package com.j3a.assurance.model;

// Generated 10 août 2015 09:53:29 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccordCima generated by hbm2java
 */
@Entity
@Table(name = "accord_cima", catalog = "zeusbd")
public class AccordCima implements java.io.Serializable {

	private AccordCimaId id;
	private Accords accords;
	private EtatCima etatCima;

	public AccordCima() {
	}

	public AccordCima(AccordCimaId id, Accords accords, EtatCima etatCima) {
		this.id = id;
		this.accords = accords;
		this.etatCima = etatCima;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeAccord", column = @Column(name = "CODE_ACCORD", nullable = false, length = 20)),
			@AttributeOverride(name = "codeEtatCima", column = @Column(name = "CODE_ETAT_CIMA", nullable = false, length = 20)) })
	public AccordCimaId getId() {
		return this.id;
	}

	public void setId(AccordCimaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ACCORD", nullable = false, insertable = false, updatable = false)
	public Accords getAccords() {
		return this.accords;
	}

	public void setAccords(Accords accords) {
		this.accords = accords;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, insertable = false, updatable = false)
	public EtatCima getEtatCima() {
		return this.etatCima;
	}

	public void setEtatCima(EtatCima etatCima) {
		this.etatCima = etatCima;
	}

}
