package com.j3a.assurance.model;

// Generated 10 août 2015 09:53:29 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Accords generated by hbm2java
 */
@Entity
@Table(name = "accords", catalog = "zeusbd")
public class Accords implements java.io.Serializable {

	private String codeAccord;
	private String clausesAccord;
	private String refTextAccord;
	private String natureAccord;
	private Set<AccordCima> accordCimas = new HashSet<AccordCima>(0);

	public Accords() {
	}

	public Accords(String codeAccord) {
		this.codeAccord = codeAccord;
	}

	public Accords(String codeAccord, String clausesAccord,
			String refTextAccord, String natureAccord,
			Set<AccordCima> accordCimas) {
		this.codeAccord = codeAccord;
		this.clausesAccord = clausesAccord;
		this.refTextAccord = refTextAccord;
		this.natureAccord = natureAccord;
		this.accordCimas = accordCimas;
	}

	@Id
	@Column(name = "CODE_ACCORD", unique = true, nullable = false, length = 20)
	public String getCodeAccord() {
		return this.codeAccord;
	}

	public void setCodeAccord(String codeAccord) {
		this.codeAccord = codeAccord;
	}

	@Column(name = "CLAUSES_ACCORD", length = 65535)
	public String getClausesAccord() {
		return this.clausesAccord;
	}

	public void setClausesAccord(String clausesAccord) {
		this.clausesAccord = clausesAccord;
	}

	@Column(name = "REF_TEXT_ACCORD", length = 65535)
	public String getRefTextAccord() {
		return this.refTextAccord;
	}

	public void setRefTextAccord(String refTextAccord) {
		this.refTextAccord = refTextAccord;
	}

	@Column(name = "NATURE_ACCORD", length = 100)
	public String getNatureAccord() {
		return this.natureAccord;
	}

	public void setNatureAccord(String natureAccord) {
		this.natureAccord = natureAccord;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accords")
	public Set<AccordCima> getAccordCimas() {
		return this.accordCimas;
	}

	public void setAccordCimas(Set<AccordCima> accordCimas) {
		this.accordCimas = accordCimas;
	}

}
