package com.j3a.assurance.model;

// Generated 10 août 2015 09:53:29 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AcExerciceId generated by hbm2java
 */
@Embeddable
public class AcExerciceId implements java.io.Serializable {

	private String codeAc;
	private String codeEtatCima;

	public AcExerciceId() {
	}

	public AcExerciceId(String codeAc, String codeEtatCima) {
		this.codeAc = codeAc;
		this.codeEtatCima = codeEtatCima;
	}

	@Column(name = "CODE_AC", nullable = false, length = 20)
	public String getCodeAc() {
		return this.codeAc;
	}

	public void setCodeAc(String codeAc) {
		this.codeAc = codeAc;
	}

	@Column(name = "CODE_ETAT_CIMA", nullable = false, length = 20)
	public String getCodeEtatCima() {
		return this.codeEtatCima;
	}

	public void setCodeEtatCima(String codeEtatCima) {
		this.codeEtatCima = codeEtatCima;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcExerciceId))
			return false;
		AcExerciceId castOther = (AcExerciceId) other;

		return ((this.getCodeAc() == castOther.getCodeAc()) || (this
				.getCodeAc() != null && castOther.getCodeAc() != null && this
				.getCodeAc().equals(castOther.getCodeAc())))
				&& ((this.getCodeEtatCima() == castOther.getCodeEtatCima()) || (this
						.getCodeEtatCima() != null
						&& castOther.getCodeEtatCima() != null && this
						.getCodeEtatCima().equals(castOther.getCodeEtatCima())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodeAc() == null ? 0 : this.getCodeAc().hashCode());
		result = 37
				* result
				+ (getCodeEtatCima() == null ? 0 : this.getCodeEtatCima()
						.hashCode());
		return result;
	}

}
