package com.j3a.assurance.model;

// Generated 6 août 2015 16:35:56 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcExercice generated by hbm2java
 */
@Entity
@Table(name = "ac_exercice", catalog = "zeusbd")
public class AcExercice implements java.io.Serializable {

	private AcExerciceId id;
	private ActionnaireConseil actionnaireConseil;
	private EtatCima etatCima;

	public AcExercice() {
	}

	public AcExercice(AcExerciceId id, ActionnaireConseil actionnaireConseil,
			EtatCima etatCima) {
		this.id = id;
		this.actionnaireConseil = actionnaireConseil;
		this.etatCima = etatCima;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeAc", column = @Column(name = "CODE_AC", nullable = false, length = 20)),
			@AttributeOverride(name = "codeEtatCima", column = @Column(name = "CODE_ETAT_CIMA", nullable = false, length = 20)) })
	public AcExerciceId getId() {
		return this.id;
	}

	public void setId(AcExerciceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_AC", nullable = false, insertable = false, updatable = false)
	public ActionnaireConseil getActionnaireConseil() {
		return this.actionnaireConseil;
	}

	public void setActionnaireConseil(ActionnaireConseil actionnaireConseil) {
		this.actionnaireConseil = actionnaireConseil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, insertable = false, updatable = false)
	public EtatCima getEtatCima() {
		return this.etatCima;
	}

	public void setEtatCima(EtatCima etatCima) {
		this.etatCima = etatCima;
	}

}
