package com.j3a.assurance.model;

// Generated 6 août 2015 16:35:56 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Achat generated by hbm2java
 */
@Entity
@Table(name = "achat", catalog = "zeusbd")
public class Achat implements java.io.Serializable {

	private String codePortefeilles;
	private Portefeuilles portefeuilles;
	private String natureAchat;
	private String cedantAchat;

	public Achat() {
	}

	public Achat(String codePortefeilles, Portefeuilles portefeuilles) {
		this.codePortefeilles = codePortefeilles;
		this.portefeuilles = portefeuilles;
	}

	public Achat(String codePortefeilles, Portefeuilles portefeuilles,
			String natureAchat, String cedantAchat) {
		this.codePortefeilles = codePortefeilles;
		this.portefeuilles = portefeuilles;
		this.natureAchat = natureAchat;
		this.cedantAchat = cedantAchat;
	}

	@Id
	@Column(name = "CODE_PORTEFEILLES", unique = true, nullable = false, length = 20)
	public String getCodePortefeilles() {
		return this.codePortefeilles;
	}

	public void setCodePortefeilles(String codePortefeilles) {
		this.codePortefeilles = codePortefeilles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_PORTEFEILLES", unique = true, nullable = false, insertable = false, updatable = false)
	public Portefeuilles getPortefeuilles() {
		return this.portefeuilles;
	}

	public void setPortefeuilles(Portefeuilles portefeuilles) {
		this.portefeuilles = portefeuilles;
	}

	@Column(name = "NATURE_ACHAT", length = 20)
	public String getNatureAchat() {
		return this.natureAchat;
	}

	public void setNatureAchat(String natureAchat) {
		this.natureAchat = natureAchat;
	}

	@Column(name = "CEDANT_ACHAT", length = 20)
	public String getCedantAchat() {
		return this.cedantAchat;
	}

	public void setCedantAchat(String cedantAchat) {
		this.cedantAchat = cedantAchat;
	}

}
