package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AffilieListeAffilieId generated by hbm2java
 */
@Embeddable
public class AffilieListeAffilieId implements java.io.Serializable {

	private String codeAffilie;
	private String codeListeAffilie;

	public AffilieListeAffilieId() {
	}

	public AffilieListeAffilieId(String codeAffilie, String codeListeAffilie) {
		this.codeAffilie = codeAffilie;
		this.codeListeAffilie = codeListeAffilie;
	}

	@Column(name = "CODE_AFFILIE", nullable = false, length = 60)
	public String getCodeAffilie() {
		return this.codeAffilie;
	}

	public void setCodeAffilie(String codeAffilie) {
		this.codeAffilie = codeAffilie;
	}

	@Column(name = "CODE_LISTE_AFFILIE", nullable = false, length = 60)
	public String getCodeListeAffilie() {
		return this.codeListeAffilie;
	}

	public void setCodeListeAffilie(String codeListeAffilie) {
		this.codeListeAffilie = codeListeAffilie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AffilieListeAffilieId))
			return false;
		AffilieListeAffilieId castOther = (AffilieListeAffilieId) other;

		return ((this.getCodeAffilie() == castOther.getCodeAffilie()) || (this
				.getCodeAffilie() != null && castOther.getCodeAffilie() != null && this
				.getCodeAffilie().equals(castOther.getCodeAffilie())))
				&& ((this.getCodeListeAffilie() == castOther
						.getCodeListeAffilie()) || (this.getCodeListeAffilie() != null
						&& castOther.getCodeListeAffilie() != null && this
						.getCodeListeAffilie().equals(
								castOther.getCodeListeAffilie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodeAffilie() == null ? 0 : this.getCodeAffilie()
						.hashCode());
		result = 37
				* result
				+ (getCodeListeAffilie() == null ? 0 : this
						.getCodeListeAffilie().hashCode());
		return result;
	}

}
