package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AffilieListeAffilie generated by hbm2java
 */
@Entity
@Table(name = "affilie_liste_affilie", catalog = "zeusbd")
public class AffilieListeAffilie implements java.io.Serializable {

	private AffilieListeAffilieId id;
	private AffilieSante affilieSante;
	private ListeAffilie listeAffilie;
	private Date dateListeAffilie;

	public AffilieListeAffilie() {
	}

	public AffilieListeAffilie(AffilieListeAffilieId id,
			AffilieSante affilieSante, ListeAffilie listeAffilie) {
		this.id = id;
		this.affilieSante = affilieSante;
		this.listeAffilie = listeAffilie;
	}

	public AffilieListeAffilie(AffilieListeAffilieId id,
			AffilieSante affilieSante, ListeAffilie listeAffilie,
			Date dateListeAffilie) {
		this.id = id;
		this.affilieSante = affilieSante;
		this.listeAffilie = listeAffilie;
		this.dateListeAffilie = dateListeAffilie;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeAffilie", column = @Column(name = "CODE_AFFILIE", nullable = false, length = 60)),
			@AttributeOverride(name = "codeListeAffilie", column = @Column(name = "CODE_LISTE_AFFILIE", nullable = false, length = 60)) })
	public AffilieListeAffilieId getId() {
		return this.id;
	}

	public void setId(AffilieListeAffilieId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_AFFILIE", nullable = false, insertable = false, updatable = false)
	public AffilieSante getAffilieSante() {
		return this.affilieSante;
	}

	public void setAffilieSante(AffilieSante affilieSante) {
		this.affilieSante = affilieSante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_LISTE_AFFILIE", nullable = false, insertable = false, updatable = false)
	public ListeAffilie getListeAffilie() {
		return this.listeAffilie;
	}

	public void setListeAffilie(ListeAffilie listeAffilie) {
		this.listeAffilie = listeAffilie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_LISTE_AFFILIE", length = 10)
	public Date getDateListeAffilie() {
		return this.dateListeAffilie;
	}

	public void setDateListeAffilie(Date dateListeAffilie) {
		this.dateListeAffilie = dateListeAffilie;
	}

}
