package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AvenantListeGestionConfieId generated by hbm2java
 */
@Embeddable
public class AvenantListeGestionConfieId implements java.io.Serializable {

	private String numAvenant;
	private String codeListeGestionConfie;

	public AvenantListeGestionConfieId() {
	}

	public AvenantListeGestionConfieId(String numAvenant,
			String codeListeGestionConfie) {
		this.numAvenant = numAvenant;
		this.codeListeGestionConfie = codeListeGestionConfie;
	}

	@Column(name = "NUM_AVENANT", nullable = false, length = 25)
	public String getNumAvenant() {
		return this.numAvenant;
	}

	public void setNumAvenant(String numAvenant) {
		this.numAvenant = numAvenant;
	}

	@Column(name = "CODE_LISTE_GESTION_CONFIE", nullable = false, length = 60)
	public String getCodeListeGestionConfie() {
		return this.codeListeGestionConfie;
	}

	public void setCodeListeGestionConfie(String codeListeGestionConfie) {
		this.codeListeGestionConfie = codeListeGestionConfie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AvenantListeGestionConfieId))
			return false;
		AvenantListeGestionConfieId castOther = (AvenantListeGestionConfieId) other;

		return ((this.getNumAvenant() == castOther.getNumAvenant()) || (this
				.getNumAvenant() != null && castOther.getNumAvenant() != null && this
				.getNumAvenant().equals(castOther.getNumAvenant())))
				&& ((this.getCodeListeGestionConfie() == castOther
						.getCodeListeGestionConfie()) || (this
						.getCodeListeGestionConfie() != null
						&& castOther.getCodeListeGestionConfie() != null && this
						.getCodeListeGestionConfie().equals(
								castOther.getCodeListeGestionConfie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getNumAvenant() == null ? 0 : this.getNumAvenant()
						.hashCode());
		result = 37
				* result
				+ (getCodeListeGestionConfie() == null ? 0 : this
						.getCodeListeGestionConfie().hashCode());
		return result;
	}

}
