package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AvListeCorpsEnginId generated by hbm2java
 */
@Embeddable
public class AvListeCorpsEnginId implements java.io.Serializable {

	private String numAvenant;
	private String codeListeCorpsEngin;

	public AvListeCorpsEnginId() {
	}

	public AvListeCorpsEnginId(String numAvenant, String codeListeCorpsEngin) {
		this.numAvenant = numAvenant;
		this.codeListeCorpsEngin = codeListeCorpsEngin;
	}

	@Column(name = "NUM_AVENANT", nullable = false, length = 25)
	public String getNumAvenant() {
		return this.numAvenant;
	}

	public void setNumAvenant(String numAvenant) {
		this.numAvenant = numAvenant;
	}

	@Column(name = "CODE_LISTE_CORPS_ENGIN", nullable = false, length = 27)
	public String getCodeListeCorpsEngin() {
		return this.codeListeCorpsEngin;
	}

	public void setCodeListeCorpsEngin(String codeListeCorpsEngin) {
		this.codeListeCorpsEngin = codeListeCorpsEngin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AvListeCorpsEnginId))
			return false;
		AvListeCorpsEnginId castOther = (AvListeCorpsEnginId) other;

		return ((this.getNumAvenant() == castOther.getNumAvenant()) || (this
				.getNumAvenant() != null && castOther.getNumAvenant() != null && this
				.getNumAvenant().equals(castOther.getNumAvenant())))
				&& ((this.getCodeListeCorpsEngin() == castOther
						.getCodeListeCorpsEngin()) || (this
						.getCodeListeCorpsEngin() != null
						&& castOther.getCodeListeCorpsEngin() != null && this
						.getCodeListeCorpsEngin().equals(
								castOther.getCodeListeCorpsEngin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getNumAvenant() == null ? 0 : this.getNumAvenant()
						.hashCode());
		result = 37
				* result
				+ (getCodeListeCorpsEngin() == null ? 0 : this
						.getCodeListeCorpsEngin().hashCode());
		return result;
	}

}
