package com.j3a.assurance.model;

// Generated 6 août 2015 16:35:56 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BrancheExercice generated by hbm2java
 */
@Entity
@Table(name = "branche_exercice", catalog = "zeusbd")
public class BrancheExercice implements java.io.Serializable {

	private BrancheExerciceId id;
	private Branche branche;
	private EtatCima etatCima;

	public BrancheExercice() {
	}

	public BrancheExercice(BrancheExerciceId id, Branche branche,
			EtatCima etatCima) {
		this.id = id;
		this.branche = branche;
		this.etatCima = etatCima;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeEtatCima", column = @Column(name = "CODE_ETAT_CIMA", nullable = false, length = 20)),
			@AttributeOverride(name = "codeBranche", column = @Column(name = "CODE_BRANCHE", nullable = false, length = 20)) })
	public BrancheExerciceId getId() {
		return this.id;
	}

	public void setId(BrancheExerciceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_BRANCHE", nullable = false, insertable = false, updatable = false)
	public Branche getBranche() {
		return this.branche;
	}

	public void setBranche(Branche branche) {
		this.branche = branche;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, insertable = false, updatable = false)
	public EtatCima getEtatCima() {
		return this.etatCima;
	}

	public void setEtatCima(EtatCima etatCima) {
		this.etatCima = etatCima;
	}

}
