package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * C10Exercice generated by hbm2java
 */
@Entity
@Table(name = "c10_exercice", catalog = "zeusbd")
public class C10Exercice implements java.io.Serializable {

	private C10ExerciceId id;
	private Etatc10bCategorie etatc10bCategorie;
	private Exercice exercice;
	private Integer nbrsinitresterminesprec;
	private Integer nbrsinitresreouvert;
	private Integer nbrsinitrestermines;
	private Integer nbrsinitresrestantapayer;
	private Integer nbrsinitrestotal;
	private Integer nbrsinitresdeclaresexoecoule;
	private BigDecimal sinistrespaiementexo;
	private BigDecimal sinistresprovisions31dec;
	private BigDecimal sinistrestotal;
	private BigDecimal sinistresprovisions31decprec;
	private BigDecimal recoursencaisses;
	private BigDecimal estimationrecoursaencaisses;
	private BigDecimal recourstotal;
	private BigDecimal reportestimation31decprecrecours;
	private BigDecimal paiementcumulesexoanterieurs;
	private BigDecimal paiementscumulestotal;
	private BigDecimal cumulrecoursencaisses;
	private BigDecimal chargenetterecours;
	private BigDecimal coutmoyennetrecours;
	private BigDecimal primesacquises;
	private BigDecimal rapportsinistresnetsderecoursauxprimes;

	public C10Exercice() {
	}

	public C10Exercice(C10ExerciceId id, Etatc10bCategorie etatc10bCategorie,
			Exercice exercice) {
		this.id = id;
		this.etatc10bCategorie = etatc10bCategorie;
		this.exercice = exercice;
	}

	public C10Exercice(C10ExerciceId id, Etatc10bCategorie etatc10bCategorie,
			Exercice exercice, Integer nbrsinitresterminesprec,
			Integer nbrsinitresreouvert, Integer nbrsinitrestermines,
			Integer nbrsinitresrestantapayer, Integer nbrsinitrestotal,
			Integer nbrsinitresdeclaresexoecoule,
			BigDecimal sinistrespaiementexo,
			BigDecimal sinistresprovisions31dec, BigDecimal sinistrestotal,
			BigDecimal sinistresprovisions31decprec,
			BigDecimal recoursencaisses,
			BigDecimal estimationrecoursaencaisses, BigDecimal recourstotal,
			BigDecimal reportestimation31decprecrecours,
			BigDecimal paiementcumulesexoanterieurs,
			BigDecimal paiementscumulestotal, BigDecimal cumulrecoursencaisses,
			BigDecimal chargenetterecours, BigDecimal coutmoyennetrecours,
			BigDecimal primesacquises,
			BigDecimal rapportsinistresnetsderecoursauxprimes) {
		this.id = id;
		this.etatc10bCategorie = etatc10bCategorie;
		this.exercice = exercice;
		this.nbrsinitresterminesprec = nbrsinitresterminesprec;
		this.nbrsinitresreouvert = nbrsinitresreouvert;
		this.nbrsinitrestermines = nbrsinitrestermines;
		this.nbrsinitresrestantapayer = nbrsinitresrestantapayer;
		this.nbrsinitrestotal = nbrsinitrestotal;
		this.nbrsinitresdeclaresexoecoule = nbrsinitresdeclaresexoecoule;
		this.sinistrespaiementexo = sinistrespaiementexo;
		this.sinistresprovisions31dec = sinistresprovisions31dec;
		this.sinistrestotal = sinistrestotal;
		this.sinistresprovisions31decprec = sinistresprovisions31decprec;
		this.recoursencaisses = recoursencaisses;
		this.estimationrecoursaencaisses = estimationrecoursaencaisses;
		this.recourstotal = recourstotal;
		this.reportestimation31decprecrecours = reportestimation31decprecrecours;
		this.paiementcumulesexoanterieurs = paiementcumulesexoanterieurs;
		this.paiementscumulestotal = paiementscumulestotal;
		this.cumulrecoursencaisses = cumulrecoursencaisses;
		this.chargenetterecours = chargenetterecours;
		this.coutmoyennetrecours = coutmoyennetrecours;
		this.primesacquises = primesacquises;
		this.rapportsinistresnetsderecoursauxprimes = rapportsinistresnetsderecoursauxprimes;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeexercice", column = @Column(name = "CODEEXERCICE", nullable = false)),
			@AttributeOverride(name = "codec10bcategorie", column = @Column(name = "CODEC10BCATEGORIE", nullable = false, length = 20)) })
	public C10ExerciceId getId() {
		return this.id;
	}

	public void setId(C10ExerciceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEC10BCATEGORIE", nullable = false, insertable = false, updatable = false)
	public Etatc10bCategorie getEtatc10bCategorie() {
		return this.etatc10bCategorie;
	}

	public void setEtatc10bCategorie(Etatc10bCategorie etatc10bCategorie) {
		this.etatc10bCategorie = etatc10bCategorie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEEXERCICE", nullable = false, insertable = false, updatable = false)
	public Exercice getExercice() {
		return this.exercice;
	}

	public void setExercice(Exercice exercice) {
		this.exercice = exercice;
	}

	@Column(name = "NBRSINITRESTERMINESPREC")
	public Integer getNbrsinitresterminesprec() {
		return this.nbrsinitresterminesprec;
	}

	public void setNbrsinitresterminesprec(Integer nbrsinitresterminesprec) {
		this.nbrsinitresterminesprec = nbrsinitresterminesprec;
	}

	@Column(name = "NBRSINITRESREOUVERT")
	public Integer getNbrsinitresreouvert() {
		return this.nbrsinitresreouvert;
	}

	public void setNbrsinitresreouvert(Integer nbrsinitresreouvert) {
		this.nbrsinitresreouvert = nbrsinitresreouvert;
	}

	@Column(name = "NBRSINITRESTERMINES")
	public Integer getNbrsinitrestermines() {
		return this.nbrsinitrestermines;
	}

	public void setNbrsinitrestermines(Integer nbrsinitrestermines) {
		this.nbrsinitrestermines = nbrsinitrestermines;
	}

	@Column(name = "NBRSINITRESRESTANTAPAYER")
	public Integer getNbrsinitresrestantapayer() {
		return this.nbrsinitresrestantapayer;
	}

	public void setNbrsinitresrestantapayer(Integer nbrsinitresrestantapayer) {
		this.nbrsinitresrestantapayer = nbrsinitresrestantapayer;
	}

	@Column(name = "NBRSINITRESTOTAL")
	public Integer getNbrsinitrestotal() {
		return this.nbrsinitrestotal;
	}

	public void setNbrsinitrestotal(Integer nbrsinitrestotal) {
		this.nbrsinitrestotal = nbrsinitrestotal;
	}

	@Column(name = "NBRSINITRESDECLARESEXOECOULE")
	public Integer getNbrsinitresdeclaresexoecoule() {
		return this.nbrsinitresdeclaresexoecoule;
	}

	public void setNbrsinitresdeclaresexoecoule(
			Integer nbrsinitresdeclaresexoecoule) {
		this.nbrsinitresdeclaresexoecoule = nbrsinitresdeclaresexoecoule;
	}

	@Column(name = "SINISTRESPAIEMENTEXO", precision = 15, scale = 3)
	public BigDecimal getSinistrespaiementexo() {
		return this.sinistrespaiementexo;
	}

	public void setSinistrespaiementexo(BigDecimal sinistrespaiementexo) {
		this.sinistrespaiementexo = sinistrespaiementexo;
	}

	@Column(name = "SINISTRESPROVISIONS31DEC", precision = 15, scale = 3)
	public BigDecimal getSinistresprovisions31dec() {
		return this.sinistresprovisions31dec;
	}

	public void setSinistresprovisions31dec(BigDecimal sinistresprovisions31dec) {
		this.sinistresprovisions31dec = sinistresprovisions31dec;
	}

	@Column(name = "SINISTRESTOTAL", precision = 15, scale = 3)
	public BigDecimal getSinistrestotal() {
		return this.sinistrestotal;
	}

	public void setSinistrestotal(BigDecimal sinistrestotal) {
		this.sinistrestotal = sinistrestotal;
	}

	@Column(name = "SINISTRESPROVISIONS31DECPREC", precision = 15, scale = 3)
	public BigDecimal getSinistresprovisions31decprec() {
		return this.sinistresprovisions31decprec;
	}

	public void setSinistresprovisions31decprec(
			BigDecimal sinistresprovisions31decprec) {
		this.sinistresprovisions31decprec = sinistresprovisions31decprec;
	}

	@Column(name = "RECOURSENCAISSES", precision = 15, scale = 3)
	public BigDecimal getRecoursencaisses() {
		return this.recoursencaisses;
	}

	public void setRecoursencaisses(BigDecimal recoursencaisses) {
		this.recoursencaisses = recoursencaisses;
	}

	@Column(name = "ESTIMATIONRECOURSAENCAISSES", precision = 15, scale = 3)
	public BigDecimal getEstimationrecoursaencaisses() {
		return this.estimationrecoursaencaisses;
	}

	public void setEstimationrecoursaencaisses(
			BigDecimal estimationrecoursaencaisses) {
		this.estimationrecoursaencaisses = estimationrecoursaencaisses;
	}

	@Column(name = "RECOURSTOTAL", precision = 15, scale = 3)
	public BigDecimal getRecourstotal() {
		return this.recourstotal;
	}

	public void setRecourstotal(BigDecimal recourstotal) {
		this.recourstotal = recourstotal;
	}

	@Column(name = "REPORTESTIMATION31DECPRECRECOURS", precision = 15, scale = 3)
	public BigDecimal getReportestimation31decprecrecours() {
		return this.reportestimation31decprecrecours;
	}

	public void setReportestimation31decprecrecours(
			BigDecimal reportestimation31decprecrecours) {
		this.reportestimation31decprecrecours = reportestimation31decprecrecours;
	}

	@Column(name = "PAIEMENTCUMULESEXOANTERIEURS", precision = 15, scale = 3)
	public BigDecimal getPaiementcumulesexoanterieurs() {
		return this.paiementcumulesexoanterieurs;
	}

	public void setPaiementcumulesexoanterieurs(
			BigDecimal paiementcumulesexoanterieurs) {
		this.paiementcumulesexoanterieurs = paiementcumulesexoanterieurs;
	}

	@Column(name = "PAIEMENTSCUMULESTOTAL", precision = 15, scale = 3)
	public BigDecimal getPaiementscumulestotal() {
		return this.paiementscumulestotal;
	}

	public void setPaiementscumulestotal(BigDecimal paiementscumulestotal) {
		this.paiementscumulestotal = paiementscumulestotal;
	}

	@Column(name = "CUMULRECOURSENCAISSES", precision = 15, scale = 3)
	public BigDecimal getCumulrecoursencaisses() {
		return this.cumulrecoursencaisses;
	}

	public void setCumulrecoursencaisses(BigDecimal cumulrecoursencaisses) {
		this.cumulrecoursencaisses = cumulrecoursencaisses;
	}

	@Column(name = "CHARGENETTERECOURS", precision = 15, scale = 3)
	public BigDecimal getChargenetterecours() {
		return this.chargenetterecours;
	}

	public void setChargenetterecours(BigDecimal chargenetterecours) {
		this.chargenetterecours = chargenetterecours;
	}

	@Column(name = "COUTMOYENNETRECOURS", precision = 15, scale = 3)
	public BigDecimal getCoutmoyennetrecours() {
		return this.coutmoyennetrecours;
	}

	public void setCoutmoyennetrecours(BigDecimal coutmoyennetrecours) {
		this.coutmoyennetrecours = coutmoyennetrecours;
	}

	@Column(name = "PRIMESACQUISES", precision = 15, scale = 3)
	public BigDecimal getPrimesacquises() {
		return this.primesacquises;
	}

	public void setPrimesacquises(BigDecimal primesacquises) {
		this.primesacquises = primesacquises;
	}

	@Column(name = "RAPPORTSINISTRESNETSDERECOURSAUXPRIMES", precision = 6, scale = 3)
	public BigDecimal getRapportsinistresnetsderecoursauxprimes() {
		return this.rapportsinistresnetsderecoursauxprimes;
	}

	public void setRapportsinistresnetsderecoursauxprimes(
			BigDecimal rapportsinistresnetsderecoursauxprimes) {
		this.rapportsinistresnetsderecoursauxprimes = rapportsinistresnetsderecoursauxprimes;
	}

}
