package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * C10ExerciceId generated by hbm2java
 */
@Embeddable
public class C10ExerciceId implements java.io.Serializable {

	private int codeexercice;
	private String codec10bcategorie;

	public C10ExerciceId() {
	}

	public C10ExerciceId(int codeexercice, String codec10bcategorie) {
		this.codeexercice = codeexercice;
		this.codec10bcategorie = codec10bcategorie;
	}

	@Column(name = "CODEEXERCICE", nullable = false)
	public int getCodeexercice() {
		return this.codeexercice;
	}

	public void setCodeexercice(int codeexercice) {
		this.codeexercice = codeexercice;
	}

	@Column(name = "CODEC10BCATEGORIE", nullable = false, length = 20)
	public String getCodec10bcategorie() {
		return this.codec10bcategorie;
	}

	public void setCodec10bcategorie(String codec10bcategorie) {
		this.codec10bcategorie = codec10bcategorie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof C10ExerciceId))
			return false;
		C10ExerciceId castOther = (C10ExerciceId) other;

		return (this.getCodeexercice() == castOther.getCodeexercice())
				&& ((this.getCodec10bcategorie() == castOther
						.getCodec10bcategorie()) || (this
						.getCodec10bcategorie() != null
						&& castOther.getCodec10bcategorie() != null && this
						.getCodec10bcategorie().equals(
								castOther.getCodec10bcategorie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodeexercice();
		result = 37
				* result
				+ (getCodec10bcategorie() == null ? 0 : this
						.getCodec10bcategorie().hashCode());
		return result;
	}

}
