package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * C9Exercice generated by hbm2java
 */
@Entity
@Table(name = "c9_exercice", catalog = "zeusbd")
public class C9Exercice implements java.io.Serializable {

	private C9ExerciceId id;
	private Etatc9Categorie etatc9Categorie;
	private Exercice exercice;
	private BigDecimal emissionc9;
	private BigDecimal annulationc9;
	private BigDecimal encaissementc9;
	private BigDecimal arrierec9;

	public C9Exercice() {
	}

	public C9Exercice(C9ExerciceId id, Etatc9Categorie etatc9Categorie,
			Exercice exercice) {
		this.id = id;
		this.etatc9Categorie = etatc9Categorie;
		this.exercice = exercice;
	}

	public C9Exercice(C9ExerciceId id, Etatc9Categorie etatc9Categorie,
			Exercice exercice, BigDecimal emissionc9, BigDecimal annulationc9,
			BigDecimal encaissementc9, BigDecimal arrierec9) {
		this.id = id;
		this.etatc9Categorie = etatc9Categorie;
		this.exercice = exercice;
		this.emissionc9 = emissionc9;
		this.annulationc9 = annulationc9;
		this.encaissementc9 = encaissementc9;
		this.arrierec9 = arrierec9;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codec9categorie", column = @Column(name = "CODEC9CATEGORIE", nullable = false, length = 20)),
			@AttributeOverride(name = "codeexercice", column = @Column(name = "CODEEXERCICE", nullable = false)) })
	public C9ExerciceId getId() {
		return this.id;
	}

	public void setId(C9ExerciceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEC9CATEGORIE", nullable = false, insertable = false, updatable = false)
	public Etatc9Categorie getEtatc9Categorie() {
		return this.etatc9Categorie;
	}

	public void setEtatc9Categorie(Etatc9Categorie etatc9Categorie) {
		this.etatc9Categorie = etatc9Categorie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEEXERCICE", nullable = false, insertable = false, updatable = false)
	public Exercice getExercice() {
		return this.exercice;
	}

	public void setExercice(Exercice exercice) {
		this.exercice = exercice;
	}

	@Column(name = "EMISSIONC9", precision = 15, scale = 3)
	public BigDecimal getEmissionc9() {
		return this.emissionc9;
	}

	public void setEmissionc9(BigDecimal emissionc9) {
		this.emissionc9 = emissionc9;
	}

	@Column(name = "ANNULATIONC9", precision = 15, scale = 3)
	public BigDecimal getAnnulationc9() {
		return this.annulationc9;
	}

	public void setAnnulationc9(BigDecimal annulationc9) {
		this.annulationc9 = annulationc9;
	}

	@Column(name = "ENCAISSEMENTC9", precision = 15, scale = 3)
	public BigDecimal getEncaissementc9() {
		return this.encaissementc9;
	}

	public void setEncaissementc9(BigDecimal encaissementc9) {
		this.encaissementc9 = encaissementc9;
	}

	@Column(name = "ARRIEREC9", precision = 15, scale = 3)
	public BigDecimal getArrierec9() {
		return this.arrierec9;
	}

	public void setArrierec9(BigDecimal arrierec9) {
		this.arrierec9 = arrierec9;
	}

}
