package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CegDebit generated by hbm2java
 */
@Entity
@Table(name = "ceg_debit", catalog = "zeusbd")
public class CegDebit implements java.io.Serializable {

	private String codeCegDebit;
	private EtatCima etatCima;
	private BigDecimal prestFraisPayeOpBruteDebitExpre;
	private BigDecimal prestFraisPayeCessRetro;
	private BigDecimal prestFraisPayeOpNettes;
	private BigDecimal provSinistreClotureEncoursOpBruttes;
	private BigDecimal provSinistreClotureEncoursCessRetro;
	private BigDecimal provSinistreClotureEncoursOpNettes;
	private BigDecimal provSinistreOuverturePrecedentOpBruttes;
	private BigDecimal provSinistreOuverturePrecedentCessRetro;
	private BigDecimal provSinistreOuverturePrecedentOpNettes;
	private BigDecimal prestFraisExerciceOpBruttes;
	private BigDecimal prestFraisExerciceRetroCess;
	private BigDecimal prestFraisExerciceOpNettes;
	private BigDecimal chargeComOpBruttes;
	private BigDecimal chargeComCessRetro;
	private BigDecimal chargeComOpNettes;
	private BigDecimal fraisPersOpBruttes;
	private BigDecimal impotsTaxesOpBruttes;
	private BigDecimal travFournServOpBruttes;
	private BigDecimal transportDeplOpBruttes;
	private BigDecimal fraisDiversOpBruttes;
	private BigDecimal dotAmort;
	private BigDecimal dotProv;
	private BigDecimal totalAutresChargesOpBruttes;
	private BigDecimal totalComChargesOpBruttes;
	private BigDecimal totalComChargesCessRetro;
	private BigDecimal totalComChargesOpNettes;
	private BigDecimal fraisFinancierTitresOpBruttes;
	private BigDecimal fraisFinancierImmblePlcmtOpBruttes;
	private BigDecimal autresFraisFinancierOpBruttes;
	private BigDecimal dotAmortiValeurPlcmtOpBruttes;
	private BigDecimal totalPlcmt;
	private BigDecimal soldeCrediteur;
	private BigDecimal totalDeb;

	public CegDebit() {
	}

	public CegDebit(String codeCegDebit) {
		this.codeCegDebit = codeCegDebit;
	}

	public CegDebit(String codeCegDebit, EtatCima etatCima,
			BigDecimal prestFraisPayeOpBruteDebitExpre,
			BigDecimal prestFraisPayeCessRetro,
			BigDecimal prestFraisPayeOpNettes,
			BigDecimal provSinistreClotureEncoursOpBruttes,
			BigDecimal provSinistreClotureEncoursCessRetro,
			BigDecimal provSinistreClotureEncoursOpNettes,
			BigDecimal provSinistreOuverturePrecedentOpBruttes,
			BigDecimal provSinistreOuverturePrecedentCessRetro,
			BigDecimal provSinistreOuverturePrecedentOpNettes,
			BigDecimal prestFraisExerciceOpBruttes,
			BigDecimal prestFraisExerciceRetroCess,
			BigDecimal prestFraisExerciceOpNettes,
			BigDecimal chargeComOpBruttes, BigDecimal chargeComCessRetro,
			BigDecimal chargeComOpNettes, BigDecimal fraisPersOpBruttes,
			BigDecimal impotsTaxesOpBruttes, BigDecimal travFournServOpBruttes,
			BigDecimal transportDeplOpBruttes, BigDecimal fraisDiversOpBruttes,
			BigDecimal dotAmort, BigDecimal dotProv,
			BigDecimal totalAutresChargesOpBruttes,
			BigDecimal totalComChargesOpBruttes,
			BigDecimal totalComChargesCessRetro,
			BigDecimal totalComChargesOpNettes,
			BigDecimal fraisFinancierTitresOpBruttes,
			BigDecimal fraisFinancierImmblePlcmtOpBruttes,
			BigDecimal autresFraisFinancierOpBruttes,
			BigDecimal dotAmortiValeurPlcmtOpBruttes, BigDecimal totalPlcmt,
			BigDecimal soldeCrediteur, BigDecimal totalDeb) {
		this.codeCegDebit = codeCegDebit;
		this.etatCima = etatCima;
		this.prestFraisPayeOpBruteDebitExpre = prestFraisPayeOpBruteDebitExpre;
		this.prestFraisPayeCessRetro = prestFraisPayeCessRetro;
		this.prestFraisPayeOpNettes = prestFraisPayeOpNettes;
		this.provSinistreClotureEncoursOpBruttes = provSinistreClotureEncoursOpBruttes;
		this.provSinistreClotureEncoursCessRetro = provSinistreClotureEncoursCessRetro;
		this.provSinistreClotureEncoursOpNettes = provSinistreClotureEncoursOpNettes;
		this.provSinistreOuverturePrecedentOpBruttes = provSinistreOuverturePrecedentOpBruttes;
		this.provSinistreOuverturePrecedentCessRetro = provSinistreOuverturePrecedentCessRetro;
		this.provSinistreOuverturePrecedentOpNettes = provSinistreOuverturePrecedentOpNettes;
		this.prestFraisExerciceOpBruttes = prestFraisExerciceOpBruttes;
		this.prestFraisExerciceRetroCess = prestFraisExerciceRetroCess;
		this.prestFraisExerciceOpNettes = prestFraisExerciceOpNettes;
		this.chargeComOpBruttes = chargeComOpBruttes;
		this.chargeComCessRetro = chargeComCessRetro;
		this.chargeComOpNettes = chargeComOpNettes;
		this.fraisPersOpBruttes = fraisPersOpBruttes;
		this.impotsTaxesOpBruttes = impotsTaxesOpBruttes;
		this.travFournServOpBruttes = travFournServOpBruttes;
		this.transportDeplOpBruttes = transportDeplOpBruttes;
		this.fraisDiversOpBruttes = fraisDiversOpBruttes;
		this.dotAmort = dotAmort;
		this.dotProv = dotProv;
		this.totalAutresChargesOpBruttes = totalAutresChargesOpBruttes;
		this.totalComChargesOpBruttes = totalComChargesOpBruttes;
		this.totalComChargesCessRetro = totalComChargesCessRetro;
		this.totalComChargesOpNettes = totalComChargesOpNettes;
		this.fraisFinancierTitresOpBruttes = fraisFinancierTitresOpBruttes;
		this.fraisFinancierImmblePlcmtOpBruttes = fraisFinancierImmblePlcmtOpBruttes;
		this.autresFraisFinancierOpBruttes = autresFraisFinancierOpBruttes;
		this.dotAmortiValeurPlcmtOpBruttes = dotAmortiValeurPlcmtOpBruttes;
		this.totalPlcmt = totalPlcmt;
		this.soldeCrediteur = soldeCrediteur;
		this.totalDeb = totalDeb;
	}

	@Id
	@Column(name = "CODE_CEG_DEBIT", unique = true, nullable = false, length = 20)
	public String getCodeCegDebit() {
		return this.codeCegDebit;
	}

	public void setCodeCegDebit(String codeCegDebit) {
		this.codeCegDebit = codeCegDebit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETAT_CIMA")
	public EtatCima getEtatCima() {
		return this.etatCima;
	}

	public void setEtatCima(EtatCima etatCima) {
		this.etatCima = etatCima;
	}

	@Column(name = "PREST_FRAIS_PAYE_OP_BRUTE_DEBIT_EXPRE", precision = 15, scale = 3)
	public BigDecimal getPrestFraisPayeOpBruteDebitExpre() {
		return this.prestFraisPayeOpBruteDebitExpre;
	}

	public void setPrestFraisPayeOpBruteDebitExpre(
			BigDecimal prestFraisPayeOpBruteDebitExpre) {
		this.prestFraisPayeOpBruteDebitExpre = prestFraisPayeOpBruteDebitExpre;
	}

	@Column(name = "PREST_FRAIS_PAYE_CESS_RETRO", precision = 15, scale = 3)
	public BigDecimal getPrestFraisPayeCessRetro() {
		return this.prestFraisPayeCessRetro;
	}

	public void setPrestFraisPayeCessRetro(BigDecimal prestFraisPayeCessRetro) {
		this.prestFraisPayeCessRetro = prestFraisPayeCessRetro;
	}

	@Column(name = "PREST_FRAIS_PAYE_OP_NETTES", precision = 15, scale = 3)
	public BigDecimal getPrestFraisPayeOpNettes() {
		return this.prestFraisPayeOpNettes;
	}

	public void setPrestFraisPayeOpNettes(BigDecimal prestFraisPayeOpNettes) {
		this.prestFraisPayeOpNettes = prestFraisPayeOpNettes;
	}

	@Column(name = "PROV_SINISTRE_CLOTURE_ENCOURS_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getProvSinistreClotureEncoursOpBruttes() {
		return this.provSinistreClotureEncoursOpBruttes;
	}

	public void setProvSinistreClotureEncoursOpBruttes(
			BigDecimal provSinistreClotureEncoursOpBruttes) {
		this.provSinistreClotureEncoursOpBruttes = provSinistreClotureEncoursOpBruttes;
	}

	@Column(name = "PROV_SINISTRE_CLOTURE_ENCOURS_CESS_RETRO", precision = 15, scale = 3)
	public BigDecimal getProvSinistreClotureEncoursCessRetro() {
		return this.provSinistreClotureEncoursCessRetro;
	}

	public void setProvSinistreClotureEncoursCessRetro(
			BigDecimal provSinistreClotureEncoursCessRetro) {
		this.provSinistreClotureEncoursCessRetro = provSinistreClotureEncoursCessRetro;
	}

	@Column(name = "PROV_SINISTRE_CLOTURE_ENCOURS_OP_NETTES", precision = 15, scale = 3)
	public BigDecimal getProvSinistreClotureEncoursOpNettes() {
		return this.provSinistreClotureEncoursOpNettes;
	}

	public void setProvSinistreClotureEncoursOpNettes(
			BigDecimal provSinistreClotureEncoursOpNettes) {
		this.provSinistreClotureEncoursOpNettes = provSinistreClotureEncoursOpNettes;
	}

	@Column(name = "PROV_SINISTRE_OUVERTURE_PRECEDENT_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getProvSinistreOuverturePrecedentOpBruttes() {
		return this.provSinistreOuverturePrecedentOpBruttes;
	}

	public void setProvSinistreOuverturePrecedentOpBruttes(
			BigDecimal provSinistreOuverturePrecedentOpBruttes) {
		this.provSinistreOuverturePrecedentOpBruttes = provSinistreOuverturePrecedentOpBruttes;
	}

	@Column(name = "PROV_SINISTRE_OUVERTURE_PRECEDENT_CESS_RETRO", precision = 15, scale = 3)
	public BigDecimal getProvSinistreOuverturePrecedentCessRetro() {
		return this.provSinistreOuverturePrecedentCessRetro;
	}

	public void setProvSinistreOuverturePrecedentCessRetro(
			BigDecimal provSinistreOuverturePrecedentCessRetro) {
		this.provSinistreOuverturePrecedentCessRetro = provSinistreOuverturePrecedentCessRetro;
	}

	@Column(name = "PROV_SINISTRE_OUVERTURE_PRECEDENT_OP_NETTES", precision = 15, scale = 3)
	public BigDecimal getProvSinistreOuverturePrecedentOpNettes() {
		return this.provSinistreOuverturePrecedentOpNettes;
	}

	public void setProvSinistreOuverturePrecedentOpNettes(
			BigDecimal provSinistreOuverturePrecedentOpNettes) {
		this.provSinistreOuverturePrecedentOpNettes = provSinistreOuverturePrecedentOpNettes;
	}

	@Column(name = "PREST_FRAIS_EXERCICE_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getPrestFraisExerciceOpBruttes() {
		return this.prestFraisExerciceOpBruttes;
	}

	public void setPrestFraisExerciceOpBruttes(
			BigDecimal prestFraisExerciceOpBruttes) {
		this.prestFraisExerciceOpBruttes = prestFraisExerciceOpBruttes;
	}

	@Column(name = "PREST_FRAIS_EXERCICE_RETRO_CESS", precision = 15, scale = 3)
	public BigDecimal getPrestFraisExerciceRetroCess() {
		return this.prestFraisExerciceRetroCess;
	}

	public void setPrestFraisExerciceRetroCess(
			BigDecimal prestFraisExerciceRetroCess) {
		this.prestFraisExerciceRetroCess = prestFraisExerciceRetroCess;
	}

	@Column(name = "PREST_FRAIS_EXERCICE_OP_NETTES", precision = 15, scale = 3)
	public BigDecimal getPrestFraisExerciceOpNettes() {
		return this.prestFraisExerciceOpNettes;
	}

	public void setPrestFraisExerciceOpNettes(
			BigDecimal prestFraisExerciceOpNettes) {
		this.prestFraisExerciceOpNettes = prestFraisExerciceOpNettes;
	}

	@Column(name = "CHARGE_COM_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getChargeComOpBruttes() {
		return this.chargeComOpBruttes;
	}

	public void setChargeComOpBruttes(BigDecimal chargeComOpBruttes) {
		this.chargeComOpBruttes = chargeComOpBruttes;
	}

	@Column(name = "CHARGE_COM_CESS_RETRO", precision = 15, scale = 3)
	public BigDecimal getChargeComCessRetro() {
		return this.chargeComCessRetro;
	}

	public void setChargeComCessRetro(BigDecimal chargeComCessRetro) {
		this.chargeComCessRetro = chargeComCessRetro;
	}

	@Column(name = "CHARGE_COM_OP_NETTES", precision = 15, scale = 3)
	public BigDecimal getChargeComOpNettes() {
		return this.chargeComOpNettes;
	}

	public void setChargeComOpNettes(BigDecimal chargeComOpNettes) {
		this.chargeComOpNettes = chargeComOpNettes;
	}

	@Column(name = "FRAIS_PERS_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getFraisPersOpBruttes() {
		return this.fraisPersOpBruttes;
	}

	public void setFraisPersOpBruttes(BigDecimal fraisPersOpBruttes) {
		this.fraisPersOpBruttes = fraisPersOpBruttes;
	}

	@Column(name = "IMPOTS_TAXES_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getImpotsTaxesOpBruttes() {
		return this.impotsTaxesOpBruttes;
	}

	public void setImpotsTaxesOpBruttes(BigDecimal impotsTaxesOpBruttes) {
		this.impotsTaxesOpBruttes = impotsTaxesOpBruttes;
	}

	@Column(name = "TRAV_FOURN_SERV_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getTravFournServOpBruttes() {
		return this.travFournServOpBruttes;
	}

	public void setTravFournServOpBruttes(BigDecimal travFournServOpBruttes) {
		this.travFournServOpBruttes = travFournServOpBruttes;
	}

	@Column(name = "TRANSPORT_DEPL_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getTransportDeplOpBruttes() {
		return this.transportDeplOpBruttes;
	}

	public void setTransportDeplOpBruttes(BigDecimal transportDeplOpBruttes) {
		this.transportDeplOpBruttes = transportDeplOpBruttes;
	}

	@Column(name = "FRAIS_DIVERS_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getFraisDiversOpBruttes() {
		return this.fraisDiversOpBruttes;
	}

	public void setFraisDiversOpBruttes(BigDecimal fraisDiversOpBruttes) {
		this.fraisDiversOpBruttes = fraisDiversOpBruttes;
	}

	@Column(name = "DOT_AMORT", precision = 15, scale = 3)
	public BigDecimal getDotAmort() {
		return this.dotAmort;
	}

	public void setDotAmort(BigDecimal dotAmort) {
		this.dotAmort = dotAmort;
	}

	@Column(name = "DOT_PROV", precision = 15, scale = 3)
	public BigDecimal getDotProv() {
		return this.dotProv;
	}

	public void setDotProv(BigDecimal dotProv) {
		this.dotProv = dotProv;
	}

	@Column(name = "TOTAL_AUTRES_CHARGES_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getTotalAutresChargesOpBruttes() {
		return this.totalAutresChargesOpBruttes;
	}

	public void setTotalAutresChargesOpBruttes(
			BigDecimal totalAutresChargesOpBruttes) {
		this.totalAutresChargesOpBruttes = totalAutresChargesOpBruttes;
	}

	@Column(name = "TOTAL_COM_CHARGES_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getTotalComChargesOpBruttes() {
		return this.totalComChargesOpBruttes;
	}

	public void setTotalComChargesOpBruttes(BigDecimal totalComChargesOpBruttes) {
		this.totalComChargesOpBruttes = totalComChargesOpBruttes;
	}

	@Column(name = "TOTAL_COM_CHARGES_CESS_RETRO", precision = 15, scale = 3)
	public BigDecimal getTotalComChargesCessRetro() {
		return this.totalComChargesCessRetro;
	}

	public void setTotalComChargesCessRetro(BigDecimal totalComChargesCessRetro) {
		this.totalComChargesCessRetro = totalComChargesCessRetro;
	}

	@Column(name = "TOTAL_COM_CHARGES_OP_NETTES", precision = 15, scale = 3)
	public BigDecimal getTotalComChargesOpNettes() {
		return this.totalComChargesOpNettes;
	}

	public void setTotalComChargesOpNettes(BigDecimal totalComChargesOpNettes) {
		this.totalComChargesOpNettes = totalComChargesOpNettes;
	}

	@Column(name = "FRAIS_FINANCIER_TITRES_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getFraisFinancierTitresOpBruttes() {
		return this.fraisFinancierTitresOpBruttes;
	}

	public void setFraisFinancierTitresOpBruttes(
			BigDecimal fraisFinancierTitresOpBruttes) {
		this.fraisFinancierTitresOpBruttes = fraisFinancierTitresOpBruttes;
	}

	@Column(name = "FRAIS_FINANCIER_IMMBLE_PLCMT_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getFraisFinancierImmblePlcmtOpBruttes() {
		return this.fraisFinancierImmblePlcmtOpBruttes;
	}

	public void setFraisFinancierImmblePlcmtOpBruttes(
			BigDecimal fraisFinancierImmblePlcmtOpBruttes) {
		this.fraisFinancierImmblePlcmtOpBruttes = fraisFinancierImmblePlcmtOpBruttes;
	}

	@Column(name = "AUTRES_FRAIS_FINANCIER_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getAutresFraisFinancierOpBruttes() {
		return this.autresFraisFinancierOpBruttes;
	}

	public void setAutresFraisFinancierOpBruttes(
			BigDecimal autresFraisFinancierOpBruttes) {
		this.autresFraisFinancierOpBruttes = autresFraisFinancierOpBruttes;
	}

	@Column(name = "DOT_AMORTI_VALEUR_PLCMT_OP_BRUTTES", precision = 15, scale = 3)
	public BigDecimal getDotAmortiValeurPlcmtOpBruttes() {
		return this.dotAmortiValeurPlcmtOpBruttes;
	}

	public void setDotAmortiValeurPlcmtOpBruttes(
			BigDecimal dotAmortiValeurPlcmtOpBruttes) {
		this.dotAmortiValeurPlcmtOpBruttes = dotAmortiValeurPlcmtOpBruttes;
	}

	@Column(name = "TOTAL_PLCMT", precision = 15, scale = 3)
	public BigDecimal getTotalPlcmt() {
		return this.totalPlcmt;
	}

	public void setTotalPlcmt(BigDecimal totalPlcmt) {
		this.totalPlcmt = totalPlcmt;
	}

	@Column(name = "SOLDE_CREDITEUR", precision = 15, scale = 3)
	public BigDecimal getSoldeCrediteur() {
		return this.soldeCrediteur;
	}

	public void setSoldeCrediteur(BigDecimal soldeCrediteur) {
		this.soldeCrediteur = soldeCrediteur;
	}

	@Column(name = "TOTAL_DEB", precision = 15, scale = 3)
	public BigDecimal getTotalDeb() {
		return this.totalDeb;
	}

	public void setTotalDeb(BigDecimal totalDeb) {
		this.totalDeb = totalDeb;
	}

}
