package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClasseGc generated by hbm2java
 */
@Entity
@Table(name = "classe_gc", catalog = "zeusbd")
public class ClasseGc implements java.io.Serializable {

	private String codeClasseGc;
	private String libelleClasseGc;
	private String natureClasseGc;
	private String tarifClasseGc;
	private Set<GestionConfiee> gestionConfiees = new HashSet<GestionConfiee>(0);

	public ClasseGc() {
	}

	public ClasseGc(String codeClasseGc) {
		this.codeClasseGc = codeClasseGc;
	}

	public ClasseGc(String codeClasseGc, String libelleClasseGc,
			String natureClasseGc, String tarifClasseGc,
			Set<GestionConfiee> gestionConfiees) {
		this.codeClasseGc = codeClasseGc;
		this.libelleClasseGc = libelleClasseGc;
		this.natureClasseGc = natureClasseGc;
		this.tarifClasseGc = tarifClasseGc;
		this.gestionConfiees = gestionConfiees;
	}

	@Id
	@Column(name = "CODE_CLASSE_GC", unique = true, nullable = false, length = 30)
	public String getCodeClasseGc() {
		return this.codeClasseGc;
	}

	public void setCodeClasseGc(String codeClasseGc) {
		this.codeClasseGc = codeClasseGc;
	}

	@Column(name = "LIBELLE_CLASSE_GC", length = 60)
	public String getLibelleClasseGc() {
		return this.libelleClasseGc;
	}

	public void setLibelleClasseGc(String libelleClasseGc) {
		this.libelleClasseGc = libelleClasseGc;
	}

	@Column(name = "NATURE_CLASSE_GC", length = 30)
	public String getNatureClasseGc() {
		return this.natureClasseGc;
	}

	public void setNatureClasseGc(String natureClasseGc) {
		this.natureClasseGc = natureClasseGc;
	}

	@Column(name = "TARIF_CLASSE_GC", length = 60)
	public String getTarifClasseGc() {
		return this.tarifClasseGc;
	}

	public void setTarifClasseGc(String tarifClasseGc) {
		this.tarifClasseGc = tarifClasseGc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classeGc")
	public Set<GestionConfiee> getGestionConfiees() {
		return this.gestionConfiees;
	}

	public void setGestionConfiees(Set<GestionConfiee> gestionConfiees) {
		this.gestionConfiees = gestionConfiees;
	}

}
