package com.j3a.assurance.model;

// Generated 12 août 2015 16:21:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompagnieAssurance generated by hbm2java
 */
@Entity
@Table(name = "compagnie_assurance", catalog = "zeusbd")
public class CompagnieAssurance implements java.io.Serializable {

	private String codeCompagnieAssurance;
	private Pays pays;
	private UserRole userRole;
	private String raisonSocialeCompAss;
	private String adresseCompAss;
	private String telCompAss;
	private String siteWebCompAss;
	private String deviseCompAss;
	private String loginCompAss;
	private String motPasseCompAss;
	private Float tauxReduction;
	private Float tauxAccessoire;
	private Boolean activiteCompagnie;
	private Set<Tarifweb> tarifwebs = new HashSet<Tarifweb>(0);
	private Set<Avenant> avenants = new HashSet<Avenant>(0);
	private Set<CompteCompagnieAssurance> compteCompagnieAssurances = new HashSet<CompteCompagnieAssurance>(
			0);
	private Set<OptionsGarantie> optionsGaranties = new HashSet<OptionsGarantie>(
			0);

	public CompagnieAssurance() {
	}

	public CompagnieAssurance(String codeCompagnieAssurance, Pays pays,
			UserRole userRole) {
		this.codeCompagnieAssurance = codeCompagnieAssurance;
		this.pays = pays;
		this.userRole = userRole;
	}

	public CompagnieAssurance(String codeCompagnieAssurance, Pays pays,
			UserRole userRole, String raisonSocialeCompAss,
			String adresseCompAss, String telCompAss, String siteWebCompAss,
			String deviseCompAss, String loginCompAss, String motPasseCompAss,
			Float tauxReduction, Float tauxAccessoire,
			Boolean activiteCompagnie, Set<Tarifweb> tarifwebs,
			Set<Avenant> avenants,
			Set<CompteCompagnieAssurance> compteCompagnieAssurances,
			Set<OptionsGarantie> optionsGaranties) {
		this.codeCompagnieAssurance = codeCompagnieAssurance;
		this.pays = pays;
		this.userRole = userRole;
		this.raisonSocialeCompAss = raisonSocialeCompAss;
		this.adresseCompAss = adresseCompAss;
		this.telCompAss = telCompAss;
		this.siteWebCompAss = siteWebCompAss;
		this.deviseCompAss = deviseCompAss;
		this.loginCompAss = loginCompAss;
		this.motPasseCompAss = motPasseCompAss;
		this.tauxReduction = tauxReduction;
		this.tauxAccessoire = tauxAccessoire;
		this.activiteCompagnie = activiteCompagnie;
		this.tarifwebs = tarifwebs;
		this.avenants = avenants;
		this.compteCompagnieAssurances = compteCompagnieAssurances;
		this.optionsGaranties = optionsGaranties;
	}

	@Id
	@Column(name = "CODE_COMPAGNIE_ASSURANCE", unique = true, nullable = false, length = 16)
	public String getCodeCompagnieAssurance() {
		return this.codeCompagnieAssurance;
	}

	public void setCodeCompagnieAssurance(String codeCompagnieAssurance) {
		this.codeCompagnieAssurance = codeCompagnieAssurance;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_PAYS", nullable = false)
	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USER_ROLE_ID", nullable = false)
	public UserRole getUserRole() {
		return this.userRole;
	}

	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}

	@Column(name = "RAISON_SOCIALE_COMP_ASS", length = 225)
	public String getRaisonSocialeCompAss() {
		return this.raisonSocialeCompAss;
	}

	public void setRaisonSocialeCompAss(String raisonSocialeCompAss) {
		this.raisonSocialeCompAss = raisonSocialeCompAss;
	}

	@Column(name = "ADRESSE_COMP_ASS", length = 100)
	public String getAdresseCompAss() {
		return this.adresseCompAss;
	}

	public void setAdresseCompAss(String adresseCompAss) {
		this.adresseCompAss = adresseCompAss;
	}

	@Column(name = "TEL_COMP_ASS", length = 20)
	public String getTelCompAss() {
		return this.telCompAss;
	}

	public void setTelCompAss(String telCompAss) {
		this.telCompAss = telCompAss;
	}

	@Column(name = "SITE_WEB_COMP_ASS", length = 100)
	public String getSiteWebCompAss() {
		return this.siteWebCompAss;
	}

	public void setSiteWebCompAss(String siteWebCompAss) {
		this.siteWebCompAss = siteWebCompAss;
	}

	@Column(name = "DEVISE_COMP_ASS", length = 20)
	public String getDeviseCompAss() {
		return this.deviseCompAss;
	}

	public void setDeviseCompAss(String deviseCompAss) {
		this.deviseCompAss = deviseCompAss;
	}

	@Column(name = "LOGIN_COMP_ASS", length = 30)
	public String getLoginCompAss() {
		return this.loginCompAss;
	}

	public void setLoginCompAss(String loginCompAss) {
		this.loginCompAss = loginCompAss;
	}

	@Column(name = "MOT_PASSE_COMP_ASS", length = 20)
	public String getMotPasseCompAss() {
		return this.motPasseCompAss;
	}

	public void setMotPasseCompAss(String motPasseCompAss) {
		this.motPasseCompAss = motPasseCompAss;
	}

	@Column(name = "TAUX_REDUCTION", precision = 12, scale = 0)
	public Float getTauxReduction() {
		return tauxReduction;
	}

	public void setTauxReduction(Float tauxReduction) {
		this.tauxReduction = tauxReduction;
	}
	
	@Column(name = "TAUX_ACCESSOIRE", precision = 12, scale = 0)
	public Float getTauxAccessoire() {
		return tauxAccessoire;
	}

	public void setTauxAccessoire(Float tauxAccessoire) {
		this.tauxAccessoire = tauxAccessoire;
	}

	@Column(name = "ACTIVITE_COMPAGNIE")
	public Boolean getActiviteCompagnie() {
		return this.activiteCompagnie;
	}

	public void setActiviteCompagnie(Boolean activiteCompagnie) {
		this.activiteCompagnie = activiteCompagnie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compagnieAssurance")
	public Set<Tarifweb> getTarifwebs() {
		return this.tarifwebs;
	}

	public void setTarifwebs(Set<Tarifweb> tarifwebs) {
		this.tarifwebs = tarifwebs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compagnieAssurance")
	public Set<Avenant> getAvenants() {
		return this.avenants;
	}

	public void setAvenants(Set<Avenant> avenants) {
		this.avenants = avenants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compagnieAssurance")
	public Set<CompteCompagnieAssurance> getCompteCompagnieAssurances() {
		return this.compteCompagnieAssurances;
	}

	public void setCompteCompagnieAssurances(
			Set<CompteCompagnieAssurance> compteCompagnieAssurances) {
		this.compteCompagnieAssurances = compteCompagnieAssurances;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "compagnieAssurance")
	public Set<OptionsGarantie> getOptionsGaranties() {
		return this.optionsGaranties;
	}

	public void setOptionsGaranties(Set<OptionsGarantie> optionsGaranties) {
		this.optionsGaranties = optionsGaranties;
	}

}
