package com.j3a.assurance.model;

// Generated 12 août 2015 16:21:18 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompteCompagnieAssurance generated by hbm2java
 */
@Entity
@Table(name = "compte_compagnie_assurance", catalog = "zeusbd")
public class CompteCompagnieAssurance implements java.io.Serializable {

	private String codeCompteCompAss;
	private CompagnieAssurance compagnieAssurance;
	private BigDecimal totalPrimeDue;
	private BigDecimal totamPrimeRecu;
	private BigDecimal primeAVersee;
	private Date dateCreaCompte;
	private Set<ReglementCompagnieAssurance> reglementCompagnieAssurances = new HashSet<ReglementCompagnieAssurance>(
			0);

	public CompteCompagnieAssurance() {
	}

	public CompteCompagnieAssurance(String codeCompteCompAss,
			CompagnieAssurance compagnieAssurance) {
		this.codeCompteCompAss = codeCompteCompAss;
		this.compagnieAssurance = compagnieAssurance;
	}

	public CompteCompagnieAssurance(String codeCompteCompAss,
			CompagnieAssurance compagnieAssurance, BigDecimal totalPrimeDue,
			BigDecimal totamPrimeRecu, BigDecimal primeAVersee,
			Date dateCreaCompte,
			Set<ReglementCompagnieAssurance> reglementCompagnieAssurances) {
		this.codeCompteCompAss = codeCompteCompAss;
		this.compagnieAssurance = compagnieAssurance;
		this.totalPrimeDue = totalPrimeDue;
		this.totamPrimeRecu = totamPrimeRecu;
		this.primeAVersee = primeAVersee;
		this.dateCreaCompte = dateCreaCompte;
		this.reglementCompagnieAssurances = reglementCompagnieAssurances;
	}

	@Id
	@Column(name = "CODE_COMPTE_COMP_ASS", unique = true, nullable = false, length = 20)
	public String getCodeCompteCompAss() {
		return this.codeCompteCompAss;
	}

	public void setCodeCompteCompAss(String codeCompteCompAss) {
		this.codeCompteCompAss = codeCompteCompAss;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_COMPAGNIE_ASSURANCE", nullable = false)
	public CompagnieAssurance getCompagnieAssurance() {
		return this.compagnieAssurance;
	}

	public void setCompagnieAssurance(CompagnieAssurance compagnieAssurance) {
		this.compagnieAssurance = compagnieAssurance;
	}

	@Column(name = "TOTAL_PRIME_DUE", precision = 15, scale = 3)
	public BigDecimal getTotalPrimeDue() {
		return this.totalPrimeDue;
	}

	public void setTotalPrimeDue(BigDecimal totalPrimeDue) {
		this.totalPrimeDue = totalPrimeDue;
	}

	@Column(name = "TOTAM_PRIME_RECU", precision = 15, scale = 3)
	public BigDecimal getTotamPrimeRecu() {
		return this.totamPrimeRecu;
	}

	public void setTotamPrimeRecu(BigDecimal totamPrimeRecu) {
		this.totamPrimeRecu = totamPrimeRecu;
	}

	@Column(name = "PRIME_A_VERSEE", precision = 15, scale = 3)
	public BigDecimal getPrimeAVersee() {
		return this.primeAVersee;
	}

	public void setPrimeAVersee(BigDecimal primeAVersee) {
		this.primeAVersee = primeAVersee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CREA_COMPTE", length = 10)
	public Date getDateCreaCompte() {
		return this.dateCreaCompte;
	}

	public void setDateCreaCompte(Date dateCreaCompte) {
		this.dateCreaCompte = dateCreaCompte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteCompagnieAssurance")
	public Set<ReglementCompagnieAssurance> getReglementCompagnieAssurances() {
		return this.reglementCompagnieAssurances;
	}

	public void setReglementCompagnieAssurances(
			Set<ReglementCompagnieAssurance> reglementCompagnieAssurances) {
		this.reglementCompagnieAssurances = reglementCompagnieAssurances;
	}

}
