package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conducteur generated by hbm2java
 */
@Entity
@Table(name = "conducteur", catalog = "zeusbd")
public class Conducteur implements java.io.Serializable {

	private String numCond;
	private String nonCond;
	private String prenomsCond;
	private Date dateNaissCond;
	private String lieuNaisCond;
	private String typpermiscond;
	private String numpermiscond;
	private Short dureepermiscond;
	private String categsocioprocond;
	private String typcatsocprocond;
	private Set<ConduireVehicule> conduireVehicules = new HashSet<ConduireVehicule>(
			0);

	public Conducteur() {
	}

	public Conducteur(String numCond) {
		this.numCond = numCond;
	}

	public Conducteur(String numCond, String nonCond, String prenomsCond,
			Date dateNaissCond, String lieuNaisCond, String typpermiscond,
			String numpermiscond, Short dureepermiscond,
			String categsocioprocond, String typcatsocprocond,
			Set<ConduireVehicule> conduireVehicules) {
		this.numCond = numCond;
		this.nonCond = nonCond;
		this.prenomsCond = prenomsCond;
		this.dateNaissCond = dateNaissCond;
		this.lieuNaisCond = lieuNaisCond;
		this.typpermiscond = typpermiscond;
		this.numpermiscond = numpermiscond;
		this.dureepermiscond = dureepermiscond;
		this.categsocioprocond = categsocioprocond;
		this.typcatsocprocond = typcatsocprocond;
		this.conduireVehicules = conduireVehicules;
	}

	@Id
	@Column(name = "NUM_COND", unique = true, nullable = false, length = 15)
	public String getNumCond() {
		return this.numCond;
	}

	public void setNumCond(String numCond) {
		this.numCond = numCond;
	}

	@Column(name = "NON_COND", length = 15)
	public String getNonCond() {
		return this.nonCond;
	}

	public void setNonCond(String nonCond) {
		this.nonCond = nonCond;
	}

	@Column(name = "PRENOMS_COND", length = 25)
	public String getPrenomsCond() {
		return this.prenomsCond;
	}

	public void setPrenomsCond(String prenomsCond) {
		this.prenomsCond = prenomsCond;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAISS_COND", length = 10)
	public Date getDateNaissCond() {
		return this.dateNaissCond;
	}

	public void setDateNaissCond(Date dateNaissCond) {
		this.dateNaissCond = dateNaissCond;
	}

	@Column(name = "LIEU_NAIS_COND", length = 15)
	public String getLieuNaisCond() {
		return this.lieuNaisCond;
	}

	public void setLieuNaisCond(String lieuNaisCond) {
		this.lieuNaisCond = lieuNaisCond;
	}

	@Column(name = "TYPPERMISCOND", length = 15)
	public String getTyppermiscond() {
		return this.typpermiscond;
	}

	public void setTyppermiscond(String typpermiscond) {
		this.typpermiscond = typpermiscond;
	}

	@Column(name = "NUMPERMISCOND", length = 25)
	public String getNumpermiscond() {
		return this.numpermiscond;
	}

	public void setNumpermiscond(String numpermiscond) {
		this.numpermiscond = numpermiscond;
	}

	@Column(name = "DUREEPERMISCOND")
	public Short getDureepermiscond() {
		return this.dureepermiscond;
	}

	public void setDureepermiscond(Short dureepermiscond) {
		this.dureepermiscond = dureepermiscond;
	}

	@Column(name = "CATEGSOCIOPROCOND", length = 25)
	public String getCategsocioprocond() {
		return this.categsocioprocond;
	}

	public void setCategsocioprocond(String categsocioprocond) {
		this.categsocioprocond = categsocioprocond;
	}

	@Column(name = "TYPCATSOCPROCOND", length = 25)
	public String getTypcatsocprocond() {
		return this.typcatsocprocond;
	}

	public void setTypcatsocprocond(String typcatsocprocond) {
		this.typcatsocprocond = typcatsocprocond;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conducteur")
	public Set<ConduireVehicule> getConduireVehicules() {
		return this.conduireVehicules;
	}

	public void setConduireVehicules(Set<ConduireVehicule> conduireVehicules) {
		this.conduireVehicules = conduireVehicules;
	}

}
