package com.j3a.assurance.model;

// Generated 10 août 2015 09:53:29 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DirectionExercice generated by hbm2java
 */
@Entity
@Table(name = "direction_exercice", catalog = "zeusbd")
public class DirectionExercice implements java.io.Serializable {

	private DirectionExerciceId id;
	private Direction direction;
	private EtatCima etatCima;

	public DirectionExercice() {
	}

	public DirectionExercice(DirectionExerciceId id, Direction direction,
			EtatCima etatCima) {
		this.id = id;
		this.direction = direction;
		this.etatCima = etatCima;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codePdirect", column = @Column(name = "CODE_PDIRECT", nullable = false, length = 20)),
			@AttributeOverride(name = "codeEtatCima", column = @Column(name = "CODE_ETAT_CIMA", nullable = false, length = 20)) })
	public DirectionExerciceId getId() {
		return this.id;
	}

	public void setId(DirectionExerciceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_PDIRECT", nullable = false, insertable = false, updatable = false)
	public Direction getDirection() {
		return this.direction;
	}

	public void setDirection(Direction direction) {
		this.direction = direction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, insertable = false, updatable = false)
	public EtatCima getEtatCima() {
		return this.etatCima;
	}

	public void setEtatCima(EtatCima etatCima) {
		this.etatCima = etatCima;
	}

}
