package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Direction generated by hbm2java
 */
@Entity
@Table(name = "direction", catalog = "zeusbd")
public class Direction implements java.io.Serializable {

	private String codePdirect;
	private String nomPdirect;
	private String prenomsPdirect;
	private Date dateNaisPdirect;
	private String lieuNaisPdirect;
	private String sexePdirect;
	private String nationalitePdirect;
	private String qualificationPdirect;
	private String gradePdirect;
	private String contactPdirect;
	private Set<EtatCima> etatCimas = new HashSet<EtatCima>(0);

	public Direction() {
	}

	public Direction(String codePdirect) {
		this.codePdirect = codePdirect;
	}

	public Direction(String codePdirect, String nomPdirect,
			String prenomsPdirect, Date dateNaisPdirect,
			String lieuNaisPdirect, String sexePdirect,
			String nationalitePdirect, String qualificationPdirect,
			String gradePdirect, String contactPdirect, Set<EtatCima> etatCimas) {
		this.codePdirect = codePdirect;
		this.nomPdirect = nomPdirect;
		this.prenomsPdirect = prenomsPdirect;
		this.dateNaisPdirect = dateNaisPdirect;
		this.lieuNaisPdirect = lieuNaisPdirect;
		this.sexePdirect = sexePdirect;
		this.nationalitePdirect = nationalitePdirect;
		this.qualificationPdirect = qualificationPdirect;
		this.gradePdirect = gradePdirect;
		this.contactPdirect = contactPdirect;
		this.etatCimas = etatCimas;
	}

	@Id
	@Column(name = "CODE_PDIRECT", unique = true, nullable = false, length = 20)
	public String getCodePdirect() {
		return this.codePdirect;
	}

	public void setCodePdirect(String codePdirect) {
		this.codePdirect = codePdirect;
	}

	@Column(name = "NOM_PDIRECT", length = 20)
	public String getNomPdirect() {
		return this.nomPdirect;
	}

	public void setNomPdirect(String nomPdirect) {
		this.nomPdirect = nomPdirect;
	}

	@Column(name = "PRENOMS_PDIRECT", length = 30)
	public String getPrenomsPdirect() {
		return this.prenomsPdirect;
	}

	public void setPrenomsPdirect(String prenomsPdirect) {
		this.prenomsPdirect = prenomsPdirect;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAIS_PDIRECT", length = 10)
	public Date getDateNaisPdirect() {
		return this.dateNaisPdirect;
	}

	public void setDateNaisPdirect(Date dateNaisPdirect) {
		this.dateNaisPdirect = dateNaisPdirect;
	}

	@Column(name = "LIEU_NAIS_PDIRECT", length = 30)
	public String getLieuNaisPdirect() {
		return this.lieuNaisPdirect;
	}

	public void setLieuNaisPdirect(String lieuNaisPdirect) {
		this.lieuNaisPdirect = lieuNaisPdirect;
	}

	@Column(name = "SEXE_PDIRECT", length = 10)
	public String getSexePdirect() {
		return this.sexePdirect;
	}

	public void setSexePdirect(String sexePdirect) {
		this.sexePdirect = sexePdirect;
	}

	@Column(name = "NATIONALITE_PDIRECT", length = 20)
	public String getNationalitePdirect() {
		return this.nationalitePdirect;
	}

	public void setNationalitePdirect(String nationalitePdirect) {
		this.nationalitePdirect = nationalitePdirect;
	}

	@Column(name = "QUALIFICATION_PDIRECT", length = 50)
	public String getQualificationPdirect() {
		return this.qualificationPdirect;
	}

	public void setQualificationPdirect(String qualificationPdirect) {
		this.qualificationPdirect = qualificationPdirect;
	}

	@Column(name = "GRADE_PDIRECT", length = 50)
	public String getGradePdirect() {
		return this.gradePdirect;
	}

	public void setGradePdirect(String gradePdirect) {
		this.gradePdirect = gradePdirect;
	}

	@Column(name = "CONTACT_PDIRECT", length = 50)
	public String getContactPdirect() {
		return this.contactPdirect;
	}

	public void setContactPdirect(String contactPdirect) {
		this.contactPdirect = contactPdirect;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "direction_exercice", catalog = "zeusbd", joinColumns = { @JoinColumn(name = "CODE_PDIRECT", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, updatable = false) })
	public Set<EtatCima> getEtatCimas() {
		return this.etatCimas;
	}

	public void setEtatCimas(Set<EtatCima> etatCimas) {
		this.etatCimas = etatCimas;
	}

}
