package com.j3a.assurance.model;

// Generated 10 août 2015 09:53:29 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EffectifPersoEtatCima generated by hbm2java
 */
@Entity
@Table(name = "effectif_perso_etat_cima", catalog = "zeusbd")
public class EffectifPersoEtatCima implements java.io.Serializable {

	private EffectifPersoEtatCimaId id;
	private EffectifPersonnel effectifPersonnel;
	private EtatCima etatCima;

	public EffectifPersoEtatCima() {
	}

	public EffectifPersoEtatCima(EffectifPersoEtatCimaId id,
			EffectifPersonnel effectifPersonnel, EtatCima etatCima) {
		this.id = id;
		this.effectifPersonnel = effectifPersonnel;
		this.etatCima = etatCima;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeEffectifPersonnel", column = @Column(name = "CODE_EFFECTIF_PERSONNEL", nullable = false, length = 20)),
			@AttributeOverride(name = "codeEtatCima", column = @Column(name = "CODE_ETAT_CIMA", nullable = false, length = 20)) })
	public EffectifPersoEtatCimaId getId() {
		return this.id;
	}

	public void setId(EffectifPersoEtatCimaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_EFFECTIF_PERSONNEL", nullable = false, insertable = false, updatable = false)
	public EffectifPersonnel getEffectifPersonnel() {
		return this.effectifPersonnel;
	}

	public void setEffectifPersonnel(EffectifPersonnel effectifPersonnel) {
		this.effectifPersonnel = effectifPersonnel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, insertable = false, updatable = false)
	public EtatCima getEtatCima() {
		return this.etatCima;
	}

	public void setEtatCima(EtatCima etatCima) {
		this.etatCima = etatCima;
	}

}
