package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EngagementsActifrep generated by hbm2java
 */
@Entity
@Table(name = "engagements_actifrep", catalog = "zeusbd")
public class EngagementsActifrep implements java.io.Serializable {

	private EngagementsActifrepId id;
	private ActifsRepresentatifs actifsRepresentatifs;
	private EtatC4 etatC4;
	private BigDecimal prixachatourevient;
	private BigDecimal valeurrealisation;
	private BigDecimal valeurcouverture;

	public EngagementsActifrep() {
	}

	public EngagementsActifrep(EngagementsActifrepId id,
			ActifsRepresentatifs actifsRepresentatifs, EtatC4 etatC4) {
		this.id = id;
		this.actifsRepresentatifs = actifsRepresentatifs;
		this.etatC4 = etatC4;
	}

	public EngagementsActifrep(EngagementsActifrepId id,
			ActifsRepresentatifs actifsRepresentatifs, EtatC4 etatC4,
			BigDecimal prixachatourevient, BigDecimal valeurrealisation,
			BigDecimal valeurcouverture) {
		this.id = id;
		this.actifsRepresentatifs = actifsRepresentatifs;
		this.etatC4 = etatC4;
		this.prixachatourevient = prixachatourevient;
		this.valeurrealisation = valeurrealisation;
		this.valeurcouverture = valeurcouverture;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeengagements", column = @Column(name = "CODEENGAGEMENTS", nullable = false, length = 20)),
			@AttributeOverride(name = "codeactifrep", column = @Column(name = "CODEACTIFREP", nullable = false, length = 20)) })
	public EngagementsActifrepId getId() {
		return this.id;
	}

	public void setId(EngagementsActifrepId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEACTIFREP", nullable = false, insertable = false, updatable = false)
	public ActifsRepresentatifs getActifsRepresentatifs() {
		return this.actifsRepresentatifs;
	}

	public void setActifsRepresentatifs(
			ActifsRepresentatifs actifsRepresentatifs) {
		this.actifsRepresentatifs = actifsRepresentatifs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEENGAGEMENTS", nullable = false, insertable = false, updatable = false)
	public EtatC4 getEtatC4() {
		return this.etatC4;
	}

	public void setEtatC4(EtatC4 etatC4) {
		this.etatC4 = etatC4;
	}

	@Column(name = "PRIXACHATOUREVIENT", precision = 15, scale = 3)
	public BigDecimal getPrixachatourevient() {
		return this.prixachatourevient;
	}

	public void setPrixachatourevient(BigDecimal prixachatourevient) {
		this.prixachatourevient = prixachatourevient;
	}

	@Column(name = "VALEURREALISATION", precision = 15, scale = 3)
	public BigDecimal getValeurrealisation() {
		return this.valeurrealisation;
	}

	public void setValeurrealisation(BigDecimal valeurrealisation) {
		this.valeurrealisation = valeurrealisation;
	}

	@Column(name = "VALEURCOUVERTURE", precision = 15, scale = 3)
	public BigDecimal getValeurcouverture() {
		return this.valeurcouverture;
	}

	public void setValeurcouverture(BigDecimal valeurcouverture) {
		this.valeurcouverture = valeurcouverture;
	}

}
