package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EngagementsActifrepId generated by hbm2java
 */
@Embeddable
public class EngagementsActifrepId implements java.io.Serializable {

	private String codeengagements;
	private String codeactifrep;

	public EngagementsActifrepId() {
	}

	public EngagementsActifrepId(String codeengagements, String codeactifrep) {
		this.codeengagements = codeengagements;
		this.codeactifrep = codeactifrep;
	}

	@Column(name = "CODEENGAGEMENTS", nullable = false, length = 20)
	public String getCodeengagements() {
		return this.codeengagements;
	}

	public void setCodeengagements(String codeengagements) {
		this.codeengagements = codeengagements;
	}

	@Column(name = "CODEACTIFREP", nullable = false, length = 20)
	public String getCodeactifrep() {
		return this.codeactifrep;
	}

	public void setCodeactifrep(String codeactifrep) {
		this.codeactifrep = codeactifrep;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EngagementsActifrepId))
			return false;
		EngagementsActifrepId castOther = (EngagementsActifrepId) other;

		return ((this.getCodeengagements() == castOther.getCodeengagements()) || (this
				.getCodeengagements() != null
				&& castOther.getCodeengagements() != null && this
				.getCodeengagements().equals(castOther.getCodeengagements())))
				&& ((this.getCodeactifrep() == castOther.getCodeactifrep()) || (this
						.getCodeactifrep() != null
						&& castOther.getCodeactifrep() != null && this
						.getCodeactifrep().equals(castOther.getCodeactifrep())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodeengagements() == null ? 0 : this.getCodeengagements()
						.hashCode());
		result = 37
				* result
				+ (getCodeactifrep() == null ? 0 : this.getCodeactifrep()
						.hashCode());
		return result;
	}

}
