package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etatc10bCategorie generated by hbm2java
 */
@Entity
@Table(name = "etatc10b_categorie", catalog = "zeusbd")
public class Etatc10bCategorie implements java.io.Serializable {

	private String codec10bcategorie;
	private CategorieCima categorieCima;
	private Etatc10b etatc10b;
	private String libelleetatc10cate;
	private BigDecimal primesacquisesexoA;
	private BigDecimal primesacquisesexoB;
	private BigDecimal primesacquisesexoBbis;
	private BigDecimal primesacquisesexoC;
	private BigDecimal primesacquisesexoD;
	private BigDecimal primesacquisesexoE;
	private Integer nbrcontrats31decpres;
	private Integer nbrcontrats31des;
	private Set<C10Exercice> c10Exercices = new HashSet<C10Exercice>(0);

	public Etatc10bCategorie() {
	}

	public Etatc10bCategorie(String codec10bcategorie,
			CategorieCima categorieCima, Etatc10b etatc10b) {
		this.codec10bcategorie = codec10bcategorie;
		this.categorieCima = categorieCima;
		this.etatc10b = etatc10b;
	}

	public Etatc10bCategorie(String codec10bcategorie,
			CategorieCima categorieCima, Etatc10b etatc10b,
			String libelleetatc10cate, BigDecimal primesacquisesexoA,
			BigDecimal primesacquisesexoB, BigDecimal primesacquisesexoBbis,
			BigDecimal primesacquisesexoC, BigDecimal primesacquisesexoD,
			BigDecimal primesacquisesexoE, Integer nbrcontrats31decpres,
			Integer nbrcontrats31des, Set<C10Exercice> c10Exercices) {
		this.codec10bcategorie = codec10bcategorie;
		this.categorieCima = categorieCima;
		this.etatc10b = etatc10b;
		this.libelleetatc10cate = libelleetatc10cate;
		this.primesacquisesexoA = primesacquisesexoA;
		this.primesacquisesexoB = primesacquisesexoB;
		this.primesacquisesexoBbis = primesacquisesexoBbis;
		this.primesacquisesexoC = primesacquisesexoC;
		this.primesacquisesexoD = primesacquisesexoD;
		this.primesacquisesexoE = primesacquisesexoE;
		this.nbrcontrats31decpres = nbrcontrats31decpres;
		this.nbrcontrats31des = nbrcontrats31des;
		this.c10Exercices = c10Exercices;
	}

	@Id
	@Column(name = "CODEC10BCATEGORIE", unique = true, nullable = false, length = 20)
	public String getCodec10bcategorie() {
		return this.codec10bcategorie;
	}

	public void setCodec10bcategorie(String codec10bcategorie) {
		this.codec10bcategorie = codec10bcategorie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODECATEGORIECIMA", nullable = false)
	public CategorieCima getCategorieCima() {
		return this.categorieCima;
	}

	public void setCategorieCima(CategorieCima categorieCima) {
		this.categorieCima = categorieCima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEETATC10B", nullable = false)
	public Etatc10b getEtatc10b() {
		return this.etatc10b;
	}

	public void setEtatc10b(Etatc10b etatc10b) {
		this.etatc10b = etatc10b;
	}

	@Column(name = "LIBELLEETATC10CATE", length = 100)
	public String getLibelleetatc10cate() {
		return this.libelleetatc10cate;
	}

	public void setLibelleetatc10cate(String libelleetatc10cate) {
		this.libelleetatc10cate = libelleetatc10cate;
	}

	@Column(name = "PRIMESACQUISESEXO_A", precision = 15, scale = 3)
	public BigDecimal getPrimesacquisesexoA() {
		return this.primesacquisesexoA;
	}

	public void setPrimesacquisesexoA(BigDecimal primesacquisesexoA) {
		this.primesacquisesexoA = primesacquisesexoA;
	}

	@Column(name = "PRIMESACQUISESEXO_B", precision = 15, scale = 3)
	public BigDecimal getPrimesacquisesexoB() {
		return this.primesacquisesexoB;
	}

	public void setPrimesacquisesexoB(BigDecimal primesacquisesexoB) {
		this.primesacquisesexoB = primesacquisesexoB;
	}

	@Column(name = "PRIMESACQUISESEXO_BBIS", precision = 15, scale = 3)
	public BigDecimal getPrimesacquisesexoBbis() {
		return this.primesacquisesexoBbis;
	}

	public void setPrimesacquisesexoBbis(BigDecimal primesacquisesexoBbis) {
		this.primesacquisesexoBbis = primesacquisesexoBbis;
	}

	@Column(name = "PRIMESACQUISESEXO_C", precision = 15, scale = 3)
	public BigDecimal getPrimesacquisesexoC() {
		return this.primesacquisesexoC;
	}

	public void setPrimesacquisesexoC(BigDecimal primesacquisesexoC) {
		this.primesacquisesexoC = primesacquisesexoC;
	}

	@Column(name = "PRIMESACQUISESEXO_D", precision = 15, scale = 3)
	public BigDecimal getPrimesacquisesexoD() {
		return this.primesacquisesexoD;
	}

	public void setPrimesacquisesexoD(BigDecimal primesacquisesexoD) {
		this.primesacquisesexoD = primesacquisesexoD;
	}

	@Column(name = "PRIMESACQUISESEXO_E", precision = 15, scale = 3)
	public BigDecimal getPrimesacquisesexoE() {
		return this.primesacquisesexoE;
	}

	public void setPrimesacquisesexoE(BigDecimal primesacquisesexoE) {
		this.primesacquisesexoE = primesacquisesexoE;
	}

	@Column(name = "NBRCONTRATS31DECPRES")
	public Integer getNbrcontrats31decpres() {
		return this.nbrcontrats31decpres;
	}

	public void setNbrcontrats31decpres(Integer nbrcontrats31decpres) {
		this.nbrcontrats31decpres = nbrcontrats31decpres;
	}

	@Column(name = "NBRCONTRATS31DES")
	public Integer getNbrcontrats31des() {
		return this.nbrcontrats31des;
	}

	public void setNbrcontrats31des(Integer nbrcontrats31des) {
		this.nbrcontrats31des = nbrcontrats31des;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatc10bCategorie")
	public Set<C10Exercice> getC10Exercices() {
		return this.c10Exercices;
	}

	public void setC10Exercices(Set<C10Exercice> c10Exercices) {
		this.c10Exercices = c10Exercices;
	}

}
