package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Etatc10aCategorie generated by hbm2java
 */
@Entity
@Table(name = "etatc10a_categorie", catalog = "zeusbd")
public class Etatc10aCategorie implements java.io.Serializable {

	private Etatc10aCategorieId id;
	private CategorieCima categorieCima;
	private Etatc10a etatc10a;
	private BigDecimal primeEmiseAccImpotTaxe;
	private BigDecimal dotProvPrime;
	private BigDecimal primesAcquisesC10a;
	private BigDecimal rgmtEffectueC10a;
	private BigDecimal sinPayerExoEncours;
	private BigDecimal sinPayerExoPrec;
	private BigDecimal recoursEncaisseC10a;
	private BigDecimal chargesSinistreC10a;
	private BigDecimal comissionsC10a;
	private BigDecimal fraisGenC10a;
	private BigDecimal soldeBruteExo;
	private BigDecimal SPaC10a;
	private BigDecimal tauxComC10a;
	private BigDecimal tauxFraisGenC10a;
	private BigDecimal tauxSoldePa;

	public Etatc10aCategorie() {
	}

	public Etatc10aCategorie(Etatc10aCategorieId id,
			CategorieCima categorieCima, Etatc10a etatc10a) {
		this.id = id;
		this.categorieCima = categorieCima;
		this.etatc10a = etatc10a;
	}

	public Etatc10aCategorie(Etatc10aCategorieId id,
			CategorieCima categorieCima, Etatc10a etatc10a,
			BigDecimal primeEmiseAccImpotTaxe, BigDecimal dotProvPrime,
			BigDecimal primesAcquisesC10a, BigDecimal rgmtEffectueC10a,
			BigDecimal sinPayerExoEncours, BigDecimal sinPayerExoPrec,
			BigDecimal recoursEncaisseC10a, BigDecimal chargesSinistreC10a,
			BigDecimal comissionsC10a, BigDecimal fraisGenC10a,
			BigDecimal soldeBruteExo, BigDecimal SPaC10a,
			BigDecimal tauxComC10a, BigDecimal tauxFraisGenC10a,
			BigDecimal tauxSoldePa) {
		this.id = id;
		this.categorieCima = categorieCima;
		this.etatc10a = etatc10a;
		this.primeEmiseAccImpotTaxe = primeEmiseAccImpotTaxe;
		this.dotProvPrime = dotProvPrime;
		this.primesAcquisesC10a = primesAcquisesC10a;
		this.rgmtEffectueC10a = rgmtEffectueC10a;
		this.sinPayerExoEncours = sinPayerExoEncours;
		this.sinPayerExoPrec = sinPayerExoPrec;
		this.recoursEncaisseC10a = recoursEncaisseC10a;
		this.chargesSinistreC10a = chargesSinistreC10a;
		this.comissionsC10a = comissionsC10a;
		this.fraisGenC10a = fraisGenC10a;
		this.soldeBruteExo = soldeBruteExo;
		this.SPaC10a = SPaC10a;
		this.tauxComC10a = tauxComC10a;
		this.tauxFraisGenC10a = tauxFraisGenC10a;
		this.tauxSoldePa = tauxSoldePa;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codecategoriecima", column = @Column(name = "CODECATEGORIECIMA", nullable = false, length = 20)),
			@AttributeOverride(name = "codeEtatc10a", column = @Column(name = "CODE_ETATC10A", nullable = false, length = 20)) })
	public Etatc10aCategorieId getId() {
		return this.id;
	}

	public void setId(Etatc10aCategorieId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODECATEGORIECIMA", nullable = false, insertable = false, updatable = false)
	public CategorieCima getCategorieCima() {
		return this.categorieCima;
	}

	public void setCategorieCima(CategorieCima categorieCima) {
		this.categorieCima = categorieCima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETATC10A", nullable = false, insertable = false, updatable = false)
	public Etatc10a getEtatc10a() {
		return this.etatc10a;
	}

	public void setEtatc10a(Etatc10a etatc10a) {
		this.etatc10a = etatc10a;
	}

	@Column(name = "PRIME_EMISE_ACC_IMPOT_TAXE", precision = 15, scale = 3)
	public BigDecimal getPrimeEmiseAccImpotTaxe() {
		return this.primeEmiseAccImpotTaxe;
	}

	public void setPrimeEmiseAccImpotTaxe(BigDecimal primeEmiseAccImpotTaxe) {
		this.primeEmiseAccImpotTaxe = primeEmiseAccImpotTaxe;
	}

	@Column(name = "DOT_PROV_PRIME", precision = 15, scale = 3)
	public BigDecimal getDotProvPrime() {
		return this.dotProvPrime;
	}

	public void setDotProvPrime(BigDecimal dotProvPrime) {
		this.dotProvPrime = dotProvPrime;
	}

	@Column(name = "PRIMES_ACQUISES_C10A", precision = 15, scale = 3)
	public BigDecimal getPrimesAcquisesC10a() {
		return this.primesAcquisesC10a;
	}

	public void setPrimesAcquisesC10a(BigDecimal primesAcquisesC10a) {
		this.primesAcquisesC10a = primesAcquisesC10a;
	}

	@Column(name = "RGMT_EFFECTUE_C10A", precision = 15, scale = 3)
	public BigDecimal getRgmtEffectueC10a() {
		return this.rgmtEffectueC10a;
	}

	public void setRgmtEffectueC10a(BigDecimal rgmtEffectueC10a) {
		this.rgmtEffectueC10a = rgmtEffectueC10a;
	}

	@Column(name = "SIN_PAYER_EXO_ENCOURS", precision = 15, scale = 3)
	public BigDecimal getSinPayerExoEncours() {
		return this.sinPayerExoEncours;
	}

	public void setSinPayerExoEncours(BigDecimal sinPayerExoEncours) {
		this.sinPayerExoEncours = sinPayerExoEncours;
	}

	@Column(name = "SIN_PAYER_EXO_PREC", precision = 15, scale = 3)
	public BigDecimal getSinPayerExoPrec() {
		return this.sinPayerExoPrec;
	}

	public void setSinPayerExoPrec(BigDecimal sinPayerExoPrec) {
		this.sinPayerExoPrec = sinPayerExoPrec;
	}

	@Column(name = "RECOURS_ENCAISSE_C10A", precision = 15, scale = 3)
	public BigDecimal getRecoursEncaisseC10a() {
		return this.recoursEncaisseC10a;
	}

	public void setRecoursEncaisseC10a(BigDecimal recoursEncaisseC10a) {
		this.recoursEncaisseC10a = recoursEncaisseC10a;
	}

	@Column(name = "CHARGES_SINISTRE_C10A", precision = 15, scale = 3)
	public BigDecimal getChargesSinistreC10a() {
		return this.chargesSinistreC10a;
	}

	public void setChargesSinistreC10a(BigDecimal chargesSinistreC10a) {
		this.chargesSinistreC10a = chargesSinistreC10a;
	}

	@Column(name = "COMISSIONS_C10A", precision = 15, scale = 3)
	public BigDecimal getComissionsC10a() {
		return this.comissionsC10a;
	}

	public void setComissionsC10a(BigDecimal comissionsC10a) {
		this.comissionsC10a = comissionsC10a;
	}

	@Column(name = "FRAIS_GEN_C10A", precision = 15, scale = 3)
	public BigDecimal getFraisGenC10a() {
		return this.fraisGenC10a;
	}

	public void setFraisGenC10a(BigDecimal fraisGenC10a) {
		this.fraisGenC10a = fraisGenC10a;
	}

	@Column(name = "SOLDE_BRUTE_EXO", precision = 15, scale = 3)
	public BigDecimal getSoldeBruteExo() {
		return this.soldeBruteExo;
	}

	public void setSoldeBruteExo(BigDecimal soldeBruteExo) {
		this.soldeBruteExo = soldeBruteExo;
	}

	@Column(name = "S_PA_C10A", precision = 15, scale = 3)
	public BigDecimal getSPaC10a() {
		return this.SPaC10a;
	}

	public void setSPaC10a(BigDecimal SPaC10a) {
		this.SPaC10a = SPaC10a;
	}

	@Column(name = "TAUX_COM_C10A", precision = 15, scale = 3)
	public BigDecimal getTauxComC10a() {
		return this.tauxComC10a;
	}

	public void setTauxComC10a(BigDecimal tauxComC10a) {
		this.tauxComC10a = tauxComC10a;
	}

	@Column(name = "TAUX_FRAIS_GEN_C10A", precision = 15, scale = 3)
	public BigDecimal getTauxFraisGenC10a() {
		return this.tauxFraisGenC10a;
	}

	public void setTauxFraisGenC10a(BigDecimal tauxFraisGenC10a) {
		this.tauxFraisGenC10a = tauxFraisGenC10a;
	}

	@Column(name = "TAUX_SOLDE_PA", precision = 15, scale = 3)
	public BigDecimal getTauxSoldePa() {
		return this.tauxSoldePa;
	}

	public void setTauxSoldePa(BigDecimal tauxSoldePa) {
		this.tauxSoldePa = tauxSoldePa;
	}

}
