package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Etatc9 generated by hbm2java
 */
@Entity
@Table(name = "etatc9", catalog = "zeusbd")
public class Etatc9 implements java.io.Serializable {

	private String codeetatc9;
	private EtatCima etatCima;
	private Date dateetatc9;
	private Set<Etatc9Categorie> etatc9Categories = new HashSet<Etatc9Categorie>(
			0);

	public Etatc9() {
	}

	public Etatc9(String codeetatc9) {
		this.codeetatc9 = codeetatc9;
	}

	public Etatc9(String codeetatc9, EtatCima etatCima, Date dateetatc9,
			Set<Etatc9Categorie> etatc9Categories) {
		this.codeetatc9 = codeetatc9;
		this.etatCima = etatCima;
		this.dateetatc9 = dateetatc9;
		this.etatc9Categories = etatc9Categories;
	}

	@Id
	@Column(name = "CODEETATC9", unique = true, nullable = false, length = 20)
	public String getCodeetatc9() {
		return this.codeetatc9;
	}

	public void setCodeetatc9(String codeetatc9) {
		this.codeetatc9 = codeetatc9;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETAT_CIMA")
	public EtatCima getEtatCima() {
		return this.etatCima;
	}

	public void setEtatCima(EtatCima etatCima) {
		this.etatCima = etatCima;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEETATC9", length = 10)
	public Date getDateetatc9() {
		return this.dateetatc9;
	}

	public void setDateetatc9(Date dateetatc9) {
		this.dateetatc9 = dateetatc9;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatc9")
	public Set<Etatc9Categorie> getEtatc9Categories() {
		return this.etatc9Categories;
	}

	public void setEtatc9Categories(Set<Etatc9Categorie> etatc9Categories) {
		this.etatc9Categories = etatc9Categories;
	}

}
