package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EtatC5 generated by hbm2java
 */
@Entity
@Table(name = "etat_c5", catalog = "zeusbd")
public class EtatC5 implements java.io.Serializable {

	private String codeEtatc5;
	private EtatCima etatCima;
	private String libelleEtatc5;
	private BigDecimal soutotalvaleurArticle;
	private BigDecimal soutotalvaleurPar;
	private BigDecimal soutotalvaleurRealisation;
	private BigDecimal soutotalCouverture;
	private BigDecimal soutotalOrganisme1;
	private BigDecimal soutotalOrganisme2;
	private BigDecimal soutotalOrganisme3;
	private BigDecimal soutotalOrganisme4;
	private BigDecimal soustotalFinanciere1;
	private BigDecimal soustotalFinanciere2;
	private BigDecimal soustotalFinanciere3;
	private BigDecimal soustotalFinanciere4;
	private BigDecimal soutotalAutreobligation1;
	private BigDecimal soutotalAutreobligation2;
	private BigDecimal soutotalAutreobligation3;
	private BigDecimal soutotalAutreobligation4;
	private BigDecimal soutotalAction1;
	private BigDecimal soutotalAction2;
	private BigDecimal soutotalAction3;
	private BigDecimal soutotalAction4;
	private BigDecimal soutotalAssurance1;
	private BigDecimal soutotalAssurance2;
	private BigDecimal soutotalAssurance3;
	private BigDecimal soutotalAssurance4;
	private BigDecimal soutotalCommercial1;
	private BigDecimal soutotalCommercial2;
	private BigDecimal soutotalCommercial3;
	private BigDecimal soutotalCommercial4;
	private BigDecimal soutotalInvestissement1;
	private BigDecimal soutotalInvestissement2;
	private BigDecimal soutotalInvestissement3;
	private BigDecimal soutotalInvestissement4;
	private BigDecimal soutotalImobilier1;
	private BigDecimal soutotalImobilier2;
	private BigDecimal soutotalImobilier3;
	private BigDecimal soutotalImobilier4;
	private BigDecimal soutotalGarantie1;
	private BigDecimal soutotalGarantie2;
	private BigDecimal soutotalGarantie3;
	private BigDecimal soutotalGarantie4;
	private BigDecimal soutotalHypo1;
	private BigDecimal soutotalHypo2;
	private BigDecimal soutotalHypo3;
	private BigDecimal soutotalHypo4;
	private BigDecimal soutotalAutrepret1;
	private BigDecimal soutotalAutrepret2;
	private BigDecimal soutotalAutrepret3;
	private BigDecimal soutotalAutrepret4;
	private BigDecimal soutotalDepotbanq1;
	private BigDecimal soutotalDepotbanq2;
	private BigDecimal soutotalDepotbanq3;
	private BigDecimal soutotalDepotbanq4;
	private BigDecimal totalvaleur1;
	private BigDecimal totalvaleur2;
	private BigDecimal totalvaleur3;
	private BigDecimal totalvaleur4;
	private Date dateEtatc5;

	public EtatC5() {
	}

	public EtatC5(String codeEtatc5) {
		this.codeEtatc5 = codeEtatc5;
	}

	public EtatC5(String codeEtatc5, EtatCima etatCima, String libelleEtatc5,
			BigDecimal soutotalvaleurArticle, BigDecimal soutotalvaleurPar,
			BigDecimal soutotalvaleurRealisation,
			BigDecimal soutotalCouverture, BigDecimal soutotalOrganisme1,
			BigDecimal soutotalOrganisme2, BigDecimal soutotalOrganisme3,
			BigDecimal soutotalOrganisme4, BigDecimal soustotalFinanciere1,
			BigDecimal soustotalFinanciere2, BigDecimal soustotalFinanciere3,
			BigDecimal soustotalFinanciere4,
			BigDecimal soutotalAutreobligation1,
			BigDecimal soutotalAutreobligation2,
			BigDecimal soutotalAutreobligation3,
			BigDecimal soutotalAutreobligation4, BigDecimal soutotalAction1,
			BigDecimal soutotalAction2, BigDecimal soutotalAction3,
			BigDecimal soutotalAction4, BigDecimal soutotalAssurance1,
			BigDecimal soutotalAssurance2, BigDecimal soutotalAssurance3,
			BigDecimal soutotalAssurance4, BigDecimal soutotalCommercial1,
			BigDecimal soutotalCommercial2, BigDecimal soutotalCommercial3,
			BigDecimal soutotalCommercial4, BigDecimal soutotalInvestissement1,
			BigDecimal soutotalInvestissement2,
			BigDecimal soutotalInvestissement3,
			BigDecimal soutotalInvestissement4, BigDecimal soutotalImobilier1,
			BigDecimal soutotalImobilier2, BigDecimal soutotalImobilier3,
			BigDecimal soutotalImobilier4, BigDecimal soutotalGarantie1,
			BigDecimal soutotalGarantie2, BigDecimal soutotalGarantie3,
			BigDecimal soutotalGarantie4, BigDecimal soutotalHypo1,
			BigDecimal soutotalHypo2, BigDecimal soutotalHypo3,
			BigDecimal soutotalHypo4, BigDecimal soutotalAutrepret1,
			BigDecimal soutotalAutrepret2, BigDecimal soutotalAutrepret3,
			BigDecimal soutotalAutrepret4, BigDecimal soutotalDepotbanq1,
			BigDecimal soutotalDepotbanq2, BigDecimal soutotalDepotbanq3,
			BigDecimal soutotalDepotbanq4, BigDecimal totalvaleur1,
			BigDecimal totalvaleur2, BigDecimal totalvaleur3,
			BigDecimal totalvaleur4, Date dateEtatc5) {
		this.codeEtatc5 = codeEtatc5;
		this.etatCima = etatCima;
		this.libelleEtatc5 = libelleEtatc5;
		this.soutotalvaleurArticle = soutotalvaleurArticle;
		this.soutotalvaleurPar = soutotalvaleurPar;
		this.soutotalvaleurRealisation = soutotalvaleurRealisation;
		this.soutotalCouverture = soutotalCouverture;
		this.soutotalOrganisme1 = soutotalOrganisme1;
		this.soutotalOrganisme2 = soutotalOrganisme2;
		this.soutotalOrganisme3 = soutotalOrganisme3;
		this.soutotalOrganisme4 = soutotalOrganisme4;
		this.soustotalFinanciere1 = soustotalFinanciere1;
		this.soustotalFinanciere2 = soustotalFinanciere2;
		this.soustotalFinanciere3 = soustotalFinanciere3;
		this.soustotalFinanciere4 = soustotalFinanciere4;
		this.soutotalAutreobligation1 = soutotalAutreobligation1;
		this.soutotalAutreobligation2 = soutotalAutreobligation2;
		this.soutotalAutreobligation3 = soutotalAutreobligation3;
		this.soutotalAutreobligation4 = soutotalAutreobligation4;
		this.soutotalAction1 = soutotalAction1;
		this.soutotalAction2 = soutotalAction2;
		this.soutotalAction3 = soutotalAction3;
		this.soutotalAction4 = soutotalAction4;
		this.soutotalAssurance1 = soutotalAssurance1;
		this.soutotalAssurance2 = soutotalAssurance2;
		this.soutotalAssurance3 = soutotalAssurance3;
		this.soutotalAssurance4 = soutotalAssurance4;
		this.soutotalCommercial1 = soutotalCommercial1;
		this.soutotalCommercial2 = soutotalCommercial2;
		this.soutotalCommercial3 = soutotalCommercial3;
		this.soutotalCommercial4 = soutotalCommercial4;
		this.soutotalInvestissement1 = soutotalInvestissement1;
		this.soutotalInvestissement2 = soutotalInvestissement2;
		this.soutotalInvestissement3 = soutotalInvestissement3;
		this.soutotalInvestissement4 = soutotalInvestissement4;
		this.soutotalImobilier1 = soutotalImobilier1;
		this.soutotalImobilier2 = soutotalImobilier2;
		this.soutotalImobilier3 = soutotalImobilier3;
		this.soutotalImobilier4 = soutotalImobilier4;
		this.soutotalGarantie1 = soutotalGarantie1;
		this.soutotalGarantie2 = soutotalGarantie2;
		this.soutotalGarantie3 = soutotalGarantie3;
		this.soutotalGarantie4 = soutotalGarantie4;
		this.soutotalHypo1 = soutotalHypo1;
		this.soutotalHypo2 = soutotalHypo2;
		this.soutotalHypo3 = soutotalHypo3;
		this.soutotalHypo4 = soutotalHypo4;
		this.soutotalAutrepret1 = soutotalAutrepret1;
		this.soutotalAutrepret2 = soutotalAutrepret2;
		this.soutotalAutrepret3 = soutotalAutrepret3;
		this.soutotalAutrepret4 = soutotalAutrepret4;
		this.soutotalDepotbanq1 = soutotalDepotbanq1;
		this.soutotalDepotbanq2 = soutotalDepotbanq2;
		this.soutotalDepotbanq3 = soutotalDepotbanq3;
		this.soutotalDepotbanq4 = soutotalDepotbanq4;
		this.totalvaleur1 = totalvaleur1;
		this.totalvaleur2 = totalvaleur2;
		this.totalvaleur3 = totalvaleur3;
		this.totalvaleur4 = totalvaleur4;
		this.dateEtatc5 = dateEtatc5;
	}

	@Id
	@Column(name = "CODE_ETATC5", unique = true, nullable = false, length = 20)
	public String getCodeEtatc5() {
		return this.codeEtatc5;
	}

	public void setCodeEtatc5(String codeEtatc5) {
		this.codeEtatc5 = codeEtatc5;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETAT_CIMA")
	public EtatCima getEtatCima() {
		return this.etatCima;
	}

	public void setEtatCima(EtatCima etatCima) {
		this.etatCima = etatCima;
	}

	@Column(name = "LIBELLE_ETATC5", length = 100)
	public String getLibelleEtatc5() {
		return this.libelleEtatc5;
	}

	public void setLibelleEtatc5(String libelleEtatc5) {
		this.libelleEtatc5 = libelleEtatc5;
	}

	@Column(name = "SOUTOTALVALEUR_ARTICLE", precision = 15, scale = 3)
	public BigDecimal getSoutotalvaleurArticle() {
		return this.soutotalvaleurArticle;
	}

	public void setSoutotalvaleurArticle(BigDecimal soutotalvaleurArticle) {
		this.soutotalvaleurArticle = soutotalvaleurArticle;
	}

	@Column(name = "SOUTOTALVALEUR_PAR", precision = 15, scale = 3)
	public BigDecimal getSoutotalvaleurPar() {
		return this.soutotalvaleurPar;
	}

	public void setSoutotalvaleurPar(BigDecimal soutotalvaleurPar) {
		this.soutotalvaleurPar = soutotalvaleurPar;
	}

	@Column(name = "SOUTOTALVALEUR_REALISATION", precision = 15, scale = 3)
	public BigDecimal getSoutotalvaleurRealisation() {
		return this.soutotalvaleurRealisation;
	}

	public void setSoutotalvaleurRealisation(
			BigDecimal soutotalvaleurRealisation) {
		this.soutotalvaleurRealisation = soutotalvaleurRealisation;
	}

	@Column(name = "SOUTOTAL_COUVERTURE", precision = 15, scale = 3)
	public BigDecimal getSoutotalCouverture() {
		return this.soutotalCouverture;
	}

	public void setSoutotalCouverture(BigDecimal soutotalCouverture) {
		this.soutotalCouverture = soutotalCouverture;
	}

	@Column(name = "SOUTOTAL_ORGANISME1", precision = 15, scale = 3)
	public BigDecimal getSoutotalOrganisme1() {
		return this.soutotalOrganisme1;
	}

	public void setSoutotalOrganisme1(BigDecimal soutotalOrganisme1) {
		this.soutotalOrganisme1 = soutotalOrganisme1;
	}

	@Column(name = "SOUTOTAL_ORGANISME2", precision = 15, scale = 3)
	public BigDecimal getSoutotalOrganisme2() {
		return this.soutotalOrganisme2;
	}

	public void setSoutotalOrganisme2(BigDecimal soutotalOrganisme2) {
		this.soutotalOrganisme2 = soutotalOrganisme2;
	}

	@Column(name = "SOUTOTAL_ORGANISME3", precision = 15, scale = 3)
	public BigDecimal getSoutotalOrganisme3() {
		return this.soutotalOrganisme3;
	}

	public void setSoutotalOrganisme3(BigDecimal soutotalOrganisme3) {
		this.soutotalOrganisme3 = soutotalOrganisme3;
	}

	@Column(name = "SOUTOTAL_ORGANISME4", precision = 15, scale = 3)
	public BigDecimal getSoutotalOrganisme4() {
		return this.soutotalOrganisme4;
	}

	public void setSoutotalOrganisme4(BigDecimal soutotalOrganisme4) {
		this.soutotalOrganisme4 = soutotalOrganisme4;
	}

	@Column(name = "SOUSTOTAL_FINANCIERE1", precision = 15, scale = 3)
	public BigDecimal getSoustotalFinanciere1() {
		return this.soustotalFinanciere1;
	}

	public void setSoustotalFinanciere1(BigDecimal soustotalFinanciere1) {
		this.soustotalFinanciere1 = soustotalFinanciere1;
	}

	@Column(name = "SOUSTOTAL_FINANCIERE2", precision = 15, scale = 3)
	public BigDecimal getSoustotalFinanciere2() {
		return this.soustotalFinanciere2;
	}

	public void setSoustotalFinanciere2(BigDecimal soustotalFinanciere2) {
		this.soustotalFinanciere2 = soustotalFinanciere2;
	}

	@Column(name = "SOUSTOTAL_FINANCIERE3", precision = 15, scale = 3)
	public BigDecimal getSoustotalFinanciere3() {
		return this.soustotalFinanciere3;
	}

	public void setSoustotalFinanciere3(BigDecimal soustotalFinanciere3) {
		this.soustotalFinanciere3 = soustotalFinanciere3;
	}

	@Column(name = "SOUSTOTAL_FINANCIERE4", precision = 15, scale = 3)
	public BigDecimal getSoustotalFinanciere4() {
		return this.soustotalFinanciere4;
	}

	public void setSoustotalFinanciere4(BigDecimal soustotalFinanciere4) {
		this.soustotalFinanciere4 = soustotalFinanciere4;
	}

	@Column(name = "SOUTOTAL_AUTREOBLIGATION1", precision = 15, scale = 3)
	public BigDecimal getSoutotalAutreobligation1() {
		return this.soutotalAutreobligation1;
	}

	public void setSoutotalAutreobligation1(BigDecimal soutotalAutreobligation1) {
		this.soutotalAutreobligation1 = soutotalAutreobligation1;
	}

	@Column(name = "SOUTOTAL_AUTREOBLIGATION2", precision = 15, scale = 3)
	public BigDecimal getSoutotalAutreobligation2() {
		return this.soutotalAutreobligation2;
	}

	public void setSoutotalAutreobligation2(BigDecimal soutotalAutreobligation2) {
		this.soutotalAutreobligation2 = soutotalAutreobligation2;
	}

	@Column(name = "SOUTOTAL_AUTREOBLIGATION3", precision = 15, scale = 3)
	public BigDecimal getSoutotalAutreobligation3() {
		return this.soutotalAutreobligation3;
	}

	public void setSoutotalAutreobligation3(BigDecimal soutotalAutreobligation3) {
		this.soutotalAutreobligation3 = soutotalAutreobligation3;
	}

	@Column(name = "SOUTOTAL_AUTREOBLIGATION4", precision = 15, scale = 3)
	public BigDecimal getSoutotalAutreobligation4() {
		return this.soutotalAutreobligation4;
	}

	public void setSoutotalAutreobligation4(BigDecimal soutotalAutreobligation4) {
		this.soutotalAutreobligation4 = soutotalAutreobligation4;
	}

	@Column(name = "SOUTOTAL_ACTION1", precision = 15, scale = 3)
	public BigDecimal getSoutotalAction1() {
		return this.soutotalAction1;
	}

	public void setSoutotalAction1(BigDecimal soutotalAction1) {
		this.soutotalAction1 = soutotalAction1;
	}

	@Column(name = "SOUTOTAL_ACTION2", precision = 15, scale = 3)
	public BigDecimal getSoutotalAction2() {
		return this.soutotalAction2;
	}

	public void setSoutotalAction2(BigDecimal soutotalAction2) {
		this.soutotalAction2 = soutotalAction2;
	}

	@Column(name = "SOUTOTAL_ACTION3", precision = 15, scale = 3)
	public BigDecimal getSoutotalAction3() {
		return this.soutotalAction3;
	}

	public void setSoutotalAction3(BigDecimal soutotalAction3) {
		this.soutotalAction3 = soutotalAction3;
	}

	@Column(name = "SOUTOTAL_ACTION4", precision = 15, scale = 3)
	public BigDecimal getSoutotalAction4() {
		return this.soutotalAction4;
	}

	public void setSoutotalAction4(BigDecimal soutotalAction4) {
		this.soutotalAction4 = soutotalAction4;
	}

	@Column(name = "SOUTOTAL_ASSURANCE1", precision = 15, scale = 3)
	public BigDecimal getSoutotalAssurance1() {
		return this.soutotalAssurance1;
	}

	public void setSoutotalAssurance1(BigDecimal soutotalAssurance1) {
		this.soutotalAssurance1 = soutotalAssurance1;
	}

	@Column(name = "SOUTOTAL_ASSURANCE2", precision = 15, scale = 3)
	public BigDecimal getSoutotalAssurance2() {
		return this.soutotalAssurance2;
	}

	public void setSoutotalAssurance2(BigDecimal soutotalAssurance2) {
		this.soutotalAssurance2 = soutotalAssurance2;
	}

	@Column(name = "SOUTOTAL_ASSURANCE3", precision = 15, scale = 3)
	public BigDecimal getSoutotalAssurance3() {
		return this.soutotalAssurance3;
	}

	public void setSoutotalAssurance3(BigDecimal soutotalAssurance3) {
		this.soutotalAssurance3 = soutotalAssurance3;
	}

	@Column(name = "SOUTOTAL_ASSURANCE4", precision = 15, scale = 3)
	public BigDecimal getSoutotalAssurance4() {
		return this.soutotalAssurance4;
	}

	public void setSoutotalAssurance4(BigDecimal soutotalAssurance4) {
		this.soutotalAssurance4 = soutotalAssurance4;
	}

	@Column(name = "SOUTOTAL_COMMERCIAL1", precision = 15, scale = 3)
	public BigDecimal getSoutotalCommercial1() {
		return this.soutotalCommercial1;
	}

	public void setSoutotalCommercial1(BigDecimal soutotalCommercial1) {
		this.soutotalCommercial1 = soutotalCommercial1;
	}

	@Column(name = "SOUTOTAL_COMMERCIAL2", precision = 15, scale = 3)
	public BigDecimal getSoutotalCommercial2() {
		return this.soutotalCommercial2;
	}

	public void setSoutotalCommercial2(BigDecimal soutotalCommercial2) {
		this.soutotalCommercial2 = soutotalCommercial2;
	}

	@Column(name = "SOUTOTAL_COMMERCIAL3", precision = 15, scale = 3)
	public BigDecimal getSoutotalCommercial3() {
		return this.soutotalCommercial3;
	}

	public void setSoutotalCommercial3(BigDecimal soutotalCommercial3) {
		this.soutotalCommercial3 = soutotalCommercial3;
	}

	@Column(name = "SOUTOTAL_COMMERCIAL4", precision = 15, scale = 3)
	public BigDecimal getSoutotalCommercial4() {
		return this.soutotalCommercial4;
	}

	public void setSoutotalCommercial4(BigDecimal soutotalCommercial4) {
		this.soutotalCommercial4 = soutotalCommercial4;
	}

	@Column(name = "SOUTOTAL_INVESTISSEMENT1", precision = 15, scale = 3)
	public BigDecimal getSoutotalInvestissement1() {
		return this.soutotalInvestissement1;
	}

	public void setSoutotalInvestissement1(BigDecimal soutotalInvestissement1) {
		this.soutotalInvestissement1 = soutotalInvestissement1;
	}

	@Column(name = "SOUTOTAL_INVESTISSEMENT2", precision = 15, scale = 3)
	public BigDecimal getSoutotalInvestissement2() {
		return this.soutotalInvestissement2;
	}

	public void setSoutotalInvestissement2(BigDecimal soutotalInvestissement2) {
		this.soutotalInvestissement2 = soutotalInvestissement2;
	}

	@Column(name = "SOUTOTAL_INVESTISSEMENT3", precision = 15, scale = 3)
	public BigDecimal getSoutotalInvestissement3() {
		return this.soutotalInvestissement3;
	}

	public void setSoutotalInvestissement3(BigDecimal soutotalInvestissement3) {
		this.soutotalInvestissement3 = soutotalInvestissement3;
	}

	@Column(name = "SOUTOTAL_INVESTISSEMENT4", precision = 15, scale = 3)
	public BigDecimal getSoutotalInvestissement4() {
		return this.soutotalInvestissement4;
	}

	public void setSoutotalInvestissement4(BigDecimal soutotalInvestissement4) {
		this.soutotalInvestissement4 = soutotalInvestissement4;
	}

	@Column(name = "SOUTOTAL_IMOBILIER1", precision = 15, scale = 3)
	public BigDecimal getSoutotalImobilier1() {
		return this.soutotalImobilier1;
	}

	public void setSoutotalImobilier1(BigDecimal soutotalImobilier1) {
		this.soutotalImobilier1 = soutotalImobilier1;
	}

	@Column(name = "SOUTOTAL_IMOBILIER2", precision = 15, scale = 3)
	public BigDecimal getSoutotalImobilier2() {
		return this.soutotalImobilier2;
	}

	public void setSoutotalImobilier2(BigDecimal soutotalImobilier2) {
		this.soutotalImobilier2 = soutotalImobilier2;
	}

	@Column(name = "SOUTOTAL_IMOBILIER3", precision = 15, scale = 3)
	public BigDecimal getSoutotalImobilier3() {
		return this.soutotalImobilier3;
	}

	public void setSoutotalImobilier3(BigDecimal soutotalImobilier3) {
		this.soutotalImobilier3 = soutotalImobilier3;
	}

	@Column(name = "SOUTOTAL_IMOBILIER4", precision = 15, scale = 3)
	public BigDecimal getSoutotalImobilier4() {
		return this.soutotalImobilier4;
	}

	public void setSoutotalImobilier4(BigDecimal soutotalImobilier4) {
		this.soutotalImobilier4 = soutotalImobilier4;
	}

	@Column(name = "SOUTOTAL_GARANTIE1", precision = 15, scale = 3)
	public BigDecimal getSoutotalGarantie1() {
		return this.soutotalGarantie1;
	}

	public void setSoutotalGarantie1(BigDecimal soutotalGarantie1) {
		this.soutotalGarantie1 = soutotalGarantie1;
	}

	@Column(name = "SOUTOTAL_GARANTIE2", precision = 15, scale = 3)
	public BigDecimal getSoutotalGarantie2() {
		return this.soutotalGarantie2;
	}

	public void setSoutotalGarantie2(BigDecimal soutotalGarantie2) {
		this.soutotalGarantie2 = soutotalGarantie2;
	}

	@Column(name = "SOUTOTAL_GARANTIE3", precision = 15, scale = 3)
	public BigDecimal getSoutotalGarantie3() {
		return this.soutotalGarantie3;
	}

	public void setSoutotalGarantie3(BigDecimal soutotalGarantie3) {
		this.soutotalGarantie3 = soutotalGarantie3;
	}

	@Column(name = "SOUTOTAL_GARANTIE4", precision = 15, scale = 3)
	public BigDecimal getSoutotalGarantie4() {
		return this.soutotalGarantie4;
	}

	public void setSoutotalGarantie4(BigDecimal soutotalGarantie4) {
		this.soutotalGarantie4 = soutotalGarantie4;
	}

	@Column(name = "SOUTOTAL_HYPO1", precision = 15, scale = 3)
	public BigDecimal getSoutotalHypo1() {
		return this.soutotalHypo1;
	}

	public void setSoutotalHypo1(BigDecimal soutotalHypo1) {
		this.soutotalHypo1 = soutotalHypo1;
	}

	@Column(name = "SOUTOTAL_HYPO2", precision = 15, scale = 3)
	public BigDecimal getSoutotalHypo2() {
		return this.soutotalHypo2;
	}

	public void setSoutotalHypo2(BigDecimal soutotalHypo2) {
		this.soutotalHypo2 = soutotalHypo2;
	}

	@Column(name = "SOUTOTAL_HYPO3", precision = 15, scale = 3)
	public BigDecimal getSoutotalHypo3() {
		return this.soutotalHypo3;
	}

	public void setSoutotalHypo3(BigDecimal soutotalHypo3) {
		this.soutotalHypo3 = soutotalHypo3;
	}

	@Column(name = "SOUTOTAL_HYPO4", precision = 15, scale = 3)
	public BigDecimal getSoutotalHypo4() {
		return this.soutotalHypo4;
	}

	public void setSoutotalHypo4(BigDecimal soutotalHypo4) {
		this.soutotalHypo4 = soutotalHypo4;
	}

	@Column(name = "SOUTOTAL_AUTREPRET1", precision = 15, scale = 3)
	public BigDecimal getSoutotalAutrepret1() {
		return this.soutotalAutrepret1;
	}

	public void setSoutotalAutrepret1(BigDecimal soutotalAutrepret1) {
		this.soutotalAutrepret1 = soutotalAutrepret1;
	}

	@Column(name = "SOUTOTAL_AUTREPRET2", precision = 15, scale = 3)
	public BigDecimal getSoutotalAutrepret2() {
		return this.soutotalAutrepret2;
	}

	public void setSoutotalAutrepret2(BigDecimal soutotalAutrepret2) {
		this.soutotalAutrepret2 = soutotalAutrepret2;
	}

	@Column(name = "SOUTOTAL_AUTREPRET3", precision = 15, scale = 3)
	public BigDecimal getSoutotalAutrepret3() {
		return this.soutotalAutrepret3;
	}

	public void setSoutotalAutrepret3(BigDecimal soutotalAutrepret3) {
		this.soutotalAutrepret3 = soutotalAutrepret3;
	}

	@Column(name = "SOUTOTAL_AUTREPRET4", precision = 15, scale = 3)
	public BigDecimal getSoutotalAutrepret4() {
		return this.soutotalAutrepret4;
	}

	public void setSoutotalAutrepret4(BigDecimal soutotalAutrepret4) {
		this.soutotalAutrepret4 = soutotalAutrepret4;
	}

	@Column(name = "SOUTOTAL_DEPOTBANQ1", precision = 15, scale = 3)
	public BigDecimal getSoutotalDepotbanq1() {
		return this.soutotalDepotbanq1;
	}

	public void setSoutotalDepotbanq1(BigDecimal soutotalDepotbanq1) {
		this.soutotalDepotbanq1 = soutotalDepotbanq1;
	}

	@Column(name = "SOUTOTAL_DEPOTBANQ2", precision = 15, scale = 3)
	public BigDecimal getSoutotalDepotbanq2() {
		return this.soutotalDepotbanq2;
	}

	public void setSoutotalDepotbanq2(BigDecimal soutotalDepotbanq2) {
		this.soutotalDepotbanq2 = soutotalDepotbanq2;
	}

	@Column(name = "SOUTOTAL_DEPOTBANQ3", precision = 15, scale = 3)
	public BigDecimal getSoutotalDepotbanq3() {
		return this.soutotalDepotbanq3;
	}

	public void setSoutotalDepotbanq3(BigDecimal soutotalDepotbanq3) {
		this.soutotalDepotbanq3 = soutotalDepotbanq3;
	}

	@Column(name = "SOUTOTAL_DEPOTBANQ4", precision = 15, scale = 3)
	public BigDecimal getSoutotalDepotbanq4() {
		return this.soutotalDepotbanq4;
	}

	public void setSoutotalDepotbanq4(BigDecimal soutotalDepotbanq4) {
		this.soutotalDepotbanq4 = soutotalDepotbanq4;
	}

	@Column(name = "TOTALVALEUR1", precision = 15, scale = 3)
	public BigDecimal getTotalvaleur1() {
		return this.totalvaleur1;
	}

	public void setTotalvaleur1(BigDecimal totalvaleur1) {
		this.totalvaleur1 = totalvaleur1;
	}

	@Column(name = "TOTALVALEUR2", precision = 15, scale = 3)
	public BigDecimal getTotalvaleur2() {
		return this.totalvaleur2;
	}

	public void setTotalvaleur2(BigDecimal totalvaleur2) {
		this.totalvaleur2 = totalvaleur2;
	}

	@Column(name = "TOTALVALEUR3", precision = 15, scale = 3)
	public BigDecimal getTotalvaleur3() {
		return this.totalvaleur3;
	}

	public void setTotalvaleur3(BigDecimal totalvaleur3) {
		this.totalvaleur3 = totalvaleur3;
	}

	@Column(name = "TOTALVALEUR4", precision = 15, scale = 3)
	public BigDecimal getTotalvaleur4() {
		return this.totalvaleur4;
	}

	public void setTotalvaleur4(BigDecimal totalvaleur4) {
		this.totalvaleur4 = totalvaleur4;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_ETATC5", length = 19)
	public Date getDateEtatc5() {
		return this.dateEtatc5;
	}

	public void setDateEtatc5(Date dateEtatc5) {
		this.dateEtatc5 = dateEtatc5;
	}

}
