package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Expertise generated by hbm2java
 */
@Entity
@Table(name = "expertise", catalog = "zeusbd")
public class Expertise implements java.io.Serializable {

	private String refExpertise;
	private ExpertSinistre expertSinistre;
	private Facture facture;
	private Sinistre sinistre;
	private String conclusionExpertise;
	private String commentaireExpertise;
	private String typeExpertise;
	private String garantiesConcernees;

	public Expertise() {
	}

	public Expertise(String refExpertise, Sinistre sinistre) {
		this.refExpertise = refExpertise;
		this.sinistre = sinistre;
	}

	public Expertise(String refExpertise, ExpertSinistre expertSinistre,
			Facture facture, Sinistre sinistre, String conclusionExpertise,
			String commentaireExpertise, String typeExpertise,
			String garantiesConcernees) {
		this.refExpertise = refExpertise;
		this.expertSinistre = expertSinistre;
		this.facture = facture;
		this.sinistre = sinistre;
		this.conclusionExpertise = conclusionExpertise;
		this.commentaireExpertise = commentaireExpertise;
		this.typeExpertise = typeExpertise;
		this.garantiesConcernees = garantiesConcernees;
	}

	@Id
	@Column(name = "REF_EXPERTISE", unique = true, nullable = false, length = 16)
	public String getRefExpertise() {
		return this.refExpertise;
	}

	public void setRefExpertise(String refExpertise) {
		this.refExpertise = refExpertise;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_EXPERT_SINISTRE")
	public ExpertSinistre getExpertSinistre() {
		return this.expertSinistre;
	}

	public void setExpertSinistre(ExpertSinistre expertSinistre) {
		this.expertSinistre = expertSinistre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_FACTURE")
	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_SINISTRE", nullable = false)
	public Sinistre getSinistre() {
		return this.sinistre;
	}

	public void setSinistre(Sinistre sinistre) {
		this.sinistre = sinistre;
	}

	@Column(name = "CONCLUSION_EXPERTISE", length = 65535)
	public String getConclusionExpertise() {
		return this.conclusionExpertise;
	}

	public void setConclusionExpertise(String conclusionExpertise) {
		this.conclusionExpertise = conclusionExpertise;
	}

	@Column(name = "COMMENTAIRE_EXPERTISE", length = 65535)
	public String getCommentaireExpertise() {
		return this.commentaireExpertise;
	}

	public void setCommentaireExpertise(String commentaireExpertise) {
		this.commentaireExpertise = commentaireExpertise;
	}

	@Column(name = "TYPE_EXPERTISE", length = 60)
	public String getTypeExpertise() {
		return this.typeExpertise;
	}

	public void setTypeExpertise(String typeExpertise) {
		this.typeExpertise = typeExpertise;
	}

	@Column(name = "GARANTIES_CONCERNEES", length = 100)
	public String getGarantiesConcernees() {
		return this.garantiesConcernees;
	}

	public void setGarantiesConcernees(String garantiesConcernees) {
		this.garantiesConcernees = garantiesConcernees;
	}

}
