package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Feuillebilan generated by hbm2java
 */
@Entity
@Table(name = "feuillebilan", catalog = "zeusbd")
public class Feuillebilan implements java.io.Serializable {

	private String idbilan;
	private EtatCima etatCima;
	private String libelle;
	private Short annee;
	private Set<LgBilanPassif> lgBilanPassifs = new HashSet<LgBilanPassif>(0);
	private Set<LgBilanActif> lgBilanActifs = new HashSet<LgBilanActif>(0);

	public Feuillebilan() {
	}

	public Feuillebilan(String idbilan) {
		this.idbilan = idbilan;
	}

	public Feuillebilan(String idbilan, EtatCima etatCima, String libelle,
			Short annee, Set<LgBilanPassif> lgBilanPassifs,
			Set<LgBilanActif> lgBilanActifs) {
		this.idbilan = idbilan;
		this.etatCima = etatCima;
		this.libelle = libelle;
		this.annee = annee;
		this.lgBilanPassifs = lgBilanPassifs;
		this.lgBilanActifs = lgBilanActifs;
	}

	@Id
	@Column(name = "IDBILAN", unique = true, nullable = false, length = 50)
	public String getIdbilan() {
		return this.idbilan;
	}

	public void setIdbilan(String idbilan) {
		this.idbilan = idbilan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETAT_CIMA")
	public EtatCima getEtatCima() {
		return this.etatCima;
	}

	public void setEtatCima(EtatCima etatCima) {
		this.etatCima = etatCima;
	}

	@Column(name = "LIBELLE", length = 75)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "ANNEE")
	public Short getAnnee() {
		return this.annee;
	}

	public void setAnnee(Short annee) {
		this.annee = annee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feuillebilan")
	public Set<LgBilanPassif> getLgBilanPassifs() {
		return this.lgBilanPassifs;
	}

	public void setLgBilanPassifs(Set<LgBilanPassif> lgBilanPassifs) {
		this.lgBilanPassifs = lgBilanPassifs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feuillebilan")
	public Set<LgBilanActif> getLgBilanActifs() {
		return this.lgBilanActifs;
	}

	public void setLgBilanActifs(Set<LgBilanActif> lgBilanActifs) {
		this.lgBilanActifs = lgBilanActifs;
	}

}
