package com.j3a.assurance.model;

// Generated 8 sept. 2015 13:52:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FormuleGarantie generated by hbm2java
 */
@Entity
@Table(name = "formule_garantie", catalog = "zeusbd")
public class FormuleGarantie implements java.io.Serializable {

	private String codeFormuleGarantie;
	private String libelleFormuleGarantie;
	private Set<OptionsGarantie> optionsGaranties = new HashSet<OptionsGarantie>(
			0);

	public FormuleGarantie() {
	}

	public FormuleGarantie(String codeFormuleGarantie) {
		this.codeFormuleGarantie = codeFormuleGarantie;
	}

	public FormuleGarantie(String codeFormuleGarantie,
			String libelleFormuleGarantie, Set<OptionsGarantie> optionsGaranties) {
		this.codeFormuleGarantie = codeFormuleGarantie;
		this.libelleFormuleGarantie = libelleFormuleGarantie;
		this.optionsGaranties = optionsGaranties;
	}
	
	@Id
	@Column(name = "CODE_FORMULE_GARANTIE", unique = true, nullable = false, length = 5)
	public String getCodeFormuleGarantie() {
		return this.codeFormuleGarantie;
	}

	public void setCodeFormuleGarantie(String codeFormuleGarantie) {
		this.codeFormuleGarantie = codeFormuleGarantie;
	}
	
	@Column(name = "LIBELLE_FORMULE_GARANTIE", length = 16)
	public String getLibelleFormuleGarantie() {
		return this.libelleFormuleGarantie;
	}

	public void setLibelleFormuleGarantie(String libelleFormuleGarantie) {
		this.libelleFormuleGarantie = libelleFormuleGarantie;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formuleGarantie")
	public Set<OptionsGarantie> getOptionsGaranties() {
		return this.optionsGaranties;
	}

	public void setOptionsGaranties(Set<OptionsGarantie> optionsGaranties) {
		this.optionsGaranties = optionsGaranties;
	}

}
