package com.j3a.assurance.model;

// Generated 12 août 2015 16:21:18 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GarantieOption generated by hbm2java
 */
@Entity
@Table(name = "garantie_option", catalog = "zeusbd")
public class GarantieOption implements java.io.Serializable {

	private GarantieOptionId id;
	private Garantie garantie;
	private OptionsGarantie optionsGarantie;

	public GarantieOption() {
	}

	public GarantieOption(GarantieOptionId id, Garantie garantie,
			OptionsGarantie optionsGarantie) {
		this.id = id;
		this.garantie = garantie;
		this.optionsGarantie = optionsGarantie;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeGarantie", column = @Column(name = "CODE_GARANTIE", nullable = false, length = 12)),
			@AttributeOverride(name = "codeOptionsGarantie", column = @Column(name = "CODE_OPTIONS_GARANTIE", nullable = false, length = 30)) })
	public GarantieOptionId getId() {
		return this.id;
	}

	public void setId(GarantieOptionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_GARANTIE", nullable = false, insertable = false, updatable = false)
	public Garantie getGarantie() {
		return this.garantie;
	}

	public void setGarantie(Garantie garantie) {
		this.garantie = garantie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_OPTIONS_GARANTIE", nullable = false, insertable = false, updatable = false)
	public OptionsGarantie getOptionsGarantie() {
		return this.optionsGarantie;
	}

	public void setOptionsGarantie(OptionsGarantie optionsGarantie) {
		this.optionsGarantie = optionsGarantie;
	}

}
