package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GarantieGarantieChoisieMrhId generated by hbm2java
 */
@Embeddable
public class GarantieGarantieChoisieMrhId implements java.io.Serializable {

	private String codeGarantie;
	private String codeGarantieChoisiemrh;

	public GarantieGarantieChoisieMrhId() {
	}

	public GarantieGarantieChoisieMrhId(String codeGarantie,
			String codeGarantieChoisiemrh) {
		this.codeGarantie = codeGarantie;
		this.codeGarantieChoisiemrh = codeGarantieChoisiemrh;
	}

	@Column(name = "CODE_GARANTIE", nullable = false, length = 12)
	public String getCodeGarantie() {
		return this.codeGarantie;
	}

	public void setCodeGarantie(String codeGarantie) {
		this.codeGarantie = codeGarantie;
	}

	@Column(name = "CODE_GARANTIE_CHOISIEMRH", nullable = false, length = 35)
	public String getCodeGarantieChoisiemrh() {
		return this.codeGarantieChoisiemrh;
	}

	public void setCodeGarantieChoisiemrh(String codeGarantieChoisiemrh) {
		this.codeGarantieChoisiemrh = codeGarantieChoisiemrh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GarantieGarantieChoisieMrhId))
			return false;
		GarantieGarantieChoisieMrhId castOther = (GarantieGarantieChoisieMrhId) other;

		return ((this.getCodeGarantie() == castOther.getCodeGarantie()) || (this
				.getCodeGarantie() != null
				&& castOther.getCodeGarantie() != null && this
				.getCodeGarantie().equals(castOther.getCodeGarantie())))
				&& ((this.getCodeGarantieChoisiemrh() == castOther
						.getCodeGarantieChoisiemrh()) || (this
						.getCodeGarantieChoisiemrh() != null
						&& castOther.getCodeGarantieChoisiemrh() != null && this
						.getCodeGarantieChoisiemrh().equals(
								castOther.getCodeGarantieChoisiemrh())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodeGarantie() == null ? 0 : this.getCodeGarantie()
						.hashCode());
		result = 37
				* result
				+ (getCodeGarantieChoisiemrh() == null ? 0 : this
						.getCodeGarantieChoisiemrh().hashCode());
		return result;
	}

}
