package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GarantieGarantieChoisieSante generated by hbm2java
 */
@Entity
@Table(name = "garantie_garantie_choisie_sante", catalog = "zeusbd")
public class GarantieGarantieChoisieSante implements java.io.Serializable {

	private GarantieGarantieChoisieSanteId id;
	private Garantie garantie;
	private GarantieChoisieSante garantieChoisieSante;
	private BigDecimal primeNetteSante;
	private BigDecimal reductionSante;
	private BigDecimal tauxPrimeSante;
	private BigDecimal tauxRedSante;
	private BigDecimal tauxGesSante;
	private BigDecimal tauxComSante;
	private BigDecimal tauxintermSante;
	private BigDecimal tauxConsSante;
	private Date dateGarantieGarantieChoisieSante;
	private BigDecimal capitalSante;
	private Integer delaiCarence;
	private String observationSante;
	private BigDecimal tauxFacteurMajoration;
	private BigDecimal surprimeFacteurMajoration;
	private String observationFacteurMajoration;

	public GarantieGarantieChoisieSante() {
	}

	public GarantieGarantieChoisieSante(GarantieGarantieChoisieSanteId id,
			Garantie garantie, GarantieChoisieSante garantieChoisieSante) {
		this.id = id;
		this.garantie = garantie;
		this.garantieChoisieSante = garantieChoisieSante;
	}

	public GarantieGarantieChoisieSante(GarantieGarantieChoisieSanteId id,
			Garantie garantie, GarantieChoisieSante garantieChoisieSante,
			BigDecimal primeNetteSante, BigDecimal reductionSante,
			BigDecimal tauxPrimeSante, BigDecimal tauxRedSante,
			BigDecimal tauxGesSante, BigDecimal tauxComSante,
			BigDecimal tauxintermSante, BigDecimal tauxConsSante,
			Date dateGarantieGarantieChoisieSante, BigDecimal capitalSante,
			Integer delaiCarence, String observationSante,
			BigDecimal tauxFacteurMajoration,
			BigDecimal surprimeFacteurMajoration,
			String observationFacteurMajoration) {
		this.id = id;
		this.garantie = garantie;
		this.garantieChoisieSante = garantieChoisieSante;
		this.primeNetteSante = primeNetteSante;
		this.reductionSante = reductionSante;
		this.tauxPrimeSante = tauxPrimeSante;
		this.tauxRedSante = tauxRedSante;
		this.tauxGesSante = tauxGesSante;
		this.tauxComSante = tauxComSante;
		this.tauxintermSante = tauxintermSante;
		this.tauxConsSante = tauxConsSante;
		this.dateGarantieGarantieChoisieSante = dateGarantieGarantieChoisieSante;
		this.capitalSante = capitalSante;
		this.delaiCarence = delaiCarence;
		this.observationSante = observationSante;
		this.tauxFacteurMajoration = tauxFacteurMajoration;
		this.surprimeFacteurMajoration = surprimeFacteurMajoration;
		this.observationFacteurMajoration = observationFacteurMajoration;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeGarantie", column = @Column(name = "CODE_GARANTIE", nullable = false, length = 12)),
			@AttributeOverride(name = "codeGarantieChoisiesante", column = @Column(name = "CODE_GARANTIE_CHOISIESANTE", nullable = false, length = 35)) })
	public GarantieGarantieChoisieSanteId getId() {
		return this.id;
	}

	public void setId(GarantieGarantieChoisieSanteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_GARANTIE", nullable = false, insertable = false, updatable = false)
	public Garantie getGarantie() {
		return this.garantie;
	}

	public void setGarantie(Garantie garantie) {
		this.garantie = garantie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_GARANTIE_CHOISIESANTE", nullable = false, insertable = false, updatable = false)
	public GarantieChoisieSante getGarantieChoisieSante() {
		return this.garantieChoisieSante;
	}

	public void setGarantieChoisieSante(
			GarantieChoisieSante garantieChoisieSante) {
		this.garantieChoisieSante = garantieChoisieSante;
	}

	@Column(name = "PRIME_NETTE_SANTE", precision = 15, scale = 3)
	public BigDecimal getPrimeNetteSante() {
		return this.primeNetteSante;
	}

	public void setPrimeNetteSante(BigDecimal primeNetteSante) {
		this.primeNetteSante = primeNetteSante;
	}

	@Column(name = "REDUCTION_SANTE", precision = 15, scale = 3)
	public BigDecimal getReductionSante() {
		return this.reductionSante;
	}

	public void setReductionSante(BigDecimal reductionSante) {
		this.reductionSante = reductionSante;
	}

	@Column(name = "TAUX_PRIME_SANTE", precision = 6, scale = 4)
	public BigDecimal getTauxPrimeSante() {
		return this.tauxPrimeSante;
	}

	public void setTauxPrimeSante(BigDecimal tauxPrimeSante) {
		this.tauxPrimeSante = tauxPrimeSante;
	}

	@Column(name = "TAUX_RED_SANTE", precision = 6, scale = 4)
	public BigDecimal getTauxRedSante() {
		return this.tauxRedSante;
	}

	public void setTauxRedSante(BigDecimal tauxRedSante) {
		this.tauxRedSante = tauxRedSante;
	}

	@Column(name = "TAUX_GES_SANTE", precision = 6, scale = 4)
	public BigDecimal getTauxGesSante() {
		return this.tauxGesSante;
	}

	public void setTauxGesSante(BigDecimal tauxGesSante) {
		this.tauxGesSante = tauxGesSante;
	}

	@Column(name = "TAUX_COM_SANTE", precision = 6, scale = 4)
	public BigDecimal getTauxComSante() {
		return this.tauxComSante;
	}

	public void setTauxComSante(BigDecimal tauxComSante) {
		this.tauxComSante = tauxComSante;
	}

	@Column(name = "TAUXINTERM_SANTE", precision = 6, scale = 4)
	public BigDecimal getTauxintermSante() {
		return this.tauxintermSante;
	}

	public void setTauxintermSante(BigDecimal tauxintermSante) {
		this.tauxintermSante = tauxintermSante;
	}

	@Column(name = "TAUX_CONS_SANTE", precision = 6, scale = 4)
	public BigDecimal getTauxConsSante() {
		return this.tauxConsSante;
	}

	public void setTauxConsSante(BigDecimal tauxConsSante) {
		this.tauxConsSante = tauxConsSante;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_GARANTIE_GARANTIE_CHOISIE_SANTE", length = 10)
	public Date getDateGarantieGarantieChoisieSante() {
		return this.dateGarantieGarantieChoisieSante;
	}

	public void setDateGarantieGarantieChoisieSante(
			Date dateGarantieGarantieChoisieSante) {
		this.dateGarantieGarantieChoisieSante = dateGarantieGarantieChoisieSante;
	}

	@Column(name = "CAPITAL_SANTE", precision = 15, scale = 3)
	public BigDecimal getCapitalSante() {
		return this.capitalSante;
	}

	public void setCapitalSante(BigDecimal capitalSante) {
		this.capitalSante = capitalSante;
	}

	@Column(name = "DELAI_CARENCE")
	public Integer getDelaiCarence() {
		return this.delaiCarence;
	}

	public void setDelaiCarence(Integer delaiCarence) {
		this.delaiCarence = delaiCarence;
	}

	@Column(name = "OBSERVATION_SANTE", length = 50)
	public String getObservationSante() {
		return this.observationSante;
	}

	public void setObservationSante(String observationSante) {
		this.observationSante = observationSante;
	}

	@Column(name = "TAUX_FACTEUR_MAJORATION", precision = 6, scale = 4)
	public BigDecimal getTauxFacteurMajoration() {
		return this.tauxFacteurMajoration;
	}

	public void setTauxFacteurMajoration(BigDecimal tauxFacteurMajoration) {
		this.tauxFacteurMajoration = tauxFacteurMajoration;
	}

	@Column(name = "SURPRIME_FACTEUR_MAJORATION", precision = 6, scale = 4)
	public BigDecimal getSurprimeFacteurMajoration() {
		return this.surprimeFacteurMajoration;
	}

	public void setSurprimeFacteurMajoration(
			BigDecimal surprimeFacteurMajoration) {
		this.surprimeFacteurMajoration = surprimeFacteurMajoration;
	}

	@Column(name = "OBSERVATION_FACTEUR_MAJORATION", length = 60)
	public String getObservationFacteurMajoration() {
		return this.observationFacteurMajoration;
	}

	public void setObservationFacteurMajoration(
			String observationFacteurMajoration) {
		this.observationFacteurMajoration = observationFacteurMajoration;
	}

}
