package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GarantieSinistreId generated by hbm2java
 */
@Embeddable
public class GarantieSinistreId implements java.io.Serializable {

	private String codeGarantie;
	private String codeSinistre;

	public GarantieSinistreId() {
	}

	public GarantieSinistreId(String codeGarantie, String codeSinistre) {
		this.codeGarantie = codeGarantie;
		this.codeSinistre = codeSinistre;
	}

	@Column(name = "CODE_GARANTIE", nullable = false, length = 12)
	public String getCodeGarantie() {
		return this.codeGarantie;
	}

	public void setCodeGarantie(String codeGarantie) {
		this.codeGarantie = codeGarantie;
	}

	@Column(name = "CODE_SINISTRE", nullable = false, length = 40)
	public String getCodeSinistre() {
		return this.codeSinistre;
	}

	public void setCodeSinistre(String codeSinistre) {
		this.codeSinistre = codeSinistre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GarantieSinistreId))
			return false;
		GarantieSinistreId castOther = (GarantieSinistreId) other;

		return ((this.getCodeGarantie() == castOther.getCodeGarantie()) || (this
				.getCodeGarantie() != null
				&& castOther.getCodeGarantie() != null && this
				.getCodeGarantie().equals(castOther.getCodeGarantie())))
				&& ((this.getCodeSinistre() == castOther.getCodeSinistre()) || (this
						.getCodeSinistre() != null
						&& castOther.getCodeSinistre() != null && this
						.getCodeSinistre().equals(castOther.getCodeSinistre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodeGarantie() == null ? 0 : this.getCodeGarantie()
						.hashCode());
		result = 37
				* result
				+ (getCodeSinistre() == null ? 0 : this.getCodeSinistre()
						.hashCode());
		return result;
	}

}
