package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GestionConfiee generated by hbm2java
 */
@Entity
@Table(name = "gestion_confiee", catalog = "zeusbd")
public class GestionConfiee implements java.io.Serializable {

	private String codeGestionConfie;
	private Categorie categorie;
	private ClasseGc classeGc;
	private CollegeSante collegeSante;
	private ListeGestionConfie listeGestionConfie;
	private Integer numIdentificationGc;
	private String natureGc;
	private String descriptionGc;
	private String territorialiteGc;
	private String tauxCouvGc;
	private BigDecimal planfondAnnuelGc;
	private Long tauxAjustGc;
	private Integer nbreChefFamille;
	private Integer nbrRetChefFamille;
	private BigDecimal primeChefFamille;
	private BigDecimal primeRetChefFamille;
	private BigDecimal primeTotChefFamille;
	private Integer nbreConjointGc;
	private Integer nbreRetConjoint;
	private BigDecimal primeConjoint;
	private BigDecimal primeRetConjoint;
	private BigDecimal primeTotConjoint;
	private Integer nbreEnftMaj;
	private Integer nbreRetEnftMaj;
	private BigDecimal primeEnftMaj;
	private BigDecimal primeRetEnftMaj;
	private BigDecimal primeTotEnftMaj;
	private Integer nbreEnftGc;
	private Integer nbreRetEnftGc;
	private BigDecimal primeEnfant;
	private BigDecimal primeRetEnftGc;
	private BigDecimal surprimeGc;
	private BigDecimal primeTotEnftGc;
	private BigDecimal primeTotaleGc;
	private Set<GestionnaireGc> gestionnaireGcs = new HashSet<GestionnaireGc>(0);
	private Set<ApporteurGestionConfiee> apporteurGestionConfiees = new HashSet<ApporteurGestionConfiee>(
			0);
	private Set<HistoGestionConfiee> histoGestionConfiees = new HashSet<HistoGestionConfiee>(
			0);
	private Set<GestionConfieFormule> gestionConfieFormules = new HashSet<GestionConfieFormule>(
			0);
	private Set<GestionConfieeSinistre> gestionConfieeSinistres = new HashSet<GestionConfieeSinistre>(
			0);

	public GestionConfiee() {
	}

	public GestionConfiee(String codeGestionConfie) {
		this.codeGestionConfie = codeGestionConfie;
	}

	public GestionConfiee(String codeGestionConfie, Categorie categorie,
			ClasseGc classeGc, CollegeSante collegeSante,
			ListeGestionConfie listeGestionConfie, Integer numIdentificationGc,
			String natureGc, String descriptionGc, String territorialiteGc,
			String tauxCouvGc, BigDecimal planfondAnnuelGc, Long tauxAjustGc,
			Integer nbreChefFamille, Integer nbrRetChefFamille,
			BigDecimal primeChefFamille, BigDecimal primeRetChefFamille,
			BigDecimal primeTotChefFamille, Integer nbreConjointGc,
			Integer nbreRetConjoint, BigDecimal primeConjoint,
			BigDecimal primeRetConjoint, BigDecimal primeTotConjoint,
			Integer nbreEnftMaj, Integer nbreRetEnftMaj,
			BigDecimal primeEnftMaj, BigDecimal primeRetEnftMaj,
			BigDecimal primeTotEnftMaj, Integer nbreEnftGc,
			Integer nbreRetEnftGc, BigDecimal primeEnfant,
			BigDecimal primeRetEnftGc, BigDecimal surprimeGc,
			BigDecimal primeTotEnftGc, BigDecimal primeTotaleGc,
			Set<GestionnaireGc> gestionnaireGcs,
			Set<ApporteurGestionConfiee> apporteurGestionConfiees,
			Set<HistoGestionConfiee> histoGestionConfiees,
			Set<GestionConfieFormule> gestionConfieFormules,
			Set<GestionConfieeSinistre> gestionConfieeSinistres) {
		this.codeGestionConfie = codeGestionConfie;
		this.categorie = categorie;
		this.classeGc = classeGc;
		this.collegeSante = collegeSante;
		this.listeGestionConfie = listeGestionConfie;
		this.numIdentificationGc = numIdentificationGc;
		this.natureGc = natureGc;
		this.descriptionGc = descriptionGc;
		this.territorialiteGc = territorialiteGc;
		this.tauxCouvGc = tauxCouvGc;
		this.planfondAnnuelGc = planfondAnnuelGc;
		this.tauxAjustGc = tauxAjustGc;
		this.nbreChefFamille = nbreChefFamille;
		this.nbrRetChefFamille = nbrRetChefFamille;
		this.primeChefFamille = primeChefFamille;
		this.primeRetChefFamille = primeRetChefFamille;
		this.primeTotChefFamille = primeTotChefFamille;
		this.nbreConjointGc = nbreConjointGc;
		this.nbreRetConjoint = nbreRetConjoint;
		this.primeConjoint = primeConjoint;
		this.primeRetConjoint = primeRetConjoint;
		this.primeTotConjoint = primeTotConjoint;
		this.nbreEnftMaj = nbreEnftMaj;
		this.nbreRetEnftMaj = nbreRetEnftMaj;
		this.primeEnftMaj = primeEnftMaj;
		this.primeRetEnftMaj = primeRetEnftMaj;
		this.primeTotEnftMaj = primeTotEnftMaj;
		this.nbreEnftGc = nbreEnftGc;
		this.nbreRetEnftGc = nbreRetEnftGc;
		this.primeEnfant = primeEnfant;
		this.primeRetEnftGc = primeRetEnftGc;
		this.surprimeGc = surprimeGc;
		this.primeTotEnftGc = primeTotEnftGc;
		this.primeTotaleGc = primeTotaleGc;
		this.gestionnaireGcs = gestionnaireGcs;
		this.apporteurGestionConfiees = apporteurGestionConfiees;
		this.histoGestionConfiees = histoGestionConfiees;
		this.gestionConfieFormules = gestionConfieFormules;
		this.gestionConfieeSinistres = gestionConfieeSinistres;
	}

	@Id
	@Column(name = "CODE_GESTION_CONFIE", unique = true, nullable = false, length = 60)
	public String getCodeGestionConfie() {
		return this.codeGestionConfie;
	}

	public void setCodeGestionConfie(String codeGestionConfie) {
		this.codeGestionConfie = codeGestionConfie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_CATEGORIE")
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_CLASSE_GC")
	public ClasseGc getClasseGc() {
		return this.classeGc;
	}

	public void setClasseGc(ClasseGc classeGc) {
		this.classeGc = classeGc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_COLLEGE")
	public CollegeSante getCollegeSante() {
		return this.collegeSante;
	}

	public void setCollegeSante(CollegeSante collegeSante) {
		this.collegeSante = collegeSante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_LISTE_GESTION_CONFIE")
	public ListeGestionConfie getListeGestionConfie() {
		return this.listeGestionConfie;
	}

	public void setListeGestionConfie(ListeGestionConfie listeGestionConfie) {
		this.listeGestionConfie = listeGestionConfie;
	}

	@Column(name = "NUM_IDENTIFICATION_GC")
	public Integer getNumIdentificationGc() {
		return this.numIdentificationGc;
	}

	public void setNumIdentificationGc(Integer numIdentificationGc) {
		this.numIdentificationGc = numIdentificationGc;
	}

	@Column(name = "NATURE_GC", length = 60)
	public String getNatureGc() {
		return this.natureGc;
	}

	public void setNatureGc(String natureGc) {
		this.natureGc = natureGc;
	}

	@Column(name = "DESCRIPTION_GC", length = 60)
	public String getDescriptionGc() {
		return this.descriptionGc;
	}

	public void setDescriptionGc(String descriptionGc) {
		this.descriptionGc = descriptionGc;
	}

	@Column(name = "TERRITORIALITE_GC", length = 60)
	public String getTerritorialiteGc() {
		return this.territorialiteGc;
	}

	public void setTerritorialiteGc(String territorialiteGc) {
		this.territorialiteGc = territorialiteGc;
	}

	@Column(name = "TAUX_COUV_GC", length = 80)
	public String getTauxCouvGc() {
		return this.tauxCouvGc;
	}

	public void setTauxCouvGc(String tauxCouvGc) {
		this.tauxCouvGc = tauxCouvGc;
	}

	@Column(name = "PLANFOND_ANNUEL_GC", precision = 15, scale = 3)
	public BigDecimal getPlanfondAnnuelGc() {
		return this.planfondAnnuelGc;
	}

	public void setPlanfondAnnuelGc(BigDecimal planfondAnnuelGc) {
		this.planfondAnnuelGc = planfondAnnuelGc;
	}

	@Column(name = "TAUX_AJUST_GC", precision = 10, scale = 0)
	public Long getTauxAjustGc() {
		return this.tauxAjustGc;
	}

	public void setTauxAjustGc(Long tauxAjustGc) {
		this.tauxAjustGc = tauxAjustGc;
	}

	@Column(name = "NBRE_CHEF_FAMILLE")
	public Integer getNbreChefFamille() {
		return this.nbreChefFamille;
	}

	public void setNbreChefFamille(Integer nbreChefFamille) {
		this.nbreChefFamille = nbreChefFamille;
	}

	@Column(name = "NBR_RET_CHEF_FAMILLE")
	public Integer getNbrRetChefFamille() {
		return this.nbrRetChefFamille;
	}

	public void setNbrRetChefFamille(Integer nbrRetChefFamille) {
		this.nbrRetChefFamille = nbrRetChefFamille;
	}

	@Column(name = "PRIME_CHEF_FAMILLE", precision = 15, scale = 3)
	public BigDecimal getPrimeChefFamille() {
		return this.primeChefFamille;
	}

	public void setPrimeChefFamille(BigDecimal primeChefFamille) {
		this.primeChefFamille = primeChefFamille;
	}

	@Column(name = "PRIME_RET_CHEF_FAMILLE", precision = 15, scale = 3)
	public BigDecimal getPrimeRetChefFamille() {
		return this.primeRetChefFamille;
	}

	public void setPrimeRetChefFamille(BigDecimal primeRetChefFamille) {
		this.primeRetChefFamille = primeRetChefFamille;
	}

	@Column(name = "PRIME_TOT_CHEF_FAMILLE", precision = 15, scale = 3)
	public BigDecimal getPrimeTotChefFamille() {
		return this.primeTotChefFamille;
	}

	public void setPrimeTotChefFamille(BigDecimal primeTotChefFamille) {
		this.primeTotChefFamille = primeTotChefFamille;
	}

	@Column(name = "NBRE_CONJOINT_GC")
	public Integer getNbreConjointGc() {
		return this.nbreConjointGc;
	}

	public void setNbreConjointGc(Integer nbreConjointGc) {
		this.nbreConjointGc = nbreConjointGc;
	}

	@Column(name = "NBRE_RET_CONJOINT")
	public Integer getNbreRetConjoint() {
		return this.nbreRetConjoint;
	}

	public void setNbreRetConjoint(Integer nbreRetConjoint) {
		this.nbreRetConjoint = nbreRetConjoint;
	}

	@Column(name = "PRIME_CONJOINT", precision = 15, scale = 3)
	public BigDecimal getPrimeConjoint() {
		return this.primeConjoint;
	}

	public void setPrimeConjoint(BigDecimal primeConjoint) {
		this.primeConjoint = primeConjoint;
	}

	@Column(name = "PRIME_RET_CONJOINT", precision = 15, scale = 3)
	public BigDecimal getPrimeRetConjoint() {
		return this.primeRetConjoint;
	}

	public void setPrimeRetConjoint(BigDecimal primeRetConjoint) {
		this.primeRetConjoint = primeRetConjoint;
	}

	@Column(name = "PRIME_TOT_CONJOINT", precision = 15, scale = 3)
	public BigDecimal getPrimeTotConjoint() {
		return this.primeTotConjoint;
	}

	public void setPrimeTotConjoint(BigDecimal primeTotConjoint) {
		this.primeTotConjoint = primeTotConjoint;
	}

	@Column(name = "NBRE_ENFT_MAJ")
	public Integer getNbreEnftMaj() {
		return this.nbreEnftMaj;
	}

	public void setNbreEnftMaj(Integer nbreEnftMaj) {
		this.nbreEnftMaj = nbreEnftMaj;
	}

	@Column(name = "NBRE_RET_ENFT_MAJ")
	public Integer getNbreRetEnftMaj() {
		return this.nbreRetEnftMaj;
	}

	public void setNbreRetEnftMaj(Integer nbreRetEnftMaj) {
		this.nbreRetEnftMaj = nbreRetEnftMaj;
	}

	@Column(name = "PRIME_ENFT_MAJ", precision = 15, scale = 3)
	public BigDecimal getPrimeEnftMaj() {
		return this.primeEnftMaj;
	}

	public void setPrimeEnftMaj(BigDecimal primeEnftMaj) {
		this.primeEnftMaj = primeEnftMaj;
	}

	@Column(name = "PRIME_RET_ENFT_MAJ", precision = 15, scale = 3)
	public BigDecimal getPrimeRetEnftMaj() {
		return this.primeRetEnftMaj;
	}

	public void setPrimeRetEnftMaj(BigDecimal primeRetEnftMaj) {
		this.primeRetEnftMaj = primeRetEnftMaj;
	}

	@Column(name = "PRIME_TOT_ENFT_MAJ", precision = 15, scale = 3)
	public BigDecimal getPrimeTotEnftMaj() {
		return this.primeTotEnftMaj;
	}

	public void setPrimeTotEnftMaj(BigDecimal primeTotEnftMaj) {
		this.primeTotEnftMaj = primeTotEnftMaj;
	}

	@Column(name = "NBRE_ENFT_GC")
	public Integer getNbreEnftGc() {
		return this.nbreEnftGc;
	}

	public void setNbreEnftGc(Integer nbreEnftGc) {
		this.nbreEnftGc = nbreEnftGc;
	}

	@Column(name = "NBRE_RET_ENFT_GC")
	public Integer getNbreRetEnftGc() {
		return this.nbreRetEnftGc;
	}

	public void setNbreRetEnftGc(Integer nbreRetEnftGc) {
		this.nbreRetEnftGc = nbreRetEnftGc;
	}

	@Column(name = "PRIME_ENFANT", precision = 15, scale = 3)
	public BigDecimal getPrimeEnfant() {
		return this.primeEnfant;
	}

	public void setPrimeEnfant(BigDecimal primeEnfant) {
		this.primeEnfant = primeEnfant;
	}

	@Column(name = "PRIME_RET_ENFT_GC", precision = 15, scale = 3)
	public BigDecimal getPrimeRetEnftGc() {
		return this.primeRetEnftGc;
	}

	public void setPrimeRetEnftGc(BigDecimal primeRetEnftGc) {
		this.primeRetEnftGc = primeRetEnftGc;
	}

	@Column(name = "SURPRIME_GC", precision = 15, scale = 3)
	public BigDecimal getSurprimeGc() {
		return this.surprimeGc;
	}

	public void setSurprimeGc(BigDecimal surprimeGc) {
		this.surprimeGc = surprimeGc;
	}

	@Column(name = "PRIME_TOT_ENFT_GC", precision = 15, scale = 3)
	public BigDecimal getPrimeTotEnftGc() {
		return this.primeTotEnftGc;
	}

	public void setPrimeTotEnftGc(BigDecimal primeTotEnftGc) {
		this.primeTotEnftGc = primeTotEnftGc;
	}

	@Column(name = "PRIME_TOTALE_GC", precision = 15, scale = 3)
	public BigDecimal getPrimeTotaleGc() {
		return this.primeTotaleGc;
	}

	public void setPrimeTotaleGc(BigDecimal primeTotaleGc) {
		this.primeTotaleGc = primeTotaleGc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestionConfiee")
	public Set<GestionnaireGc> getGestionnaireGcs() {
		return this.gestionnaireGcs;
	}

	public void setGestionnaireGcs(Set<GestionnaireGc> gestionnaireGcs) {
		this.gestionnaireGcs = gestionnaireGcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestionConfiee")
	public Set<ApporteurGestionConfiee> getApporteurGestionConfiees() {
		return this.apporteurGestionConfiees;
	}

	public void setApporteurGestionConfiees(
			Set<ApporteurGestionConfiee> apporteurGestionConfiees) {
		this.apporteurGestionConfiees = apporteurGestionConfiees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestionConfiee")
	public Set<HistoGestionConfiee> getHistoGestionConfiees() {
		return this.histoGestionConfiees;
	}

	public void setHistoGestionConfiees(
			Set<HistoGestionConfiee> histoGestionConfiees) {
		this.histoGestionConfiees = histoGestionConfiees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestionConfiee")
	public Set<GestionConfieFormule> getGestionConfieFormules() {
		return this.gestionConfieFormules;
	}

	public void setGestionConfieFormules(
			Set<GestionConfieFormule> gestionConfieFormules) {
		this.gestionConfieFormules = gestionConfieFormules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestionConfiee")
	public Set<GestionConfieeSinistre> getGestionConfieeSinistres() {
		return this.gestionConfieeSinistres;
	}

	public void setGestionConfieeSinistres(
			Set<GestionConfieeSinistre> gestionConfieeSinistres) {
		this.gestionConfieeSinistres = gestionConfieeSinistres;
	}

}
