package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gestionnaire generated by hbm2java
 */
@Entity
@Table(name = "gestionnaire", catalog = "zeusbd")
public class Gestionnaire implements java.io.Serializable {

	private String codeGestionnaire;
	private String raisonSocialGestionnaire;
	private String contactGestgc;
	private String adresseGestgc;
	private BigDecimal tauxComGestionnaireGc;
	private BigDecimal tauxAccGestionnairegc;
	private Set<GestionnaireGc> gestionnaireGcs = new HashSet<GestionnaireGc>(0);

	public Gestionnaire() {
	}

	public Gestionnaire(String codeGestionnaire) {
		this.codeGestionnaire = codeGestionnaire;
	}

	public Gestionnaire(String codeGestionnaire,
			String raisonSocialGestionnaire, String contactGestgc,
			String adresseGestgc, BigDecimal tauxComGestionnaireGc,
			BigDecimal tauxAccGestionnairegc,
			Set<GestionnaireGc> gestionnaireGcs) {
		this.codeGestionnaire = codeGestionnaire;
		this.raisonSocialGestionnaire = raisonSocialGestionnaire;
		this.contactGestgc = contactGestgc;
		this.adresseGestgc = adresseGestgc;
		this.tauxComGestionnaireGc = tauxComGestionnaireGc;
		this.tauxAccGestionnairegc = tauxAccGestionnairegc;
		this.gestionnaireGcs = gestionnaireGcs;
	}

	@Id
	@Column(name = "CODE_GESTIONNAIRE", unique = true, nullable = false, length = 30)
	public String getCodeGestionnaire() {
		return this.codeGestionnaire;
	}

	public void setCodeGestionnaire(String codeGestionnaire) {
		this.codeGestionnaire = codeGestionnaire;
	}

	@Column(name = "RAISON_SOCIAL_GESTIONNAIRE", length = 60)
	public String getRaisonSocialGestionnaire() {
		return this.raisonSocialGestionnaire;
	}

	public void setRaisonSocialGestionnaire(String raisonSocialGestionnaire) {
		this.raisonSocialGestionnaire = raisonSocialGestionnaire;
	}

	@Column(name = "CONTACT_GESTGC", length = 20)
	public String getContactGestgc() {
		return this.contactGestgc;
	}

	public void setContactGestgc(String contactGestgc) {
		this.contactGestgc = contactGestgc;
	}

	@Column(name = "ADRESSE_GESTGC", length = 80)
	public String getAdresseGestgc() {
		return this.adresseGestgc;
	}

	public void setAdresseGestgc(String adresseGestgc) {
		this.adresseGestgc = adresseGestgc;
	}

	@Column(name = "TAUX_COM_GESTIONNAIRE_GC", precision = 6, scale = 4)
	public BigDecimal getTauxComGestionnaireGc() {
		return this.tauxComGestionnaireGc;
	}

	public void setTauxComGestionnaireGc(BigDecimal tauxComGestionnaireGc) {
		this.tauxComGestionnaireGc = tauxComGestionnaireGc;
	}

	@Column(name = "TAUX_ACC_GESTIONNAIREGC", precision = 6, scale = 4)
	public BigDecimal getTauxAccGestionnairegc() {
		return this.tauxAccGestionnairegc;
	}

	public void setTauxAccGestionnairegc(BigDecimal tauxAccGestionnairegc) {
		this.tauxAccGestionnairegc = tauxAccGestionnairegc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestionnaire")
	public Set<GestionnaireGc> getGestionnaireGcs() {
		return this.gestionnaireGcs;
	}

	public void setGestionnaireGcs(Set<GestionnaireGc> gestionnaireGcs) {
		this.gestionnaireGcs = gestionnaireGcs;
	}

}
