package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lgc1credit generated by hbm2java
 */
@Entity
@Table(name = "lgc1credit", catalog = "zeusbd")
public class Lgc1credit implements java.io.Serializable {

	private String idlgc1credit;
	private CategorieCima categorieCima;
	private Etatc1 etatc1;
	private BigDecimal primaccesscred;
	private BigDecimal rappelscred;
	private BigDecimal addrannulcred;
	private BigDecimal primesnettescred;
	private BigDecimal provrisqencrsm31decprcred;
	private BigDecimal provrisqencrsp31deccred;
	private BigDecimal autrprovprmm31decprcred;
	private BigDecimal autrprovprmp31deccred;
	private BigDecimal provannulm31decprcred;
	private BigDecimal provannulp31deccred;
	private BigDecimal dotprovprmcred;
	private BigDecimal prodfinnetcred;
	private BigDecimal prodexcedcred;
	private BigDecimal partreasinprestacred;
	private BigDecimal partreasinprvpresm31decprcred;
	private BigDecimal partreasinprvpresp31deccred;
	private BigDecimal comreasscred;
	private BigDecimal partreassdschrgcred;
	private BigDecimal soldedebiteur;
	private BigDecimal totalcred;

	public Lgc1credit() {
	}

	public Lgc1credit(String idlgc1credit) {
		this.idlgc1credit = idlgc1credit;
	}

	public Lgc1credit(String idlgc1credit, CategorieCima categorieCima,
			Etatc1 etatc1, BigDecimal primaccesscred, BigDecimal rappelscred,
			BigDecimal addrannulcred, BigDecimal primesnettescred,
			BigDecimal provrisqencrsm31decprcred,
			BigDecimal provrisqencrsp31deccred,
			BigDecimal autrprovprmm31decprcred,
			BigDecimal autrprovprmp31deccred, BigDecimal provannulm31decprcred,
			BigDecimal provannulp31deccred, BigDecimal dotprovprmcred,
			BigDecimal prodfinnetcred, BigDecimal prodexcedcred,
			BigDecimal partreasinprestacred,
			BigDecimal partreasinprvpresm31decprcred,
			BigDecimal partreasinprvpresp31deccred, BigDecimal comreasscred,
			BigDecimal partreassdschrgcred, BigDecimal soldedebiteur,
			BigDecimal totalcred) {
		this.idlgc1credit = idlgc1credit;
		this.categorieCima = categorieCima;
		this.etatc1 = etatc1;
		this.primaccesscred = primaccesscred;
		this.rappelscred = rappelscred;
		this.addrannulcred = addrannulcred;
		this.primesnettescred = primesnettescred;
		this.provrisqencrsm31decprcred = provrisqencrsm31decprcred;
		this.provrisqencrsp31deccred = provrisqencrsp31deccred;
		this.autrprovprmm31decprcred = autrprovprmm31decprcred;
		this.autrprovprmp31deccred = autrprovprmp31deccred;
		this.provannulm31decprcred = provannulm31decprcred;
		this.provannulp31deccred = provannulp31deccred;
		this.dotprovprmcred = dotprovprmcred;
		this.prodfinnetcred = prodfinnetcred;
		this.prodexcedcred = prodexcedcred;
		this.partreasinprestacred = partreasinprestacred;
		this.partreasinprvpresm31decprcred = partreasinprvpresm31decprcred;
		this.partreasinprvpresp31deccred = partreasinprvpresp31deccred;
		this.comreasscred = comreasscred;
		this.partreassdschrgcred = partreassdschrgcred;
		this.soldedebiteur = soldedebiteur;
		this.totalcred = totalcred;
	}

	@Id
	@Column(name = "IDLGC1CREDIT", unique = true, nullable = false, length = 40)
	public String getIdlgc1credit() {
		return this.idlgc1credit;
	}

	public void setIdlgc1credit(String idlgc1credit) {
		this.idlgc1credit = idlgc1credit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODECATEGORIECIMA")
	public CategorieCima getCategorieCima() {
		return this.categorieCima;
	}

	public void setCategorieCima(CategorieCima categorieCima) {
		this.categorieCima = categorieCima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDETATC1")
	public Etatc1 getEtatc1() {
		return this.etatc1;
	}

	public void setEtatc1(Etatc1 etatc1) {
		this.etatc1 = etatc1;
	}

	@Column(name = "PRIMACCESSCRED", precision = 15, scale = 3)
	public BigDecimal getPrimaccesscred() {
		return this.primaccesscred;
	}

	public void setPrimaccesscred(BigDecimal primaccesscred) {
		this.primaccesscred = primaccesscred;
	}

	@Column(name = "RAPPELSCRED", precision = 15, scale = 3)
	public BigDecimal getRappelscred() {
		return this.rappelscred;
	}

	public void setRappelscred(BigDecimal rappelscred) {
		this.rappelscred = rappelscred;
	}

	@Column(name = "ADDRANNULCRED", precision = 15, scale = 3)
	public BigDecimal getAddrannulcred() {
		return this.addrannulcred;
	}

	public void setAddrannulcred(BigDecimal addrannulcred) {
		this.addrannulcred = addrannulcred;
	}

	@Column(name = "PRIMESNETTESCRED", precision = 15, scale = 3)
	public BigDecimal getPrimesnettescred() {
		return this.primesnettescred;
	}

	public void setPrimesnettescred(BigDecimal primesnettescred) {
		this.primesnettescred = primesnettescred;
	}

	@Column(name = "PROVRISQENCRSM31DECPRCRED", precision = 15, scale = 3)
	public BigDecimal getProvrisqencrsm31decprcred() {
		return this.provrisqencrsm31decprcred;
	}

	public void setProvrisqencrsm31decprcred(
			BigDecimal provrisqencrsm31decprcred) {
		this.provrisqencrsm31decprcred = provrisqencrsm31decprcred;
	}

	@Column(name = "PROVRISQENCRSP31DECCRED", precision = 15, scale = 3)
	public BigDecimal getProvrisqencrsp31deccred() {
		return this.provrisqencrsp31deccred;
	}

	public void setProvrisqencrsp31deccred(BigDecimal provrisqencrsp31deccred) {
		this.provrisqencrsp31deccred = provrisqencrsp31deccred;
	}

	@Column(name = "AUTRPROVPRMM31DECPRCRED", precision = 15, scale = 3)
	public BigDecimal getAutrprovprmm31decprcred() {
		return this.autrprovprmm31decprcred;
	}

	public void setAutrprovprmm31decprcred(BigDecimal autrprovprmm31decprcred) {
		this.autrprovprmm31decprcred = autrprovprmm31decprcred;
	}

	@Column(name = "AUTRPROVPRMP31DECCRED", precision = 15, scale = 3)
	public BigDecimal getAutrprovprmp31deccred() {
		return this.autrprovprmp31deccred;
	}

	public void setAutrprovprmp31deccred(BigDecimal autrprovprmp31deccred) {
		this.autrprovprmp31deccred = autrprovprmp31deccred;
	}

	@Column(name = "PROVANNULM31DECPRCRED", precision = 15, scale = 3)
	public BigDecimal getProvannulm31decprcred() {
		return this.provannulm31decprcred;
	}

	public void setProvannulm31decprcred(BigDecimal provannulm31decprcred) {
		this.provannulm31decprcred = provannulm31decprcred;
	}

	@Column(name = "PROVANNULP31DECCRED", precision = 15, scale = 3)
	public BigDecimal getProvannulp31deccred() {
		return this.provannulp31deccred;
	}

	public void setProvannulp31deccred(BigDecimal provannulp31deccred) {
		this.provannulp31deccred = provannulp31deccred;
	}

	@Column(name = "DOTPROVPRMCRED", precision = 15, scale = 3)
	public BigDecimal getDotprovprmcred() {
		return this.dotprovprmcred;
	}

	public void setDotprovprmcred(BigDecimal dotprovprmcred) {
		this.dotprovprmcred = dotprovprmcred;
	}

	@Column(name = "PRODFINNETCRED", precision = 15, scale = 3)
	public BigDecimal getProdfinnetcred() {
		return this.prodfinnetcred;
	}

	public void setProdfinnetcred(BigDecimal prodfinnetcred) {
		this.prodfinnetcred = prodfinnetcred;
	}

	@Column(name = "PRODEXCEDCRED", precision = 15, scale = 3)
	public BigDecimal getProdexcedcred() {
		return this.prodexcedcred;
	}

	public void setProdexcedcred(BigDecimal prodexcedcred) {
		this.prodexcedcred = prodexcedcred;
	}

	@Column(name = "PARTREASINPRESTACRED", precision = 15, scale = 3)
	public BigDecimal getPartreasinprestacred() {
		return this.partreasinprestacred;
	}

	public void setPartreasinprestacred(BigDecimal partreasinprestacred) {
		this.partreasinprestacred = partreasinprestacred;
	}

	@Column(name = "PARTREASINPRVPRESM31DECPRCRED", precision = 15, scale = 3)
	public BigDecimal getPartreasinprvpresm31decprcred() {
		return this.partreasinprvpresm31decprcred;
	}

	public void setPartreasinprvpresm31decprcred(
			BigDecimal partreasinprvpresm31decprcred) {
		this.partreasinprvpresm31decprcred = partreasinprvpresm31decprcred;
	}

	@Column(name = "PARTREASINPRVPRESP31DECCRED", precision = 15, scale = 3)
	public BigDecimal getPartreasinprvpresp31deccred() {
		return this.partreasinprvpresp31deccred;
	}

	public void setPartreasinprvpresp31deccred(
			BigDecimal partreasinprvpresp31deccred) {
		this.partreasinprvpresp31deccred = partreasinprvpresp31deccred;
	}

	@Column(name = "COMREASSCRED", precision = 15, scale = 3)
	public BigDecimal getComreasscred() {
		return this.comreasscred;
	}

	public void setComreasscred(BigDecimal comreasscred) {
		this.comreasscred = comreasscred;
	}

	@Column(name = "PARTREASSDSCHRGCRED", precision = 15, scale = 3)
	public BigDecimal getPartreassdschrgcred() {
		return this.partreassdschrgcred;
	}

	public void setPartreassdschrgcred(BigDecimal partreassdschrgcred) {
		this.partreassdschrgcred = partreassdschrgcred;
	}

	@Column(name = "SOLDEDEBITEUR", precision = 15, scale = 3)
	public BigDecimal getSoldedebiteur() {
		return this.soldedebiteur;
	}

	public void setSoldedebiteur(BigDecimal soldedebiteur) {
		this.soldedebiteur = soldedebiteur;
	}

	@Column(name = "TOTALCRED", precision = 15, scale = 3)
	public BigDecimal getTotalcred() {
		return this.totalcred;
	}

	public void setTotalcred(BigDecimal totalcred) {
		this.totalcred = totalcred;
	}

}
