package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ListeHabitation generated by hbm2java
 */
@Entity
@Table(name = "liste_habitation", catalog = "zeusbd")
public class ListeHabitation implements java.io.Serializable {

	private String codeListeHabitation;
	private String libelleListeHabitationMrh;
	private Set<Habitation> habitations = new HashSet<Habitation>(0);
	private Set<AvListeHabitation> avListeHabitations = new HashSet<AvListeHabitation>(
			0);

	public ListeHabitation() {
	}

	public ListeHabitation(String codeListeHabitation) {
		this.codeListeHabitation = codeListeHabitation;
	}

	public ListeHabitation(String codeListeHabitation,
			String libelleListeHabitationMrh, Set<Habitation> habitations,
			Set<AvListeHabitation> avListeHabitations) {
		this.codeListeHabitation = codeListeHabitation;
		this.libelleListeHabitationMrh = libelleListeHabitationMrh;
		this.habitations = habitations;
		this.avListeHabitations = avListeHabitations;
	}

	@Id
	@Column(name = "CODE_LISTE_HABITATION", unique = true, nullable = false, length = 27)
	public String getCodeListeHabitation() {
		return this.codeListeHabitation;
	}

	public void setCodeListeHabitation(String codeListeHabitation) {
		this.codeListeHabitation = codeListeHabitation;
	}

	@Column(name = "LIBELLE_LISTE_HABITATION_MRH", length = 50)
	public String getLibelleListeHabitationMrh() {
		return this.libelleListeHabitationMrh;
	}

	public void setLibelleListeHabitationMrh(String libelleListeHabitationMrh) {
		this.libelleListeHabitationMrh = libelleListeHabitationMrh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listeHabitation")
	public Set<Habitation> getHabitations() {
		return this.habitations;
	}

	public void setHabitations(Set<Habitation> habitations) {
		this.habitations = habitations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listeHabitation")
	public Set<AvListeHabitation> getAvListeHabitations() {
		return this.avListeHabitations;
	}

	public void setAvListeHabitations(Set<AvListeHabitation> avListeHabitations) {
		this.avListeHabitations = avListeHabitations;
	}

}
