package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ListeAdherent generated by hbm2java
 */
@Entity
@Table(name = "liste_adherent", catalog = "zeusbd")
public class ListeAdherent implements java.io.Serializable {

	private String codeListeAdherent;
	private String libelleListeAdherent;
	private Set<ListeAdherentSante> listeAdherentSantes = new HashSet<ListeAdherentSante>(
			0);
	private Set<AvListeAdherent> avListeAdherents = new HashSet<AvListeAdherent>(
			0);

	public ListeAdherent() {
	}

	public ListeAdherent(String codeListeAdherent) {
		this.codeListeAdherent = codeListeAdherent;
	}

	public ListeAdherent(String codeListeAdherent, String libelleListeAdherent,
			Set<ListeAdherentSante> listeAdherentSantes,
			Set<AvListeAdherent> avListeAdherents) {
		this.codeListeAdherent = codeListeAdherent;
		this.libelleListeAdherent = libelleListeAdherent;
		this.listeAdherentSantes = listeAdherentSantes;
		this.avListeAdherents = avListeAdherents;
	}

	@Id
	@Column(name = "CODE_LISTE_ADHERENT", unique = true, nullable = false, length = 60)
	public String getCodeListeAdherent() {
		return this.codeListeAdherent;
	}

	public void setCodeListeAdherent(String codeListeAdherent) {
		this.codeListeAdherent = codeListeAdherent;
	}

	@Column(name = "LIBELLE_LISTE_ADHERENT", length = 60)
	public String getLibelleListeAdherent() {
		return this.libelleListeAdherent;
	}

	public void setLibelleListeAdherent(String libelleListeAdherent) {
		this.libelleListeAdherent = libelleListeAdherent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listeAdherent")
	public Set<ListeAdherentSante> getListeAdherentSantes() {
		return this.listeAdherentSantes;
	}

	public void setListeAdherentSantes(
			Set<ListeAdherentSante> listeAdherentSantes) {
		this.listeAdherentSantes = listeAdherentSantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listeAdherent")
	public Set<AvListeAdherent> getAvListeAdherents() {
		return this.avListeAdherents;
	}

	public void setAvListeAdherents(Set<AvListeAdherent> avListeAdherents) {
		this.avListeAdherents = avListeAdherents;
	}

}
