package com.j3a.assurance.model;

// Generated 10 août 2015 09:53:29 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModifiCapital generated by hbm2java
 */
@Entity
@Table(name = "modifi_capital", catalog = "zeusbd")
public class ModifiCapital implements java.io.Serializable {

	private String codeModifCap;
	private Exercice exercice;
	private BigDecimal capitalSocialInitial;
	private BigDecimal versements;
	private BigDecimal appels;
	private BigDecimal capitalSocialFinExo;
	private BigDecimal fondEtablissementInitial;
	private BigDecimal amortissements;
	private BigDecimal fondEtablissementFinExo;
	private Set<ModifcapitalExercice> modifcapitalExercices = new HashSet<ModifcapitalExercice>(
			0);

	public ModifiCapital() {
	}

	public ModifiCapital(String codeModifCap, Exercice exercice) {
		this.codeModifCap = codeModifCap;
		this.exercice = exercice;
	}

	public ModifiCapital(String codeModifCap, Exercice exercice,
			BigDecimal capitalSocialInitial, BigDecimal versements,
			BigDecimal appels, BigDecimal capitalSocialFinExo,
			BigDecimal fondEtablissementInitial, BigDecimal amortissements,
			BigDecimal fondEtablissementFinExo,
			Set<ModifcapitalExercice> modifcapitalExercices) {
		this.codeModifCap = codeModifCap;
		this.exercice = exercice;
		this.capitalSocialInitial = capitalSocialInitial;
		this.versements = versements;
		this.appels = appels;
		this.capitalSocialFinExo = capitalSocialFinExo;
		this.fondEtablissementInitial = fondEtablissementInitial;
		this.amortissements = amortissements;
		this.fondEtablissementFinExo = fondEtablissementFinExo;
		this.modifcapitalExercices = modifcapitalExercices;
	}

	@Id
	@Column(name = "CODE_MODIF_CAP", unique = true, nullable = false, length = 20)
	public String getCodeModifCap() {
		return this.codeModifCap;
	}

	public void setCodeModifCap(String codeModifCap) {
		this.codeModifCap = codeModifCap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEEXERCICE", nullable = false)
	public Exercice getExercice() {
		return this.exercice;
	}

	public void setExercice(Exercice exercice) {
		this.exercice = exercice;
	}

	@Column(name = "CAPITAL_SOCIAL_INITIAL", precision = 15, scale = 3)
	public BigDecimal getCapitalSocialInitial() {
		return this.capitalSocialInitial;
	}

	public void setCapitalSocialInitial(BigDecimal capitalSocialInitial) {
		this.capitalSocialInitial = capitalSocialInitial;
	}

	@Column(name = "VERSEMENTS", precision = 15, scale = 3)
	public BigDecimal getVersements() {
		return this.versements;
	}

	public void setVersements(BigDecimal versements) {
		this.versements = versements;
	}

	@Column(name = "APPELS", precision = 15, scale = 3)
	public BigDecimal getAppels() {
		return this.appels;
	}

	public void setAppels(BigDecimal appels) {
		this.appels = appels;
	}

	@Column(name = "CAPITAL_SOCIAL_FIN_EXO", precision = 15, scale = 3)
	public BigDecimal getCapitalSocialFinExo() {
		return this.capitalSocialFinExo;
	}

	public void setCapitalSocialFinExo(BigDecimal capitalSocialFinExo) {
		this.capitalSocialFinExo = capitalSocialFinExo;
	}

	@Column(name = "FOND_ETABLISSEMENT_INITIAL", precision = 15, scale = 3)
	public BigDecimal getFondEtablissementInitial() {
		return this.fondEtablissementInitial;
	}

	public void setFondEtablissementInitial(BigDecimal fondEtablissementInitial) {
		this.fondEtablissementInitial = fondEtablissementInitial;
	}

	@Column(name = "AMORTISSEMENTS", precision = 15, scale = 3)
	public BigDecimal getAmortissements() {
		return this.amortissements;
	}

	public void setAmortissements(BigDecimal amortissements) {
		this.amortissements = amortissements;
	}

	@Column(name = "FOND_ETABLISSEMENT_FIN_EXO", precision = 15, scale = 3)
	public BigDecimal getFondEtablissementFinExo() {
		return this.fondEtablissementFinExo;
	}

	public void setFondEtablissementFinExo(BigDecimal fondEtablissementFinExo) {
		this.fondEtablissementFinExo = fondEtablissementFinExo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modifiCapital")
	public Set<ModifcapitalExercice> getModifcapitalExercices() {
		return this.modifcapitalExercices;
	}

	public void setModifcapitalExercices(
			Set<ModifcapitalExercice> modifcapitalExercices) {
		this.modifcapitalExercices = modifcapitalExercices;
	}

}
