package com.j3a.assurance.model;

// Generated 10 août 2015 09:53:29 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModifcapitalExercice generated by hbm2java
 */
@Entity
@Table(name = "modifcapital_exercice", catalog = "zeusbd")
public class ModifcapitalExercice implements java.io.Serializable {

	private ModifcapitalExerciceId id;
	private EtatCima etatCima;
	private ModifiCapital modifiCapital;

	public ModifcapitalExercice() {
	}

	public ModifcapitalExercice(ModifcapitalExerciceId id, EtatCima etatCima,
			ModifiCapital modifiCapital) {
		this.id = id;
		this.etatCima = etatCima;
		this.modifiCapital = modifiCapital;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeEtatCima", column = @Column(name = "CODE_ETAT_CIMA", nullable = false, length = 20)),
			@AttributeOverride(name = "codeModifCap", column = @Column(name = "CODE_MODIF_CAP", nullable = false, length = 20)) })
	public ModifcapitalExerciceId getId() {
		return this.id;
	}

	public void setId(ModifcapitalExerciceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, insertable = false, updatable = false)
	public EtatCima getEtatCima() {
		return this.etatCima;
	}

	public void setEtatCima(EtatCima etatCima) {
		this.etatCima = etatCima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_MODIF_CAP", nullable = false, insertable = false, updatable = false)
	public ModifiCapital getModifiCapital() {
		return this.modifiCapital;
	}

	public void setModifiCapital(ModifiCapital modifiCapital) {
		this.modifiCapital = modifiCapital;
	}

}
