package com.j3a.assurance.model;

// Generated 10 août 2015 09:53:29 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ObligationEmprunt generated by hbm2java
 */
@Entity
@Table(name = "obligation_emprunt", catalog = "zeusbd")
public class ObligationEmprunt implements java.io.Serializable {

	private String codeObEmp;
	private Exercice exercice;
	private String nature;
	private BigDecimal montant;
	private String type;
	private Set<ObligationExercice> obligationExercices = new HashSet<ObligationExercice>(
			0);

	public ObligationEmprunt() {
	}

	public ObligationEmprunt(String codeObEmp, Exercice exercice) {
		this.codeObEmp = codeObEmp;
		this.exercice = exercice;
	}

	public ObligationEmprunt(String codeObEmp, Exercice exercice,
			String nature, BigDecimal montant, String type,
			Set<ObligationExercice> obligationExercices) {
		this.codeObEmp = codeObEmp;
		this.exercice = exercice;
		this.nature = nature;
		this.montant = montant;
		this.type = type;
		this.obligationExercices = obligationExercices;
	}

	@Id
	@Column(name = "CODE_OB_EMP", unique = true, nullable = false, length = 20)
	public String getCodeObEmp() {
		return this.codeObEmp;
	}

	public void setCodeObEmp(String codeObEmp) {
		this.codeObEmp = codeObEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEEXERCICE", nullable = false)
	public Exercice getExercice() {
		return this.exercice;
	}

	public void setExercice(Exercice exercice) {
		this.exercice = exercice;
	}

	@Column(name = "NATURE", length = 30)
	public String getNature() {
		return this.nature;
	}

	public void setNature(String nature) {
		this.nature = nature;
	}

	@Column(name = "MONTANT", precision = 15, scale = 3)
	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	@Column(name = "TYPE", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "obligationEmprunt")
	public Set<ObligationExercice> getObligationExercices() {
		return this.obligationExercices;
	}

	public void setObligationExercices(
			Set<ObligationExercice> obligationExercices) {
		this.obligationExercices = obligationExercices;
	}

}
