package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObligationExerciceId generated by hbm2java
 */
@Embeddable
public class ObligationExerciceId implements java.io.Serializable {

	private String codeEtatCima;
	private String codeObEmp;

	public ObligationExerciceId() {
	}

	public ObligationExerciceId(String codeEtatCima, String codeObEmp) {
		this.codeEtatCima = codeEtatCima;
		this.codeObEmp = codeObEmp;
	}

	@Column(name = "CODE_ETAT_CIMA", nullable = false, length = 20)
	public String getCodeEtatCima() {
		return this.codeEtatCima;
	}

	public void setCodeEtatCima(String codeEtatCima) {
		this.codeEtatCima = codeEtatCima;
	}

	@Column(name = "CODE_OB_EMP", nullable = false, length = 20)
	public String getCodeObEmp() {
		return this.codeObEmp;
	}

	public void setCodeObEmp(String codeObEmp) {
		this.codeObEmp = codeObEmp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObligationExerciceId))
			return false;
		ObligationExerciceId castOther = (ObligationExerciceId) other;

		return ((this.getCodeEtatCima() == castOther.getCodeEtatCima()) || (this
				.getCodeEtatCima() != null
				&& castOther.getCodeEtatCima() != null && this
				.getCodeEtatCima().equals(castOther.getCodeEtatCima())))
				&& ((this.getCodeObEmp() == castOther.getCodeObEmp()) || (this
						.getCodeObEmp() != null
						&& castOther.getCodeObEmp() != null && this
						.getCodeObEmp().equals(castOther.getCodeObEmp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodeEtatCima() == null ? 0 : this.getCodeEtatCima()
						.hashCode());
		result = 37 * result
				+ (getCodeObEmp() == null ? 0 : this.getCodeObEmp().hashCode());
		return result;
	}

}
