package com.j3a.assurance.model;

// Generated 10 août 2015 09:53:29 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObligationExercice generated by hbm2java
 */
@Entity
@Table(name = "obligation_exercice", catalog = "zeusbd")
public class ObligationExercice implements java.io.Serializable {

	private ObligationExerciceId id;
	private EtatCima etatCima;
	private ObligationEmprunt obligationEmprunt;

	public ObligationExercice() {
	}

	public ObligationExercice(ObligationExerciceId id, EtatCima etatCima,
			ObligationEmprunt obligationEmprunt) {
		this.id = id;
		this.etatCima = etatCima;
		this.obligationEmprunt = obligationEmprunt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeEtatCima", column = @Column(name = "CODE_ETAT_CIMA", nullable = false, length = 20)),
			@AttributeOverride(name = "codeObEmp", column = @Column(name = "CODE_OB_EMP", nullable = false, length = 20)) })
	public ObligationExerciceId getId() {
		return this.id;
	}

	public void setId(ObligationExerciceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, insertable = false, updatable = false)
	public EtatCima getEtatCima() {
		return this.etatCima;
	}

	public void setEtatCima(EtatCima etatCima) {
		this.etatCima = etatCima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_OB_EMP", nullable = false, insertable = false, updatable = false)
	public ObligationEmprunt getObligationEmprunt() {
		return this.obligationEmprunt;
	}

	public void setObligationEmprunt(ObligationEmprunt obligationEmprunt) {
		this.obligationEmprunt = obligationEmprunt;
	}

}
