package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PaysactionExercice generated by hbm2java
 */
@Entity
@Table(name = "paysaction_exercice", catalog = "zeusbd")
public class PaysactionExercice implements java.io.Serializable {

	private PaysactionExerciceId id;

	public PaysactionExercice() {
	}

	public PaysactionExercice(PaysactionExerciceId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeEtatCima", column = @Column(name = "CODE_ETAT_CIMA", nullable = false, length = 20)),
			@AttributeOverride(name = "codePa", column = @Column(name = "CODE_PA", nullable = false, length = 20)) })
	public PaysactionExerciceId getId() {
		return this.id;
	}

	public void setId(PaysactionExerciceId id) {
		this.id = id;
	}

}
