package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PoertefeilExercice generated by hbm2java
 */
@Entity
@Table(name = "poertefeil_exercice", catalog = "zeusbd")
public class PoertefeilExercice implements java.io.Serializable {

	private PoertefeilExerciceId id;

	public PoertefeilExercice() {
	}

	public PoertefeilExercice(PoertefeilExerciceId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codePortefeilles", column = @Column(name = "CODE_PORTEFEILLES", nullable = false, length = 20)),
			@AttributeOverride(name = "codeEtatCima", column = @Column(name = "CODE_ETAT_CIMA", nullable = false, length = 20)) })
	public PoertefeilExerciceId getId() {
		return this.id;
	}

	public void setId(PoertefeilExerciceId id) {
		this.id = id;
	}

}
