package com.j3a.assurance.model;

// Generated 6 août 2015 16:35:56 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Portefeuilles generated by hbm2java
 */
@Entity
@Table(name = "portefeuilles", catalog = "zeusbd")
public class Portefeuilles implements java.io.Serializable {

	private String codePortefeilles;
	private Set<Vente> ventes = new HashSet<Vente>(0);
	private Set<Achat> achats = new HashSet<Achat>(0);
	private Set<PoertefeilExercice> poertefeilExercices = new HashSet<PoertefeilExercice>(
			0);

	public Portefeuilles() {
	}

	public Portefeuilles(String codePortefeilles) {
		this.codePortefeilles = codePortefeilles;
	}

	public Portefeuilles(String codePortefeilles, Set<Vente> ventes,
			Set<Achat> achats, Set<PoertefeilExercice> poertefeilExercices) {
		this.codePortefeilles = codePortefeilles;
		this.ventes = ventes;
		this.achats = achats;
		this.poertefeilExercices = poertefeilExercices;
	}

	@Id
	@Column(name = "CODE_PORTEFEILLES", unique = true, nullable = false, length = 20)
	public String getCodePortefeilles() {
		return this.codePortefeilles;
	}

	public void setCodePortefeilles(String codePortefeilles) {
		this.codePortefeilles = codePortefeilles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "portefeuilles")
	public Set<Vente> getVentes() {
		return this.ventes;
	}

	public void setVentes(Set<Vente> ventes) {
		this.ventes = ventes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "portefeuilles")
	public Set<Achat> getAchats() {
		return this.achats;
	}

	public void setAchats(Set<Achat> achats) {
		this.achats = achats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "portefeuilles")
	public Set<PoertefeilExercice> getPoertefeilExercices() {
		return this.poertefeilExercices;
	}

	public void setPoertefeilExercices(
			Set<PoertefeilExercice> poertefeilExercices) {
		this.poertefeilExercices = poertefeilExercices;
	}

}
