package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name = "province", catalog = "zeusbd")
public class Province implements java.io.Serializable {

	private String codeProvince;
	private Pays pays;
	private String libelleProvince;
	private Set<Ville> villes = new HashSet<Ville>(0);

	public Province() {
	}

	public Province(String codeProvince, Pays pays) {
		this.codeProvince = codeProvince;
		this.pays = pays;
	}

	public Province(String codeProvince, Pays pays, String libelleProvince,
			Set<Ville> villes) {
		this.codeProvince = codeProvince;
		this.pays = pays;
		this.libelleProvince = libelleProvince;
		this.villes = villes;
	}

	@Id
	@Column(name = "CODE_PROVINCE", unique = true, nullable = false, length = 40)
	public String getCodeProvince() {
		return this.codeProvince;
	}

	public void setCodeProvince(String codeProvince) {
		this.codeProvince = codeProvince;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_PAYS", nullable = false)
	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	@Column(name = "LIBELLE_PROVINCE", length = 50)
	public String getLibelleProvince() {
		return this.libelleProvince;
	}

	public void setLibelleProvince(String libelleProvince) {
		this.libelleProvince = libelleProvince;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "province")
	public Set<Ville> getVilles() {
		return this.villes;
	}

	public void setVilles(Set<Ville> villes) {
		this.villes = villes;
	}

}
