package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RcTarif10 generated by hbm2java
 */
@Entity
@Table(name = "rc_tarif10", catalog = "zeusbd")
public class RcTarif10 implements java.io.Serializable {

	private String codeRcTarif10;
	private BigDecimal paE12D1Zone1;
	private BigDecimal paE36D24Zone1;
	private BigDecimal paE79D56Zone1;
	private BigDecimal paE1011D78Zone1;
	private BigDecimal paE12D9Zone1;
	private BigDecimal paE12D1Zone2;
	private BigDecimal paE12D1Zone3;
	private BigDecimal paE36D24Zone2;
	private BigDecimal paE36D24Zone3;
	private BigDecimal paE79D56Zone2;
	private BigDecimal paE79D56Zone3;
	private BigDecimal paE1011D78Zone2;
	private BigDecimal paE1011D78Zone3;
	private BigDecimal paE12D9Zone2;
	private BigDecimal paE12D9Zone3;
	private Set<Tarif> tarifs = new HashSet<Tarif>(0);

	public RcTarif10() {
	}

	public RcTarif10(String codeRcTarif10) {
		this.codeRcTarif10 = codeRcTarif10;
	}

	public RcTarif10(String codeRcTarif10, BigDecimal paE12D1Zone1,
			BigDecimal paE36D24Zone1, BigDecimal paE79D56Zone1,
			BigDecimal paE1011D78Zone1, BigDecimal paE12D9Zone1,
			BigDecimal paE12D1Zone2, BigDecimal paE12D1Zone3,
			BigDecimal paE36D24Zone2, BigDecimal paE36D24Zone3,
			BigDecimal paE79D56Zone2, BigDecimal paE79D56Zone3,
			BigDecimal paE1011D78Zone2, BigDecimal paE1011D78Zone3,
			BigDecimal paE12D9Zone2, BigDecimal paE12D9Zone3, Set<Tarif> tarifs) {
		this.codeRcTarif10 = codeRcTarif10;
		this.paE12D1Zone1 = paE12D1Zone1;
		this.paE36D24Zone1 = paE36D24Zone1;
		this.paE79D56Zone1 = paE79D56Zone1;
		this.paE1011D78Zone1 = paE1011D78Zone1;
		this.paE12D9Zone1 = paE12D9Zone1;
		this.paE12D1Zone2 = paE12D1Zone2;
		this.paE12D1Zone3 = paE12D1Zone3;
		this.paE36D24Zone2 = paE36D24Zone2;
		this.paE36D24Zone3 = paE36D24Zone3;
		this.paE79D56Zone2 = paE79D56Zone2;
		this.paE79D56Zone3 = paE79D56Zone3;
		this.paE1011D78Zone2 = paE1011D78Zone2;
		this.paE1011D78Zone3 = paE1011D78Zone3;
		this.paE12D9Zone2 = paE12D9Zone2;
		this.paE12D9Zone3 = paE12D9Zone3;
		this.tarifs = tarifs;
	}

	@Id
	@Column(name = "CODE_RC_TARIF10", unique = true, nullable = false, length = 16)
	public String getCodeRcTarif10() {
		return this.codeRcTarif10;
	}

	public void setCodeRcTarif10(String codeRcTarif10) {
		this.codeRcTarif10 = codeRcTarif10;
	}

	@Column(name = "PA_E12_D1_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPaE12D1Zone1() {
		return this.paE12D1Zone1;
	}

	public void setPaE12D1Zone1(BigDecimal paE12D1Zone1) {
		this.paE12D1Zone1 = paE12D1Zone1;
	}

	@Column(name = "PA_E36_D24_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPaE36D24Zone1() {
		return this.paE36D24Zone1;
	}

	public void setPaE36D24Zone1(BigDecimal paE36D24Zone1) {
		this.paE36D24Zone1 = paE36D24Zone1;
	}

	@Column(name = "PA_E79_D56_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPaE79D56Zone1() {
		return this.paE79D56Zone1;
	}

	public void setPaE79D56Zone1(BigDecimal paE79D56Zone1) {
		this.paE79D56Zone1 = paE79D56Zone1;
	}

	@Column(name = "PA_E1011_D78_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPaE1011D78Zone1() {
		return this.paE1011D78Zone1;
	}

	public void setPaE1011D78Zone1(BigDecimal paE1011D78Zone1) {
		this.paE1011D78Zone1 = paE1011D78Zone1;
	}

	@Column(name = "PA_E12_D9_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPaE12D9Zone1() {
		return this.paE12D9Zone1;
	}

	public void setPaE12D9Zone1(BigDecimal paE12D9Zone1) {
		this.paE12D9Zone1 = paE12D9Zone1;
	}

	@Column(name = "PA_E12_D1_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPaE12D1Zone2() {
		return this.paE12D1Zone2;
	}

	public void setPaE12D1Zone2(BigDecimal paE12D1Zone2) {
		this.paE12D1Zone2 = paE12D1Zone2;
	}

	@Column(name = "PA_E12_D1_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPaE12D1Zone3() {
		return this.paE12D1Zone3;
	}

	public void setPaE12D1Zone3(BigDecimal paE12D1Zone3) {
		this.paE12D1Zone3 = paE12D1Zone3;
	}

	@Column(name = "PA_E36_D24_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPaE36D24Zone2() {
		return this.paE36D24Zone2;
	}

	public void setPaE36D24Zone2(BigDecimal paE36D24Zone2) {
		this.paE36D24Zone2 = paE36D24Zone2;
	}

	@Column(name = "PA_E36_D24_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPaE36D24Zone3() {
		return this.paE36D24Zone3;
	}

	public void setPaE36D24Zone3(BigDecimal paE36D24Zone3) {
		this.paE36D24Zone3 = paE36D24Zone3;
	}

	@Column(name = "PA_E79_D56_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPaE79D56Zone2() {
		return this.paE79D56Zone2;
	}

	public void setPaE79D56Zone2(BigDecimal paE79D56Zone2) {
		this.paE79D56Zone2 = paE79D56Zone2;
	}

	@Column(name = "PA_E79_D56_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPaE79D56Zone3() {
		return this.paE79D56Zone3;
	}

	public void setPaE79D56Zone3(BigDecimal paE79D56Zone3) {
		this.paE79D56Zone3 = paE79D56Zone3;
	}

	@Column(name = "PA_E1011_D78_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPaE1011D78Zone2() {
		return this.paE1011D78Zone2;
	}

	public void setPaE1011D78Zone2(BigDecimal paE1011D78Zone2) {
		this.paE1011D78Zone2 = paE1011D78Zone2;
	}

	@Column(name = "PA_E1011_D78_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPaE1011D78Zone3() {
		return this.paE1011D78Zone3;
	}

	public void setPaE1011D78Zone3(BigDecimal paE1011D78Zone3) {
		this.paE1011D78Zone3 = paE1011D78Zone3;
	}

	@Column(name = "PA_E12_D9_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPaE12D9Zone2() {
		return this.paE12D9Zone2;
	}

	public void setPaE12D9Zone2(BigDecimal paE12D9Zone2) {
		this.paE12D9Zone2 = paE12D9Zone2;
	}

	@Column(name = "PA_E12_D9_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPaE12D9Zone3() {
		return this.paE12D9Zone3;
	}

	public void setPaE12D9Zone3(BigDecimal paE12D9Zone3) {
		this.paE12D9Zone3 = paE12D9Zone3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rcTarif10")
	public Set<Tarif> getTarifs() {
		return this.tarifs;
	}

	public void setTarifs(Set<Tarif> tarifs) {
		this.tarifs = tarifs;
	}

}
