package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Reassurance generated by hbm2java
 */
@Entity
@Table(name = "reassurance", catalog = "zeusbd")
public class Reassurance implements java.io.Serializable {

	private String codeReassurance;
	private Contrat contrat;
	private BigDecimal montantReassurance;
	private Set<ReassuranceCompagnie> reassuranceCompagnies = new HashSet<ReassuranceCompagnie>(
			0);

	public Reassurance() {
	}

	public Reassurance(String codeReassurance, Contrat contrat) {
		this.codeReassurance = codeReassurance;
		this.contrat = contrat;
	}

	public Reassurance(String codeReassurance, Contrat contrat,
			BigDecimal montantReassurance,
			Set<ReassuranceCompagnie> reassuranceCompagnies) {
		this.codeReassurance = codeReassurance;
		this.contrat = contrat;
		this.montantReassurance = montantReassurance;
		this.reassuranceCompagnies = reassuranceCompagnies;
	}

	@Id
	@Column(name = "CODE_REASSURANCE", unique = true, nullable = false, length = 16)
	public String getCodeReassurance() {
		return this.codeReassurance;
	}

	public void setCodeReassurance(String codeReassurance) {
		this.codeReassurance = codeReassurance;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUM_POLICE", nullable = false)
	public Contrat getContrat() {
		return this.contrat;
	}

	public void setContrat(Contrat contrat) {
		this.contrat = contrat;
	}

	@Column(name = "MONTANT_REASSURANCE", precision = 15, scale = 3)
	public BigDecimal getMontantReassurance() {
		return this.montantReassurance;
	}

	public void setMontantReassurance(BigDecimal montantReassurance) {
		this.montantReassurance = montantReassurance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reassurance")
	public Set<ReassuranceCompagnie> getReassuranceCompagnies() {
		return this.reassuranceCompagnies;
	}

	public void setReassuranceCompagnies(
			Set<ReassuranceCompagnie> reassuranceCompagnies) {
		this.reassuranceCompagnies = reassuranceCompagnies;
	}

}
