package com.j3a.assurance.model;

// Generated 11 août 2015 12:07:31 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReglementCompagnieAssurance generated by hbm2java
 */
@Entity
@Table(name = "reglement_compagnie_assurance", catalog = "zeusbd")
public class ReglementCompagnieAssurance implements java.io.Serializable {

	private String codeReglementCompagnie;
	private CompteCompagnieAssurance compteCompagnieAssurance;
	private Date dateReglementCompagnie;
	private BigDecimal montantReglementCompagnie;
	private String typeReglementCompagnie;

	public ReglementCompagnieAssurance() {
	}

	public ReglementCompagnieAssurance(String codeReglementCompagnie,
			CompteCompagnieAssurance compteCompagnieAssurance) {
		this.codeReglementCompagnie = codeReglementCompagnie;
		this.compteCompagnieAssurance = compteCompagnieAssurance;
	}

	public ReglementCompagnieAssurance(String codeReglementCompagnie,
			CompteCompagnieAssurance compteCompagnieAssurance,
			Date dateReglementCompagnie, BigDecimal montantReglementCompagnie,
			String typeReglementCompagnie) {
		this.codeReglementCompagnie = codeReglementCompagnie;
		this.compteCompagnieAssurance = compteCompagnieAssurance;
		this.dateReglementCompagnie = dateReglementCompagnie;
		this.montantReglementCompagnie = montantReglementCompagnie;
		this.typeReglementCompagnie = typeReglementCompagnie;
	}

	@Id
	@Column(name = "CODE_REGLEMENT_COMPAGNIE", unique = true, nullable = false, length = 16)
	public String getCodeReglementCompagnie() {
		return this.codeReglementCompagnie;
	}

	public void setCodeReglementCompagnie(String codeReglementCompagnie) {
		this.codeReglementCompagnie = codeReglementCompagnie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_COMPTE_COMP_ASS", nullable = false)
	public CompteCompagnieAssurance getCompteCompagnieAssurance() {
		return this.compteCompagnieAssurance;
	}

	public void setCompteCompagnieAssurance(
			CompteCompagnieAssurance compteCompagnieAssurance) {
		this.compteCompagnieAssurance = compteCompagnieAssurance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_REGLEMENT_COMPAGNIE", length = 10)
	public Date getDateReglementCompagnie() {
		return this.dateReglementCompagnie;
	}

	public void setDateReglementCompagnie(Date dateReglementCompagnie) {
		this.dateReglementCompagnie = dateReglementCompagnie;
	}

	@Column(name = "MONTANT_REGLEMENT_COMPAGNIE", precision = 15, scale = 3)
	public BigDecimal getMontantReglementCompagnie() {
		return this.montantReglementCompagnie;
	}

	public void setMontantReglementCompagnie(
			BigDecimal montantReglementCompagnie) {
		this.montantReglementCompagnie = montantReglementCompagnie;
	}

	@Column(name = "TYPE_REGLEMENT_COMPAGNIE", length = 20)
	public String getTypeReglementCompagnie() {
		return this.typeReglementCompagnie;
	}

	public void setTypeReglementCompagnie(String typeReglementCompagnie) {
		this.typeReglementCompagnie = typeReglementCompagnie;
	}

}
