package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reglement generated by hbm2java
 */
@Entity
@Table(name = "reglement", catalog = "zeusbd")
public class Reglement implements java.io.Serializable {

	private String codeReglement;
	private Quittance quittance;
	private BigDecimal montantReglement;
	private Date dateReglement;
	private String modeReglement;
	private String numCheque;
	private String cpteBanque;
	private String nomTireur;
	private String steBanque;

	public Reglement() {
	}

	public Reglement(String codeReglement, Quittance quittance) {
		this.codeReglement = codeReglement;
		this.quittance = quittance;
	}

	public Reglement(String codeReglement, Quittance quittance,
			BigDecimal montantReglement, Date dateReglement,
			String modeReglement, String numCheque, String cpteBanque,
			String nomTireur, String steBanque) {
		this.codeReglement = codeReglement;
		this.quittance = quittance;
		this.montantReglement = montantReglement;
		this.dateReglement = dateReglement;
		this.modeReglement = modeReglement;
		this.numCheque = numCheque;
		this.cpteBanque = cpteBanque;
		this.nomTireur = nomTireur;
		this.steBanque = steBanque;
	}

	@Id
	@Column(name = "CODE_REGLEMENT", unique = true, nullable = false, length = 30)
	public String getCodeReglement() {
		return this.codeReglement;
	}

	public void setCodeReglement(String codeReglement) {
		this.codeReglement = codeReglement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_QUITTANCE", nullable = false)
	public Quittance getQuittance() {
		return this.quittance;
	}

	public void setQuittance(Quittance quittance) {
		this.quittance = quittance;
	}

	@Column(name = "MONTANT_REGLEMENT", precision = 15, scale = 3)
	public BigDecimal getMontantReglement() {
		return this.montantReglement;
	}

	public void setMontantReglement(BigDecimal montantReglement) {
		this.montantReglement = montantReglement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_REGLEMENT", length = 10)
	public Date getDateReglement() {
		return this.dateReglement;
	}

	public void setDateReglement(Date dateReglement) {
		this.dateReglement = dateReglement;
	}

	@Column(name = "MODE_REGLEMENT", length = 50)
	public String getModeReglement() {
		return this.modeReglement;
	}

	public void setModeReglement(String modeReglement) {
		this.modeReglement = modeReglement;
	}

	@Column(name = "NUM_CHEQUE", length = 50)
	public String getNumCheque() {
		return this.numCheque;
	}

	public void setNumCheque(String numCheque) {
		this.numCheque = numCheque;
	}

	@Column(name = "CPTE_BANQUE", length = 30)
	public String getCpteBanque() {
		return this.cpteBanque;
	}

	public void setCpteBanque(String cpteBanque) {
		this.cpteBanque = cpteBanque;
	}

	@Column(name = "NOM_TIREUR", length = 150)
	public String getNomTireur() {
		return this.nomTireur;
	}

	public void setNomTireur(String nomTireur) {
		this.nomTireur = nomTireur;
	}

	@Column(name = "STE_BANQUE", length = 50)
	public String getSteBanque() {
		return this.steBanque;
	}

	public void setSteBanque(String steBanque) {
		this.steBanque = steBanque;
	}

}
