package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ria generated by hbm2java
 */
@Entity
@Table(name = "ria", catalog = "zeusbd")
public class Ria implements java.io.Serializable {

	private String codeCria;
	private String codeEtatCima;
	private BigDecimal reporExoPrDeb;
	private BigDecimal pertesDeLExerciceDebit;
	private BigDecimal dividendeDeb;
	private BigDecimal tantiemDeb;
	private BigDecimal afectResDeb;
	private BigDecimal afectAutrResDeb;
	private BigDecimal autreRepartDeb;
	private BigDecimal reporNvBnfDeb;
	private BigDecimal totalDeb;
	private BigDecimal reporProvCred;
	private BigDecimal benefExoCred;
	private BigDecimal prevResCred;
	private BigDecimal reporNvCred;
	private BigDecimal totalCred;
	private String libelleRia;
	private Date dateRia;

	public Ria() {
	}

	public Ria(String codeCria) {
		this.codeCria = codeCria;
	}

	public Ria(String codeCria, String codeEtatCima, BigDecimal reporExoPrDeb,
			BigDecimal pertesDeLExerciceDebit, BigDecimal dividendeDeb,
			BigDecimal tantiemDeb, BigDecimal afectResDeb,
			BigDecimal afectAutrResDeb, BigDecimal autreRepartDeb,
			BigDecimal reporNvBnfDeb, BigDecimal totalDeb,
			BigDecimal reporProvCred, BigDecimal benefExoCred,
			BigDecimal prevResCred, BigDecimal reporNvCred,
			BigDecimal totalCred, String libelleRia, Date dateRia) {
		this.codeCria = codeCria;
		this.codeEtatCima = codeEtatCima;
		this.reporExoPrDeb = reporExoPrDeb;
		this.pertesDeLExerciceDebit = pertesDeLExerciceDebit;
		this.dividendeDeb = dividendeDeb;
		this.tantiemDeb = tantiemDeb;
		this.afectResDeb = afectResDeb;
		this.afectAutrResDeb = afectAutrResDeb;
		this.autreRepartDeb = autreRepartDeb;
		this.reporNvBnfDeb = reporNvBnfDeb;
		this.totalDeb = totalDeb;
		this.reporProvCred = reporProvCred;
		this.benefExoCred = benefExoCred;
		this.prevResCred = prevResCred;
		this.reporNvCred = reporNvCred;
		this.totalCred = totalCred;
		this.libelleRia = libelleRia;
		this.dateRia = dateRia;
	}

	@Id
	@Column(name = "CODE_CRIA", unique = true, nullable = false, length = 20)
	public String getCodeCria() {
		return this.codeCria;
	}

	public void setCodeCria(String codeCria) {
		this.codeCria = codeCria;
	}

	@Column(name = "CODE_ETAT_CIMA", length = 20)
	public String getCodeEtatCima() {
		return this.codeEtatCima;
	}

	public void setCodeEtatCima(String codeEtatCima) {
		this.codeEtatCima = codeEtatCima;
	}

	@Column(name = "REPOR_EXO_PR_DEB", precision = 15, scale = 3)
	public BigDecimal getReporExoPrDeb() {
		return this.reporExoPrDeb;
	}

	public void setReporExoPrDeb(BigDecimal reporExoPrDeb) {
		this.reporExoPrDeb = reporExoPrDeb;
	}

	@Column(name = "PERTES_DE_L_EXERCICE_DEBIT", precision = 15, scale = 3)
	public BigDecimal getPertesDeLExerciceDebit() {
		return this.pertesDeLExerciceDebit;
	}

	public void setPertesDeLExerciceDebit(BigDecimal pertesDeLExerciceDebit) {
		this.pertesDeLExerciceDebit = pertesDeLExerciceDebit;
	}

	@Column(name = "DIVIDENDE_DEB", precision = 15, scale = 3)
	public BigDecimal getDividendeDeb() {
		return this.dividendeDeb;
	}

	public void setDividendeDeb(BigDecimal dividendeDeb) {
		this.dividendeDeb = dividendeDeb;
	}

	@Column(name = "TANTIEM_DEB", precision = 15, scale = 3)
	public BigDecimal getTantiemDeb() {
		return this.tantiemDeb;
	}

	public void setTantiemDeb(BigDecimal tantiemDeb) {
		this.tantiemDeb = tantiemDeb;
	}

	@Column(name = "AFECT_RES_DEB", precision = 15, scale = 3)
	public BigDecimal getAfectResDeb() {
		return this.afectResDeb;
	}

	public void setAfectResDeb(BigDecimal afectResDeb) {
		this.afectResDeb = afectResDeb;
	}

	@Column(name = "AFECT_AUTR_RES_DEB", precision = 15, scale = 3)
	public BigDecimal getAfectAutrResDeb() {
		return this.afectAutrResDeb;
	}

	public void setAfectAutrResDeb(BigDecimal afectAutrResDeb) {
		this.afectAutrResDeb = afectAutrResDeb;
	}

	@Column(name = "AUTRE_REPART_DEB", precision = 15, scale = 3)
	public BigDecimal getAutreRepartDeb() {
		return this.autreRepartDeb;
	}

	public void setAutreRepartDeb(BigDecimal autreRepartDeb) {
		this.autreRepartDeb = autreRepartDeb;
	}

	@Column(name = "REPOR_NV_BNF_DEB", precision = 15, scale = 3)
	public BigDecimal getReporNvBnfDeb() {
		return this.reporNvBnfDeb;
	}

	public void setReporNvBnfDeb(BigDecimal reporNvBnfDeb) {
		this.reporNvBnfDeb = reporNvBnfDeb;
	}

	@Column(name = "TOTAL_DEB", precision = 15, scale = 3)
	public BigDecimal getTotalDeb() {
		return this.totalDeb;
	}

	public void setTotalDeb(BigDecimal totalDeb) {
		this.totalDeb = totalDeb;
	}

	@Column(name = "REPOR_PROV_CRED", precision = 15, scale = 3)
	public BigDecimal getReporProvCred() {
		return this.reporProvCred;
	}

	public void setReporProvCred(BigDecimal reporProvCred) {
		this.reporProvCred = reporProvCred;
	}

	@Column(name = "BENEF_EXO_CRED", precision = 15, scale = 3)
	public BigDecimal getBenefExoCred() {
		return this.benefExoCred;
	}

	public void setBenefExoCred(BigDecimal benefExoCred) {
		this.benefExoCred = benefExoCred;
	}

	@Column(name = "PREV_RES_CRED", precision = 15, scale = 3)
	public BigDecimal getPrevResCred() {
		return this.prevResCred;
	}

	public void setPrevResCred(BigDecimal prevResCred) {
		this.prevResCred = prevResCred;
	}

	@Column(name = "REPOR_NV_CRED", precision = 15, scale = 3)
	public BigDecimal getReporNvCred() {
		return this.reporNvCred;
	}

	public void setReporNvCred(BigDecimal reporNvCred) {
		this.reporNvCred = reporNvCred;
	}

	@Column(name = "TOTAL_CRED", precision = 15, scale = 3)
	public BigDecimal getTotalCred() {
		return this.totalCred;
	}

	public void setTotalCred(BigDecimal totalCred) {
		this.totalCred = totalCred;
	}

	@Column(name = "LIBELLE_RIA", length = 100)
	public String getLibelleRia() {
		return this.libelleRia;
	}

	public void setLibelleRia(String libelleRia) {
		this.libelleRia = libelleRia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_RIA", length = 19)
	public Date getDateRia() {
		return this.dateRia;
	}

	public void setDateRia(Date dateRia) {
		this.dateRia = dateRia;
	}

}
