package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RisqueNtaSinistre generated by hbm2java
 */
@Entity
@Table(name = "risque_nta_sinistre", catalog = "zeusbd")
public class RisqueNtaSinistre implements java.io.Serializable {

	private RisqueNtaSinistreId id;
	private RisqueNta risqueNta;
	private Sinistre sinistre;
	private String circonstanceSinistreNta;
	private String natureRisqueNta;
	private Boolean domageMatNta;
	private Boolean domageCorpNta;
	private BigDecimal respAssureNta;
	private Integer nbreVictimeNta;
	private Integer nbreBlesseNta;
	private Integer nbreDecesNta;
	private Date dateSinistreNta;

	public RisqueNtaSinistre() {
	}

	public RisqueNtaSinistre(RisqueNtaSinistreId id, RisqueNta risqueNta,
			Sinistre sinistre) {
		this.id = id;
		this.risqueNta = risqueNta;
		this.sinistre = sinistre;
	}

	public RisqueNtaSinistre(RisqueNtaSinistreId id, RisqueNta risqueNta,
			Sinistre sinistre, String circonstanceSinistreNta,
			String natureRisqueNta, Boolean domageMatNta,
			Boolean domageCorpNta, BigDecimal respAssureNta,
			Integer nbreVictimeNta, Integer nbreBlesseNta,
			Integer nbreDecesNta, Date dateSinistreNta) {
		this.id = id;
		this.risqueNta = risqueNta;
		this.sinistre = sinistre;
		this.circonstanceSinistreNta = circonstanceSinistreNta;
		this.natureRisqueNta = natureRisqueNta;
		this.domageMatNta = domageMatNta;
		this.domageCorpNta = domageCorpNta;
		this.respAssureNta = respAssureNta;
		this.nbreVictimeNta = nbreVictimeNta;
		this.nbreBlesseNta = nbreBlesseNta;
		this.nbreDecesNta = nbreDecesNta;
		this.dateSinistreNta = dateSinistreNta;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeSinistre", column = @Column(name = "CODE_SINISTRE", nullable = false, length = 40)),
			@AttributeOverride(name = "codeRisquenta", column = @Column(name = "CODE_RISQUENTA", nullable = false, length = 30)) })
	public RisqueNtaSinistreId getId() {
		return this.id;
	}

	public void setId(RisqueNtaSinistreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_RISQUENTA", nullable = false, insertable = false, updatable = false)
	public RisqueNta getRisqueNta() {
		return this.risqueNta;
	}

	public void setRisqueNta(RisqueNta risqueNta) {
		this.risqueNta = risqueNta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_SINISTRE", nullable = false, insertable = false, updatable = false)
	public Sinistre getSinistre() {
		return this.sinistre;
	}

	public void setSinistre(Sinistre sinistre) {
		this.sinistre = sinistre;
	}

	@Column(name = "CIRCONSTANCE_SINISTRE_NTA", length = 65535)
	public String getCirconstanceSinistreNta() {
		return this.circonstanceSinistreNta;
	}

	public void setCirconstanceSinistreNta(String circonstanceSinistreNta) {
		this.circonstanceSinistreNta = circonstanceSinistreNta;
	}

	@Column(name = "NATURE_RISQUE_NTA", length = 80)
	public String getNatureRisqueNta() {
		return this.natureRisqueNta;
	}

	public void setNatureRisqueNta(String natureRisqueNta) {
		this.natureRisqueNta = natureRisqueNta;
	}

	@Column(name = "DOMAGE_MAT_NTA")
	public Boolean getDomageMatNta() {
		return this.domageMatNta;
	}

	public void setDomageMatNta(Boolean domageMatNta) {
		this.domageMatNta = domageMatNta;
	}

	@Column(name = "DOMAGE_CORP_NTA")
	public Boolean getDomageCorpNta() {
		return this.domageCorpNta;
	}

	public void setDomageCorpNta(Boolean domageCorpNta) {
		this.domageCorpNta = domageCorpNta;
	}

	@Column(name = "RESP_ASSURE_NTA", precision = 15, scale = 3)
	public BigDecimal getRespAssureNta() {
		return this.respAssureNta;
	}

	public void setRespAssureNta(BigDecimal respAssureNta) {
		this.respAssureNta = respAssureNta;
	}

	@Column(name = "NBRE_VICTIME_NTA")
	public Integer getNbreVictimeNta() {
		return this.nbreVictimeNta;
	}

	public void setNbreVictimeNta(Integer nbreVictimeNta) {
		this.nbreVictimeNta = nbreVictimeNta;
	}

	@Column(name = "NBRE_BLESSE_NTA")
	public Integer getNbreBlesseNta() {
		return this.nbreBlesseNta;
	}

	public void setNbreBlesseNta(Integer nbreBlesseNta) {
		this.nbreBlesseNta = nbreBlesseNta;
	}

	@Column(name = "NBRE_DECES_NTA")
	public Integer getNbreDecesNta() {
		return this.nbreDecesNta;
	}

	public void setNbreDecesNta(Integer nbreDecesNta) {
		this.nbreDecesNta = nbreDecesNta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_SINISTRE_NTA", length = 19)
	public Date getDateSinistreNta() {
		return this.dateSinistreNta;
	}

	public void setDateSinistreNta(Date dateSinistreNta) {
		this.dateSinistreNta = dateSinistreNta;
	}

}
