package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sinistresurvenu generated by hbm2java
 */
@Entity
@Table(name = "sinistresurvenu", catalog = "zeusbd")
public class Sinistresurvenu implements java.io.Serializable {

	private int idsinsurv;
	private Integer numsurven;
	private Date dateDebut;
	private Date dateFin;
	private String nomPeriode;
	private BigDecimal mtantsinistre;
	private Set<Paiemtsinistre> paiemtsinistres = new HashSet<Paiemtsinistre>(0);

	public Sinistresurvenu() {
	}

	public Sinistresurvenu(int idsinsurv) {
		this.idsinsurv = idsinsurv;
	}

	public Sinistresurvenu(int idsinsurv, Integer numsurven, Date dateDebut,
			Date dateFin, String nomPeriode, BigDecimal mtantsinistre,
			Set<Paiemtsinistre> paiemtsinistres) {
		this.idsinsurv = idsinsurv;
		this.numsurven = numsurven;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.nomPeriode = nomPeriode;
		this.mtantsinistre = mtantsinistre;
		this.paiemtsinistres = paiemtsinistres;
	}

	@Id
	@Column(name = "IDSINSURV", unique = true, nullable = false)
	public int getIdsinsurv() {
		return this.idsinsurv;
	}

	public void setIdsinsurv(int idsinsurv) {
		this.idsinsurv = idsinsurv;
	}

	@Column(name = "NUMSURVEN")
	public Integer getNumsurven() {
		return this.numsurven;
	}

	public void setNumsurven(Integer numsurven) {
		this.numsurven = numsurven;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEBUT", length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "NOM_PERIODE", length = 60)
	public String getNomPeriode() {
		return this.nomPeriode;
	}

	public void setNomPeriode(String nomPeriode) {
		this.nomPeriode = nomPeriode;
	}

	@Column(name = "MTANTSINISTRE")
	public BigDecimal getMtantsinistre() {
		return this.mtantsinistre;
	}

	public void setMtantsinistre(BigDecimal mtantsinistre) {
		this.mtantsinistre = mtantsinistre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistresurvenu")
	public Set<Paiemtsinistre> getPaiemtsinistres() {
		return this.paiemtsinistres;
	}

	public void setPaiemtsinistres(Set<Paiemtsinistre> paiemtsinistres) {
		this.paiemtsinistres = paiemtsinistres;
	}

}
