package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock", catalog = "zeusbd")
public class Stock implements java.io.Serializable {

	private String idStock;
	private PointVente pointVente;
	private Date datestock;
	private Long stkinit;
	private Long stkrst;
	private String situation;
	private Set<Attestation> attestations = new HashSet<Attestation>(0);

	public Stock() {
	}

	public Stock(String idStock, PointVente pointVente) {
		this.idStock = idStock;
		this.pointVente = pointVente;
	}

	public Stock(String idStock, PointVente pointVente, Date datestock,
			Long stkinit, Long stkrst, String situation,
			Set<Attestation> attestations) {
		this.idStock = idStock;
		this.pointVente = pointVente;
		this.datestock = datestock;
		this.stkinit = stkinit;
		this.stkrst = stkrst;
		this.situation = situation;
		this.attestations = attestations;
	}

	@Id
	@Column(name = "ID_STOCK", unique = true, nullable = false, length = 15)
	public String getIdStock() {
		return this.idStock;
	}

	public void setIdStock(String idStock) {
		this.idStock = idStock;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_POINT_VENTE", nullable = false)
	public PointVente getPointVente() {
		return this.pointVente;
	}

	public void setPointVente(PointVente pointVente) {
		this.pointVente = pointVente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATESTOCK", length = 10)
	public Date getDatestock() {
		return this.datestock;
	}

	public void setDatestock(Date datestock) {
		this.datestock = datestock;
	}

	@Column(name = "STKINIT")
	public Long getStkinit() {
		return this.stkinit;
	}

	public void setStkinit(Long stkinit) {
		this.stkinit = stkinit;
	}

	@Column(name = "STKRST")
	public Long getStkrst() {
		return this.stkrst;
	}

	public void setStkrst(Long stkrst) {
		this.stkrst = stkrst;
	}

	@Column(name = "SITUATION", length = 60)
	public String getSituation() {
		return this.situation;
	}

	public void setSituation(String situation) {
		this.situation = situation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stock")
	public Set<Attestation> getAttestations() {
		return this.attestations;
	}

	public void setAttestations(Set<Attestation> attestations) {
		this.attestations = attestations;
	}

}
