package com.j3a.assurance.model;

// Generated 12 août 2015 16:21:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tarifweb generated by hbm2java
 */
@Entity
@Table(name = "tarifweb", catalog = "zeusbd")
public class Tarifweb implements java.io.Serializable {

	private String codeTarifWeb;
	private CompagnieAssurance compagnieAssurance;
	private Tarif tarif;
	private String libelleTarifWeb;
	private Set<TarifwebSousCat> tarifwebSousCats = new HashSet<TarifwebSousCat>(
			0);

	public Tarifweb() {
	}

	public Tarifweb(String codeTarifWeb) {
		this.codeTarifWeb = codeTarifWeb;
	}

	public Tarifweb(String codeTarifWeb, CompagnieAssurance compagnieAssurance,
			Tarif tarif, String libelleTarifWeb,
			Set<TarifwebSousCat> tarifwebSousCats) {
		this.codeTarifWeb = codeTarifWeb;
		this.compagnieAssurance = compagnieAssurance;
		this.tarif = tarif;
		this.libelleTarifWeb = libelleTarifWeb;
		this.tarifwebSousCats = tarifwebSousCats;
	}

	@Id
	@Column(name = "CODE_TARIF_WEB", unique = true, nullable = false, length = 16)
	public String getCodeTarifWeb() {
		return this.codeTarifWeb;
	}

	public void setCodeTarifWeb(String codeTarifWeb) {
		this.codeTarifWeb = codeTarifWeb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_COMPAGNIE_ASSURANCE")
	public CompagnieAssurance getCompagnieAssurance() {
		return this.compagnieAssurance;
	}

	public void setCompagnieAssurance(CompagnieAssurance compagnieAssurance) {
		this.compagnieAssurance = compagnieAssurance;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_TARIF")
	public Tarif getTarif() {
		return this.tarif;
	}

	public void setTarif(Tarif tarif) {
		this.tarif = tarif;
	}

	@Column(name = "LIBELLE_TARIF_WEB", length = 100)
	public String getLibelleTarifWeb() {
		return this.libelleTarifWeb;
	}

	public void setLibelleTarifWeb(String libelleTarifWeb) {
		this.libelleTarifWeb = libelleTarifWeb;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarifweb")
	public Set<TarifwebSousCat> getTarifwebSousCats() {
		return this.tarifwebSousCats;
	}

	public void setTarifwebSousCats(Set<TarifwebSousCat> tarifwebSousCats) {
		this.tarifwebSousCats = tarifwebSousCats;
	}

}
