package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "zeusbd")
public class UserRole implements java.io.Serializable {

	private int userRoleId;
	private String autority;
	private Set<Personne> personnes = new HashSet<Personne>(0);

	public UserRole() {
	}

	public UserRole(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	public UserRole(int userRoleId, String autority, Set<Personne> personnes) {
		this.userRoleId = userRoleId;
		this.autority = autority;
		this.personnes = personnes;
	}

	@Id
	@Column(name = "USER_ROLE_ID", unique = true, nullable = false)
	public int getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "AUTORITY", length = 45)
	public String getAutority() {
		return this.autority;
	}

	public void setAutority(String autority) {
		this.autority = autority;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRole")
	public Set<Personne> getPersonnes() {
		return this.personnes;
	}

	public void setPersonnes(Set<Personne> personnes) {
		this.personnes = personnes;
	}

}
