package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "zeusbd")
public class Utilisateur implements java.io.Serializable {

	private String codeUtilisateur;
	private PointVente pointVente;
	private String matricule;
	private String nomUtilisateur;
	private String prenomUtilisateur;
	private Date dateCreationUtilisateur;
	private String loginUtilisateur;
	private String motPasse;
	private String mailUtilisateur;
	private Integer activite;
	private Set<Avenant> avenants = new HashSet<Avenant>(0);
	private Set<ProfilUtilisateur> profilUtilisateurs = new HashSet<ProfilUtilisateur>(
			0);

	public Utilisateur() {
	}

	public Utilisateur(String codeUtilisateur, PointVente pointVente) {
		this.codeUtilisateur = codeUtilisateur;
		this.pointVente = pointVente;
	}

	public Utilisateur(String codeUtilisateur, PointVente pointVente,
			String matricule, String nomUtilisateur, String prenomUtilisateur,
			Date dateCreationUtilisateur, String loginUtilisateur,
			String motPasse, String mailUtilisateur, Integer activite,
			Set<Avenant> avenants, Set<ProfilUtilisateur> profilUtilisateurs) {
		this.codeUtilisateur = codeUtilisateur;
		this.pointVente = pointVente;
		this.matricule = matricule;
		this.nomUtilisateur = nomUtilisateur;
		this.prenomUtilisateur = prenomUtilisateur;
		this.dateCreationUtilisateur = dateCreationUtilisateur;
		this.loginUtilisateur = loginUtilisateur;
		this.motPasse = motPasse;
		this.mailUtilisateur = mailUtilisateur;
		this.activite = activite;
		this.avenants = avenants;
		this.profilUtilisateurs = profilUtilisateurs;
	}

	@Id
	@Column(name = "CODE_UTILISATEUR", unique = true, nullable = false, length = 10)
	public String getCodeUtilisateur() {
		return this.codeUtilisateur;
	}

	public void setCodeUtilisateur(String codeUtilisateur) {
		this.codeUtilisateur = codeUtilisateur;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_POINT_VENTE", nullable = false)
	public PointVente getPointVente() {
		return this.pointVente;
	}

	public void setPointVente(PointVente pointVente) {
		this.pointVente = pointVente;
	}

	@Column(name = "MATRICULE", length = 20)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "NOM_UTILISATEUR", length = 25)
	public String getNomUtilisateur() {
		return this.nomUtilisateur;
	}

	public void setNomUtilisateur(String nomUtilisateur) {
		this.nomUtilisateur = nomUtilisateur;
	}

	@Column(name = "PRENOM_UTILISATEUR", length = 60)
	public String getPrenomUtilisateur() {
		return this.prenomUtilisateur;
	}

	public void setPrenomUtilisateur(String prenomUtilisateur) {
		this.prenomUtilisateur = prenomUtilisateur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CREATION_UTILISATEUR", length = 10)
	public Date getDateCreationUtilisateur() {
		return this.dateCreationUtilisateur;
	}

	public void setDateCreationUtilisateur(Date dateCreationUtilisateur) {
		this.dateCreationUtilisateur = dateCreationUtilisateur;
	}

	@Column(name = "LOGIN_UTILISATEUR", length = 30)
	public String getLoginUtilisateur() {
		return this.loginUtilisateur;
	}

	public void setLoginUtilisateur(String loginUtilisateur) {
		this.loginUtilisateur = loginUtilisateur;
	}

	@Column(name = "MOT_PASSE", length = 10)
	public String getMotPasse() {
		return this.motPasse;
	}

	public void setMotPasse(String motPasse) {
		this.motPasse = motPasse;
	}

	@Column(name = "MAIL_UTILISATEUR", length = 50)
	public String getMailUtilisateur() {
		return this.mailUtilisateur;
	}

	public void setMailUtilisateur(String mailUtilisateur) {
		this.mailUtilisateur = mailUtilisateur;
	}

	@Column(name = "ACTIVITE")
	public Integer getActivite() {
		return this.activite;
	}

	public void setActivite(Integer activite) {
		this.activite = activite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Avenant> getAvenants() {
		return this.avenants;
	}

	public void setAvenants(Set<Avenant> avenants) {
		this.avenants = avenants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<ProfilUtilisateur> getProfilUtilisateurs() {
		return this.profilUtilisateurs;
	}

	public void setProfilUtilisateurs(Set<ProfilUtilisateur> profilUtilisateurs) {
		this.profilUtilisateurs = profilUtilisateurs;
	}

}
