package com.j3a.assurance.model;

// Generated 6 juil. 2015 11:25:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vente generated by hbm2java
 */
@Entity
@Table(name = "vente", catalog = "zeusbd")
public class Vente implements java.io.Serializable {

	private String codePortefeilles;
	private String natureVente;
	private String acquereurVente;
	private BigDecimal montantVente;

	public Vente() {
	}

	public Vente(String codePortefeilles) {
		this.codePortefeilles = codePortefeilles;
	}

	public Vente(String codePortefeilles, String natureVente,
			String acquereurVente, BigDecimal montantVente) {
		this.codePortefeilles = codePortefeilles;
		this.natureVente = natureVente;
		this.acquereurVente = acquereurVente;
		this.montantVente = montantVente;
	}

	@Id
	@Column(name = "CODE_PORTEFEILLES", unique = true, nullable = false, length = 20)
	public String getCodePortefeilles() {
		return this.codePortefeilles;
	}

	public void setCodePortefeilles(String codePortefeilles) {
		this.codePortefeilles = codePortefeilles;
	}

	@Column(name = "NATURE_VENTE", length = 20)
	public String getNatureVente() {
		return this.natureVente;
	}

	public void setNatureVente(String natureVente) {
		this.natureVente = natureVente;
	}

	@Column(name = "ACQUEREUR_VENTE", length = 20)
	public String getAcquereurVente() {
		return this.acquereurVente;
	}

	public void setAcquereurVente(String acquereurVente) {
		this.acquereurVente = acquereurVente;
	}

	@Column(name = "MONTANT_VENTE", precision = 15, scale = 3)
	public BigDecimal getMontantVente() {
		return this.montantVente;
	}

	public void setMontantVente(BigDecimal montantVente) {
		this.montantVente = montantVente;
	}

}
